### ISSUE TITLE
Blast furnace broke

### ISSUE THREAD

**Issue by delightDEM** [zymex22/Project-RimFactory-Revived#101]
i build the furnce and it wont let me do anything with it i have it powerd and the supplies to do what i need and it wont do anything. i cant play the mod if i cant use it to build machine frames

**Comment by lilwhitemouse** [comment]
Any errors?

**Comment by Steague** [comment]
@zymex22 is there a reason you only gave this issue 5 hours of time for the initial poster to respond?

Please provide reasoning for closing issues in the future.

Valid reasons examples:
- Closed - Not a bug
- Closed - Not enough information
- Resolved - Through PR

**Comment by zymex22** [comment]
closed because answered in Discord, and not a bug, just wrong use of mod.
