### ISSUE TITLE
Meat Grinder Building Allows Non-Fresh Corpses and Butchers Them

### ISSUE THREAD

**Issue by Steague** [zymex22/Project-RimFactory-Revived#104]
RimWorld Version: 1.1.2654 (64-bit)
HarmonyLIb Version: 2.0.1.0 Mod 1.0.2.0
PRF Version: 2.2.7

Reproducibility: Always
Severity: Major
Type: Functional
Regression: No

Description: The meat grinder building allows rotten/skeleton corpses to be butchered.

Expected Behavior: The meat grinder building only allows fresh corpses to be butchered.
Actual Behavior: The meat grinder building allows rotten/skeleton corpses to be butchered.

**Comment by lilwhitemouse** [comment]
Ew.

I was going to point out that some mods allow butchering such corpses for bones...but ew.

**Comment by zymex22** [comment]
Fixed with #124
