### ISSUE TITLE
Underground roller entrance/exits very difficult to place

### ISSUE THREAD

**Issue by lilwhitemouse** [zymex22/Project-RimFactory-Revived#105]
The blueprints for the rollers themselves are excellent: you can see which way they go.  But the blueprints for the entrance/exits for underground rollers?  Very difficult to figure out which direction they point.  So far I have a 50% success rate.

They need a clear indication of direction.

Until that time, they might be made "minifiable" so a player can change where they go.

**Comment by zymex22** [comment]
i fixed this
- both made it minifiedable and added arrows to them

i close
