### ISSUE TITLE
Rollers have differing power profiles

### ISSUE THREAD

**Issue by lilwhitemouse** [zymex22/Project-RimFactory-Revived#106]
Some of the roller buildings act as power transmitters.
- Pros: easy to keep them all powered
- Cons: while they are being built (frame stage of building), they interrupt current power grid by deactivating power conduits placed in the same cell.

Other roller buildings use power like regular buildings.
- Pros: avoid Cons above
- Cons: have to also place power conduit.

One way or another, they should be the same system.

Potential options:
- Make them all "power conduit"-like.
-- If they can coexist with power conduits somehow, that would be excellent
- Make them all Plug-into-wall
-- Maybe reduce steel by 1 for the extra cost?

**Comment by zymex22** [comment]
i have been playing with this before but nobos code are restricted on it ill try again see if i can make it work same way all of them.
i think ill go with first one for better power transport and less clutter on wires on floor

**Comment by zymex22** [comment]
might be puller also need to do the same but dunno? but now i have set underground and wall to work same way =)
