### ISSUE TITLE
red error for duplicate entry concrete 

### ISSUE THREAD

**Issue by Mathus2002** [zymex22/Project-RimFactory-Revived#111]
**Describe the bug**
red error for duplicate entry concrete 

https://gist.github.com/ed7fb6efd8b71c24284e35265ba3a42d

**Actual Behavior**
no actual problem seems to happen in game.  but it does error on loading up the game.

generating the follwing error:

XML error: Duplicate XML node name designatorDropdown in this XML block: <TerrainDef ParentName="FloorBase"><defName>Concrete</defName><label>concrete</label><description>Rough concrete. It is cheap and quick to build, but is also quite ugly.</description><texturePath>Terrain/Surfaces/Concrete</texturePath><edgeType>Hard</edgeType><renderPrecedence>355</renderPrecedence><statBases><Beauty>-1</Beauty><WorkToBuild>100</WorkToBuild></statBases><costList><Steel>1</Steel></costList><designationHotKey>Misc6</designationHotKey><researchPrerequisites><li>Stonecutting</li></researchPrerequisites><designatorDropdown>Floor_Concrete</designatorDropdown><designatorDropdown>PRF_ConcreteFloor</designatorDropdown></TerrainDef>
Verse.Log:Error(String, Boolean)
Verse.XmlInheritance:CheckForDuplicateNodes(XmlNode, XmlNode)
Verse.XmlInheritance:ResolveXmlNodeFor(XmlInheritanceNode)
Verse.XmlInheritance:ResolveXmlNodesRecursively(XmlInheritanceNode)
Verse.XmlInheritance:ResolveXmlNodesRecursively(XmlInheritanceNode)
Verse.XmlInheritance:ResolveXmlNodes()
Verse.XmlInheritance:Resolve()
Verse.LoadedModManager:ParseAndProcessXML(XmlDocument, Dictionary`2)
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

**Comment by zymex22** [comment]
you have another mode creating a concrete floor, wich one is creating a extra floor? then i can make a patch for it

**Comment by zymex22** [comment]
Compatible problem with Armored floors mod, i made a patch for it to check if its installed and then not collapse my concrete...

its up on next update so i close this issue
