### ISSUE TITLE
Conveyors can output items into walls.

### ISSUE THREAD

**Issue by lilwhitemouse** [zymex22/Project-RimFactory-Revived#112]
**Describe the bug**

If you have a setup like this:
->->->->W
then the conveyors will push their cargo into the wall.  Ooops.

**Comment by lilwhitemouse** [comment]
Question to think about: if the conveyor is already branching, and one branch direction is pointed into a wall, should it change the direction of the conveyor?

**Comment by zymex22** [comment]
@lilwhitemouse can this be closed?

**Comment by lilwhitemouse** [comment]
Placing code now checks for impassable
