### ISSUE TITLE
There is no way to get items off a conveyor belt

### ISSUE THREAD

**Issue by lilwhitemouse** [zymex22/Project-RimFactory-Revived#113]
If the belt cannot place the item, the item is stuck there - no one can remove it.

If we want to say conveyors are 10' in the air, we can close this "Won't Fix"

**Comment by zymex22** [comment]
i think that will be fixed with #70

**Comment by zymex22** [comment]
@lilwhitemouse can this be closed? since your redoing it anyways?

**Comment by lilwhitemouse** [comment]
What IS desired behavior if an item is stuck on a conveyor belt that cannot place it?

**Comment by zymex22** [comment]
exploding ofc?!

:P - i guess it would be wait to be able to place or stack...
theres also that "overflow" option but kinda not like that too much... 

nobo had that on pullers before so if a stockpile was full it would overflow out from that that stockpile into nearby cells :P

**Comment by lilwhitemouse** [comment]
That's a possibility. Also possible is they become haulable by pawns?

**Comment by zymex22** [comment]
if thats possible i guess thats also a option so a pawn can free up the clogging of belts

**Comment by lilwhitemouse** [comment]
Player can drop items off a conveyor belt.  There is currently no way to allow a Pawn to do so.

We should probably find a way to add Right-Click options t things carried on belts.

**Comment by zymex22** [comment]
i think this is a "wont fix" @lilwhitemouse ....
that drop items of belt button is plenty option for now...

better than before where no option was present, this can properly just be closed, try get a pawn right click option to work is more a pain than just drop of the belt and let a pawn use it....

it would have moved 10 belts before pawn get to it....

i close? reopen if needed.
