### ISSUE TITLE
Range power slider for Generic harvester

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#117]
Add nobo's power slider to boost range on generic animal harvester.
seems like a good fit to be a better upgrade over Shearer and milker.

as 1 square is pretty low in most setups.

it would need to be added to use this comp:
```xml
      <li Class="ProjectRimFactory.Common.CompProperties_PowerWorkSetting">
        <!-- speed settings -->
        <speedSetting>true</speedSetting>
        <minPowerForSpeed>0</minPowerForSpeed>
        <minSpeedFactor>1</minSpeedFactor>
        <maxPowerForSpeed>3000</maxPowerForSpeed>
        <maxSpeedFactor>3</maxSpeedFactor>
        <!-- range settings -->
        <rangeSetting>true</rangeSetting>
        <minPowerForRange>0</minPowerForRange>
        <minRange>1</minRange>
        <maxPowerForRange>1500</maxPowerForRange>
        <maxRange>4</maxRange>
        <rangeType>ProjectRimFactory.Common.RectRange</rangeType>
      </li>
```
like assembler can do (spacer cooker in this example)

**Comment by zymex22** [comment]
@Sn1p3rr3c0n is this something you can do, should not interfere with assemblers or other things being worked on.

- Range is priority..
- not sure if speed should/could be used too, i see it has some time to harvest from animals.

**Comment by Sn1p3rr3c0n** [comment]
@zymex22  as far as i can tell the process is instant. the building operates on `rare tick` so to speed it up i could choose another tick ore actually implement a task to complete

**Comment by zymex22** [comment]
LWM say its be we have as many building as possible to run on Rare as it saves performance.
so base machine should keep rare i guess?

if speed cant be adjusted then, range only is also fine =)

**Comment by zymex22** [comment]
OH actually your right! i forgot....

it harvest directly from a animal EVEN if its not 100% ready to harvest woool yet, so it will just pick 1 wool everytime it hit 1% thats why i tohught there was speed too =)

then nvm speed :P
