### ISSUE TITLE
power use on "assemblers"

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#120]
**Comment from Malkav in steam comments:**
I've found a glitch with the Metal Refinery. When I first load a save, it shows a power consumption of 0W. Once selected and the power tab opened, it changes to the correct amount and works properly. While it is at 0W, it runs at normal speed even though it's using no power.

Is this a new bug after Fueled was applied to assemblers? (metal refinery is using assembler thingclalss)

**Comment by malkav73** [comment]
I tracked it down to the comp class ProjectRimFactory.Common.CompProperties_PowerWorkSetting. It starts at minimum and doesn't reset/activate by itself after loading a save, until the power tab is opened for each building using it.

**Comment by lilwhitemouse** [comment]
It looks to me like it should reset after loading? The comp calls SetPower() on init after load, which looks right.

What were you looking at?

On July 20, 2020 9:21:26 PM EDT, malkav73 <notifications@github.com> wrote:
>I tracked it down to the comp class
>ProjectRimFactory.Common.CompProperties_PowerWorkSetting. It starts at
>minimum and doesn't reset/activate by itself after loading a save,
>until the power tab is opened for each building using it.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/zymex22/Project-RimFactory-Revived/issues/120#issuecomment-661528665

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by malkav73** [comment]
I noticed all buildings' power from <compClass>CompPowerTrader</compClass> works right upon loading, but ProjectRimFactory.Common.CompProperties_PowerWorkSetting always starts at 0, until the Power Tab is opened.

**Comment by malkav73** [comment]
I just did a quick test to rule out mod conflicts. Loaded just Royalty, Harmony, Hugslib, and PRF. When placing a Metal Refinery, it initially showed 0W power, until I opened the Power tab.

**Comment by zymex22** [comment]
it should be the same on any "assembler" like buillding using power "boost" tab
so:
- metal refinery
- spacer cooker
- adaptive assembler


![image](https://user-images.githubusercontent.com/41029070/88102894-91d3bc80-cba0-11ea-95af-df223ca8d2b7.png)

**Comment by malkav73** [comment]
It is the same, mostly. But the devil is in the details. 
First off, the adaptive assembler does not have a speed adjustment, only range, so not relevant to this case.
The Spacer Cooker uses the vanilla CompProperties_Power to set basePowerConsumption 600, then uses ProjectRimFactory.Common.CompProperties_PowerWorkSetting to set an additional power range of 0-3000 for speed. It is this additional power that does not work until the power tab is opened.
On the Metal Refinery, CompProperties_Power sets basePowerConsumption to 0, then uses ProjectRimFactory.Common.CompProperties_PowerWorkSetting to set an additional power range of 3000-10000 for speed.

As a result, the Spacer Cooker starts out at 600, but the Metal Refinery starts at 0. On BOTH the additional power does not activate until the power tab is opened.

**Comment by zymex22** [comment]
we should actually try test T3 miner see if same problem is present there? that one run from another power option file from nobos mod, if its work there we might be able to compare why prf version dont start correctly.

t3 miner, animal manager are using that one

**Comment by Sn1p3rr3c0n** [comment]
The T3 Miner is unaffected.

**Comment by zymex22** [comment]
that one uses:
this one for range:
https://github.com/zymex22/Project-RimFactory-Revived/blob/master/Source/ProjectRimFactory/AutoMachineTool/ModExtension_WorkIORange.cs

this one for speed
https://github.com/zymex22/Project-RimFactory-Revived/blob/master/Source/ProjectRimFactory/AutoMachineTool/ModExtension_WorkSpeed.cs
