### ISSUE TITLE
"TryFindBestBillIngredientsInSet" Dos not check if a Thing is Allowed in the Bill

### ISSUE THREAD

**Issue by Sn1p3rr3c0n** [zymex22/Project-RimFactory-Revived#122]
**Describe the bug**
The function `bool TryFindBestBillIngredientsInSet(List<Thing> accessibleThings, Bill b, List<ThingCount> chosen)` in `\Source\ProjectRimFactory\SAL3\Things\Assemblers\Building_ProgrammableAssembler.cs` can return an item forbidden in the Bill as part of `chosen`.
This cause Bills to start that should not be able to start.

**To Reproduce**
Reproducibility: Systematic
1. Place a affected Building (example: "Meat Grinder" , "Industrial Furnace")
2. Create a Bill and limit the Allowed Items (Example: Cremate Corpse --> Disallow Fresh)
3. Provide Disallowed Thing (Example Kill a Pawn in range) 
4. Bill is Started.

**Expected behavior**
A Bill shall only be started if the the required ingredients are both available and allowed.

**Actual Behavior**
Its is not Checked if the Thing is allowed

Some Debug Code
 ```
     protected virtual BillReport CheckBills()
        {
            foreach (Bill b in AllBillsShouldDoNow)
            {
                List<ThingCount> chosen = new List<ThingCount>();
                //TryFindBestBillIngredientsInSet(AllAccessibleThings.ToList(), b, chosen) seems to allow things forbbedden in the Bill options

                if (TryFindBestBillIngredientsInSet(AllAccessibleThings.ToList(), b, chosen))
                {
                    //Log chosen Items
                    Log.Message(chosen[0].Thing.LabelShort);
                    //Log if that item is allowed or not
                    Log.Message(b.IsFixedOrAllowedIngredient(chosen[0].Thing).ToString()); 
                    


                    return new BillReport(b, (from ta in chosen select ta.Thing.SplitOff(ta.Count)).ToList());
                }
            }
            return null;
        }
```

this should also be the cause for #104 Meat Grinder Building Allows Non-Fresh Corpses and Butchers Them

**Comment by lilwhitemouse** [comment]
Oooo, I remember thinking that looked method looked ...not quite right

good catch
