### ISSUE TITLE
Assembler mute masterwork

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#123]
Assemblers have a tendency to throw a masterwork created notification even when its not even making a masterwork.

Solution?
mute notification and just let it create random quality as it wants, so it dont confuse ppl
OR
Fix it so it so it throw notification at right times and not just randomly

its from this comment and many other:

> i get a message saying "machine produced a masterwork anorak" but when i see said anorak it can be every quality, can be master or can be normal or horrible, etc, i use vanilla leathers and the other mods i have dont change anything of clothes

> There does seem to be something weird going on with the products it does make, however. Very often I get the alert that it has produced a masterwork item (clothing, weapons, even art), but it seems like what the assembler produces (and triggers the masterwork notification) and what it actually outputs are very different quality levels. This continues to occur even after the assembler gets a pretty high speed boost to crafting a certain product. By the way; thanks for updating and continuing work on this mod, I have thoroughly enjoyed it even if I'm getting a little confused about the assemblers.

**Comment by Sn1p3rr3c0n** [comment]
... now i know why this issue exists. We modify the rarity **after** it was already produced....
```
protected override void PostProcessRecipeProduct(Thing thing)
        {
            CompQuality compQuality = thing.TryGetComp<CompQuality>();
            if (compQuality != null)
            {
                compQuality.SetQuality(GetRandomProductionQuality(), ArtGenerationContext.Colony);
            }
        }
```

**Comment by zymex22** [comment]
so what can we do about it?
im not sure whats the right approach to it is?

@lilwhitemouse @Sn1p3rr3c0n

**Comment by Sn1p3rr3c0n** [comment]
I see two possibilities to resolve this:
1. Make our own implementation of `public static IEnumerable<Thing> MakeRecipeProducts(RecipeDef recipeDef, Pawn worker, List<Thing> ingredients, Thing dominantIngredient, IBillGiver billGiver)`
2. somehow override the following function `private static Thing PostProcessProduct(Thing product, RecipeDef recipeDef, Pawn worker)`

Both function are defined under `Verse.GenRecipe`

The first function determinants the product and then invokes the second to set the rarity.

@lilwhitemouse what do you think?

**Comment by zymex22** [comment]
@lilwhitemouse what do you think? :P

**Comment by lilwhitemouse** [comment]
Why are we manually setting the quality anyway? What's wrong with leaving the quality that was originally produced?

**Comment by lilwhitemouse** [comment]
As far as ways to block that message goes....

A destructive Harmony prefix to `RimWorld.QualityUtility.SendCraftNotification()` that checks if the worker is a machine (and alternately allows notifications if some static flag is set? so we can still trigger the notification directly if we want) should be easy.

**Comment by zymex22** [comment]
we are setting qual. manually because of assembler system where it getting smarter after repeating same process over and over again i would assume? =)

for the adaptive assembler it start our producing crap but if keep doing it will become better qual. and faster production time.

if it somehow can be controlled by normal production i guess thats ok too, just need that system to work still =)

**Comment by zymex22** [comment]
whats your input @lilwhitemouse

**Comment by lilwhitemouse** [comment]
I don't understand all (any) of the subtleties of why quality generation is done this way. It looks like we could directly increase skill level of the assembler-pawn as an alternate approach, but I have no idea what that would do to in-game behavior. Perhaps ask S

**Comment by lilwhitemouse** [comment]
But the Harmony fix approach is v valid and easy.

Have you done much Harmony, SniperRecon?

**Comment by Sn1p3rr3c0n** [comment]
@lilwhitemouse i would say its rather limited,
i used it only once so far and that only kinda worked. but i can give it a try.
