### ISSUE TITLE
Port over S.A.L like robots

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#126]
### S.A.L Stationary robots 

my last task i had for nobo was to port over his S.A.L like robot
(a robot pawn / placeable assembler placed on a workbench worker slot)

theres 3 options:
### - port over from nobos mod
its called AutoMachineTool Tier1, tier2, tier3 in there:
https://github.com/nullre/rw_mods/blob/master/NR_AutoMachineTool/Defs/ThingDefs/NR_AutoMachineTool/NR_AutoMachineTool.xml def here.
source file here:
https://github.com/nullre/rw_mods/blob/master/NR_AutoMachineTool/Source/Building_AutoMachineTool.cs

and we have permission to do so.

### -Update original spdskatr mod (what nobos are based off)
update original A17 mod from spdskatr, its before PRF was made, and changed into assembler machines we have now.
https://github.com/spdskatr/S.A.L.-Station-Automation-and-Logistics-

### Why should we have this?
some task cant be done on assemblers like mend and recycle and other mod taking in items and push out again, this could be a good solution for that, and create a extra way of automate stuff.

all in all a good tool in the arsenal, and fits good in PRF history as S.A.L was first version of prf =)

and not sure whats best way? but nobos are properly most up to date version

**Comment by zymex22** [comment]
Just some notes for my try on porting over Nobos version: (ill just update this post to not spam alot)

- Opened a branch for this issue

Theese files being ported over:
**Def** 
- NR_AutoMachineTool.xml -To-> Buildings_SAL_Like.xml

**Cs files**
- Building_AutoMachineTool.cs
- PlaceWorker_AutoMachineTool.cs

might need more still searching through it

**Comment by zymex22** [comment]
### Need to be solved list:

- [ ] In modextension it asks for a `<tier>1</tier>` 1,2,3 seems like its from hes modextension and or tuple.cs
- [ ] Nobo are using modsettings in hes mod so properly need to remove that and only use modextension/comp to set stats for them

**Comment by zymex22** [comment]
**Notes/idea for later wanted functions:**


- Speed
- Separate def skill set, instead of global skill level.
- FAST robot but bad qual. (overclocked auto-assembler from S.A.L) 
- Slower robots but better qual (skill levels)
- only placed/allowed for cetain benches?
- Research bot or not?

**Comment by zymex22** [comment]
it builds! thanks @lilwhitemouse 

will need to sort out some errors in log when open game before i can test, more info later.....
![image](https://user-images.githubusercontent.com/41029070/93532307-0fb60900-f941-11ea-8068-58d8699742cd.png)
https://gist.github.com/9fec89114972a5c8dabb06be35a8deaa

some of them are just xml not being corrected yet, but have to look into it when not tired see if theres C# problems too or not

latest work are on the branch https://github.com/zymex22/Project-RimFactory-Revived/tree/%23126-S.A.L-robots

**Comment by zymex22** [comment]
okay sorted out startup errors and can now start a game

so far i encounter this error when placing one on production table:
![image](https://user-images.githubusercontent.com/41029070/93644148-b366ee00-fa01-11ea-834e-6e40ae38b3a3.png)
https://gist.github.com/e5b897ba5205e941f895ae64eb1f0895

**Comment by zymex22** [comment]
okay got those issues resolved, it need to have speed comp on it too.
ill need to figure how to get that tier extension back it had before where it had tier 1, 2, 3.

but so far it works ingame now and can work, so time for testing and see whats next

**Comment by zymex22** [comment]
todo now:
- [ ] fix language files
- [ ] update xml
- [ ] Output cell isnt shown on placement (should it?)
- [ ] New texture should look like old S.A.L building but in new prf style
C# stuff
- [ ] figure a way to set skills? There is none?
- [ ] should skills be set ALL or separate skills? (original S.A.L was separate)
- [ ] code might need a cleanup in C# to match prf standard and fixes

this is how it was done in original S.A.L
```xml
    <modExtensions>
      <li Class="ProjectSAL.ModExtension_Assembler">
        <defaultSkillLevel>1</defaultSkillLevel>
        <powerUsageLowPower>35</powerUsageLowPower>
        <globalFactor>2</globalFactor>
        <skills>
          <li>
            <skillDef>Crafting</skillDef>
            <level>5</level>
          </li>
          <li>
            <skillDef>Cooking</skillDef>
            <level>4</level>
          </li>
          <li>
            <skillDef>Artistic</skillDef>
            <level>0</level>
          </li>
        </skills>
      </li>
    </modExtensions>
```

**Comment by zymex22** [comment]
@Sn1p3rr3c0n  might need your help in above todo to set skill levels somehow, if you have time at some point :slight_smile: i dont see any way in extensions or comps to do so =)

before it was set with a "mod setting" and <tier1><tier2><tier3>

so will properly need a new modextension/comp to set skills

**Comment by Sn1p3rr3c0n** [comment]
@zymex22 i already added a ModExtension for that purpose in #80

**Comment by zymex22** [comment]
oh cool can that one be used here too then? :D that would be great have some more universal ModExtension =)

**Comment by Sn1p3rr3c0n** [comment]
- [ ] Fix or remove `Forbid output Items` Gizmo
