### ISSUE TITLE
Assembler bug after latest update

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#127]
### Assembler bug
got theese comments on steam:

Slayer Arch 
> My assemblers have bugged out either not working or no stopping at set amounts

Kaz 
> Same issue as Slayer, since the update Adaptive Assemblers seem to just be sitting at "Searching for Ingredients" tried moving them, rebuilding them, dev mode placing them. They don't seem to be outputting any error logs, they just seem to be stuck.

**Malkav**
> The latest update has broken all machines which use a recipe that has no ingredients. For example, if I use a database to copy the recipe from the SNS Cosmic Drawer to make Cosmic Matter from nothing, it gets stuck on "Searching for Ingredients." But it worked yesterday, so I know it was a recent update.

Nexus 
> Humm, all but three of my assemblers are working. The three that are not working have recipes that require no input...
> 
> Kaz and Slayer, do your effected assemblers have a recipe that requires no input?

Slayer Arch 
> yes and no
> 
> I have a recipe for fuel rods that went over the 3k limit and now i have 100k of it(it requires input)
> 
> Like Kaz my recipes that have no input have not being working

I havent tested my self and going to a funeral now but i reverted 1 version back.

**Comment by Sn1p3rr3c0n** [comment]
Sample from https://steamcommunity.com/sharedfiles/filedetails/?id=1802857253 (Science Never Stops: Ambition of the Cosmic)  - **Malkav**

<?xml version="1.0" encoding="UTF-8"?>
<Defs>

	<RecipeDef Abstract="True" Name="SNS_DrawCosmicMatter">
		<jobString>Drawing Cosmic Matter</jobString>
		
		<workSkill></workSkill>
		<skillRequirements></skillRequirements>
		<workAmount>45000</workAmount>
		<soundWorking>Recipe_Machining</soundWorking>
		<ingredients></ingredients>
		<fixedIngredientFilter></fixedIngredientFilter>
		<unfinishedThingDef>UnfinishedComponent</unfinishedThingDef>
		<recipeUsers><li>Table_SNS_CosmicDrawer</li></recipeUsers>
	</RecipeDef>

	<RecipeDef ParentName="SNS_DrawCosmicMatter">
		<defName>SNS_Production_DrawCosmicMatter</defName>
		<label>Draw Cosmic Matter</label>
		<description>Combine a lot of time and energy into drawing pure, stable Cosmic Matter.</description>
		<products><SNS_CosmicMatter>100</SNS_CosmicMatter></products>
	</RecipeDef>

</Defs>

Well i did not anticipate that something like that could exist.
I Think we can make a special condition for the cases with no ingredients

----

The Production limit seems to be the second issue.

**Comment by Sn1p3rr3c0n** [comment]
Fix for no Ingredients is in
https://github.com/zymex22/Project-RimFactory-Revived/tree/Assembler_bug_after_latest_update_%23127

---
Still have issues reproducing the Limit issue as reported by **Slayer Arch**

**Comment by Sn1p3rr3c0n** [comment]
I cant reproduce the issue reported by **Slayer Arch**.
The only case where it ignores the Limit if if it cant place the Product. That would then be a separate issue that is not related to the update.

I'm assuming with fuel rods he is referring to Rimatomics therefor I tested with that mod.

We should clarify that point with him.

**Comment by zymex22** [comment]
that bug with not count towards limit might not be a prf problem or else it might be related to this one:
https://github.com/zymex22/Project-RimFactory-Revived/issues/118

either way ive had that problem even in vanilla benches so dont think we should put too much effort into that one yet.
