### ISSUE TITLE
Puller randomly broke, gives NullReferenceException error

### ISSUE THREAD

**Issue by DestinyPlayer** [zymex22/Project-RimFactory-Revived#135]
**Describe the bug**
One of my pullers suddenly broke in a way that prevents it from working, AND prevents me from removing it in any way. It gives me a System.NullReferenceException error - https://hastebin.com/eqogeciguw.css

**To Reproduce**
Reproducibility: ?
I'm not actually sure what specifically CAUSED this issue, as far as I can tell it just randomly stopped working, while every single other puller is still functional.

**Expected behavior**
The puller should pull items from one stockpile to another, and let me deconstruct it, whether with a pawn, or via god mode.

**Actual Behavior**
It doesn't do anything, pawns can't deconstruct or move it, and even god mode fails to delete it.

**Screenshots**
https://cdn.discordapp.com/attachments/453922793621553155/737027547568537710/unknown.png - I hope this works

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.1
 - PRF Version: 2.3.3
 - HarmonyLIb Version: 2.0.1? (version that was released on the 10th of May)
 - Type: Bug
 - Severity: Medium
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: Not sure how to reproduce the problem in the first place, so I cannot check
 - Your modlist (if needed): https://hastebin.com/boturoqova.sql
 - Do you know what mod conflicts?: No idea, as the debug log doesn't seem to point to anything but Rimfactory itself

**Additional context**

**Comment by zymex22** [comment]
@DestinyPlayer thank you for a good report, not often we get them, we will look into it.

**Comment by DestinyPlayer** [comment]
If necessary, I can also send over my current save, along with a RimPy pack to make it easier to see the specific problem.

**Comment by zymex22** [comment]
it should been fixed now

**Comment by DestinyPlayer** [comment]
Seems to have been fixed so far. I can move the puller, deconstruct it, and it seems to respond to commands now. Thank you for such a rapid response!

**Comment by zymex22** [comment]
solved in latest update
