### ISSUE TITLE
Backstory problems when minified

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#137]
### Describe the bug
Assemblers throw alot of errors in debug log if assembler type buildings are minified and save and reload a game, problem is solved when they are placed, but kinda drastic when minified, this is specially noticeable on factory scenario where ppl start with a few assemblers

**To Reproduce**
Reproducibility: always
1. open prf scenario
2. dont place any machines
3. save
4. reload and spam errors

**Expected behavior**
Should be able to minify without error logs either they should be muted or removed?

**Actual Behavior**
Spam error log

**Screenshots**
![image](https://user-images.githubusercontent.com/41029070/88530703-12137b00-d002-11ea-9285-f60492991121.png)

**Rimworld (please complete the following information):**
 - Link to gist bug report:  https://gist.github.com/8076a04188ec3241e75c52790895c55a
 - Type: bug
 - Severity: minor
 - Regression: 
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: yes
 - Your modlist (if needed): none
 - Do you know what mod conflicts?: none

**Additional context**

**Comment by Sn1p3rr3c0n** [comment]
Issue only occurs if the buildings have never been placed before.

I don't see the issue when i place them and then uninstall them again

**Comment by zymex22** [comment]
oh didnt test that one, i just noticed problem from another test where i could not figure where all those error came from

**Comment by Sn1p3rr3c0n** [comment]
The issue seems to be that the `DoPwawn` function dos not run for a Minified Thing. therefor the required fields are not generated.
Image shows comparison in the save file. (Left: Without placing | Right: has been placed)
![image](https://user-images.githubusercontent.com/68663281/88536417-104eb500-d00c-11ea-9461-6425fe5e0127.png)

**Comment by lilwhitemouse** [comment]
have you figured out a way to make that work?
