### ISSUE TITLE
Mechanites Cultivator will not "produce" secondary plant products

### ISSUE THREAD

**Issue by Sn1p3rr3c0n** [zymex22/Project-RimFactory-Revived#143]
**Describe the bug**
When using a mod like for example [Kijin Race 2.0](https://steamcommunity.com/sharedfiles/filedetails/?id=1918120749) that adds a secondary drop to plants.
The Mechanites Cultivator will not generate that spawn.

The issue dos not exist with the drone cultivator

The issues likely resides in the ` public virtual void CreatePlantProducts(Plant p)` function or is caused since that function is used instead of using the base game harvest functions.

**Comment by Sn1p3rr3c0n** [comment]
The Rimwold function that produces Plant products resides in `JobDriver_PlantWork` more specifically `protected override IEnumerable<Toil> MakeNewToils`.
This function dose not support the generation of multiple types or products. therefore i believe that all Mods adding a secondary product use a Harmony patch.

I doubt that we can call the mentioned function without using a pawn for it. 
therefore i think the only way to "fix" this point is to manually patch all individual incompatibility's.

**Comment by zymex22** [comment]
well isnt it mostly for fertile fields we have been asked for it. might be worth just do that then and see if anyone ask for more.

**Comment by lilwhitemouse** [comment]
It might be possible to keep a `static Pawn` that could be the actor for all these things? But manually patching might be safer and easier >_<

**Comment by zymex22** [comment]
problem might also be fixed if we are making a Vacuum puller, that way they have a new way of collecting secondary stuff
so could be fixed with implementation of #159.
so do less patches for each mod needed, then just give them a new way to collect stuff instead.

**Comment by Sn1p3rr3c0n** [comment]
@zymex22 The issue is with the production not the collection.

**Comment by zymex22** [comment]
oh i thought it was related to machine was not able to pick it up and output it to a cell :D
then nvm heh :P

but again.... i only hear support for "Fertile Fields" please....

oh... or is it for stuff like trees and such? wich have a pick fruit but leave tree be ? :P i think i just confused myself here... =)

**Comment by zymex22** [comment]
Closed, i think its not worth doing too much here, as our drone high tiers ones can do the job now more or less same way as a mechanicte cultivator, we can consider reopen later if it getting too much of a problem in general
