### ISSUE TITLE
DS Incompatibility with belts and pullers

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#145]
**Describe the bug**
pullers and belts are unable to push to Deep Storage, it can only put in 1 item but not stack them inside og DS items.

**To Reproduce**
Reproducibility: always
1. Place a DS item
2. place a puller or belt pointing at Storage unit and try to pull to storage, it will only put in one item.
3. ...

**Expected behavior**
It should be able to stack items in DS like it can in prf storage crates and dsu

**Actual Behavior**
It does not stack

**Screenshots**

**Rimworld (please complete the following information):**
 - Link to gist bug report: 
 - Type: bug / incompability
 - Severity: minor
 - Regression:  DS problem again... :P
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed:
 - Your modlist (if needed): 
 - Do you know what mod conflicts?:

**Additional context**
Re upload of old problem because i closed that combined issue with info in it

**Comment by lilwhitemouse** [comment]
Fixed in belts branch
