### ISSUE TITLE
Refuel mortar and other canon buildings

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#146]
**Is your feature request related to a problem? Please describe.**
Refuel arms/stations can not refuel vanilla mortar and other buildings using that shell ITab.

**Describe the solution you'd like**
Either make a new thingclass + thingdef that can fuel cannons, or update refueling arm to let that one be capable of both type of refuel

**Describe alternatives you've considered**
DRONES?!

**Additional context**
i said it couldnt be done... thorny said F^** drones... lwm said it can totally be done...

**Comment by Sn1p3rr3c0n** [comment]
Added Code to support this: [commit](https://github.com/zymex22/Project-RimFactory-Revived/commit/d9f81e2e7d689a92126182c3aa014d56f532a68b)

_This patch will not work for SOS2 Torpedo Tubes._
This is caused by `SOS2` adding their own Component for the torpedo.

@lilwhitemouse Do you know if and how to add code that only executes if `SOS2` is installed. in case of Harmony we would need to patch our own code.

- [ ] Check if `SOS2` Support is possible

**Comment by lilwhitemouse** [comment]
Yes. See, for example, https://github.com/lilwhitemouse/RimWorld-LWM.DeepStorage/blob/master/DeepStorage/ModSettings.cs line 238. It may be quickest to have a static flag that we set once on startup - [StaticConstructorOnStartup] is a handy way to check that after things are loaded.

Their comp isn't derived from CompChangeableProjectile?

**Comment by Sn1p3rr3c0n** [comment]
sadly not, They even put it into the `RimWorld` namespace.

i will definitively try to use `ModLister.GetActiveModWithIdentifier("");`

**Comment by Sn1p3rr3c0n** [comment]
SoS2 is now Supported. 
This means however that we need to have the `ShipsHaveInsides.dll` for the Compile.

**Comment by zymex22** [comment]
how is that done? do we just include it in source files? or do we just need to have SoS2 installed?

**Comment by Sn1p3rr3c0n** [comment]
@zymex22  This means that for the Compile in `Visual Studio` (or any other compiler) you will need to add `ShipsHaveInsides.dll` (the binary of SoS2) under Dependencies.
Visual Studio will copy that file into our assembly folder --> **We shall remove it there**

For the User it dos not matter if SoS2 is installed or not.

**Comment by lilwhitemouse** [comment]
I do know ways we can do this without directly including the .DLL! I will see what I can do when I get my laptop back out, but short answer: #DeepMagic #ReflectionIsOnlyTheStart
