### ISSUE TITLE
Spacer cooker unable to make a majority of foods

### ISSUE THREAD

**Issue by Lucewithnootherideas** [zymex22/Project-RimFactory-Revived#148]
**Describe the bug**
as the title says the spacer cooker does not give the option to make a majority of foods including survival meals 
**To Reproduce**
try and make things with the spacer cooker

**Expected behavior**
I was expecting my every cooking need to be taken care of

**Actual Behavior**
now I Either have to go back or live with my current issue

**Screenshots**
![image](https://user-images.githubusercontent.com/51459975/89701352-8db6d700-d8e2-11ea-9e08-72481ed6f294.png)

 - RimWorld Version: 1.1

**Additional context**

**Comment by Sn1p3rr3c0n** [comment]
@Lucewithnootherideas This sounds like you are missing the required Research for the recipe.
If you have the research and its still unalienable there might be a Mod Conflict.
In that case please provide your full Mod list, where you can reproduce the issue.
![SpaceCooker](https://user-images.githubusercontent.com/68663281/89705676-8255c100-d95f-11ea-9702-ca768384f279.jpg)

**Comment by zymex22** [comment]
it copies whatever you can make on your vanilla stove can also be done on your spacer cooker, so check if it can be done on your vanilla stove. 

you can use dubs mint menu if you want a nice visual of bills also btw.

**Comment by Lucewithnootherideas** [comment]
it was fixed when i loaded up today
