### ISSUE TITLE
drone backstory bug

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#151]
Comment on steam:

from Joko

> i get this error
> 
> ```
> Backstory Drone has same unique save key PRFNoneBracketsC as old backstory Drone
> Verse.Log:Error(String, Boolean)
> RimWorld.BackstoryDatabase:AddBackstory(Backstory)
> ProjectRimFactory.Drones.<>c:<.cctor>b__2_0()
> Verse.LongEventHandler:Verse.LongEventHandler.ExecuteToExecuteWhenFinished_Patch2()
> Verse.LongEventHandler:UpdateCurrentAsynchronousEvent()
> Verse.LongEventHandler:LongEventsUpdate(Boolean&)
> Verse.Root:Verse.Root.Update_Patch1(Root)
> Verse.Root_Entry:Update()
> ```

> here is a report link to see if it helps with bug fixes
> https://gist.github.com/6b3bb9f52d0ea36df14a2eb3f66843ac

**Comment by Sn1p3rr3c0n** [comment]
@zymex22 the log link dos not contain the mentioned error. it dos however contain lots of XML Errors.
I will perform some basic tests on 1.2 but its likely that we will require a description when this Issue is observed

**Comment by zymex22** [comment]
i dont know but its a known problem i have several reports on it, also had experianced it my self a couple of times, i just cant seem to figure what cause it, seems like its a mod conflict but couldnt figure what mod does it.

ill see if i can find more reports on same and post them here.

**Comment by zymex22** [comment]
i think its something to / with drones mod also but not sure.
also seen something about job, so think thats the problem somehow.

Comrade Cyka

> Backstory Drone has same unique save key PRFNoneBracketsC as old backstory Drone
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> Backstory Drone has same unique save key PRFNoneBracketsA as old backstory Drone
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
> Not using the drone mod so I'm not sure what is happening here.

cant find rest might have been on discord then, but had same problem in some of my test runs when drones are out and load/save. even without and very old save / many mods

**Comment by Sn1p3rr3c0n** [comment]
This appears to be an incompatibility with `BetterLoading`.
Can be reproduced by simply starting the game with said mod loaded.

**Comment by Sn1p3rr3c0n** [comment]
`BetterLoading` appears to be calling `LongEventHandler.ExecuteWhenFinished` in https://github.com/zymex22/Project-RimFactory-Revived/blob/f3b1aac4c2d15f55edc5c748c5c2b90cf2bf14e6/Source/ProjectRimFactory/Drones/DroneBackstories.cs twice instead of once. this causes the error since the same key and Value pair already exists in `BackstoryDatabase` (from the initial call)
