### ISSUE TITLE
load / save bug with drones

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#152]
**Describe the bug**
When trying to load or save with active drones out it will throug a error for "each" ? drones thats out.
this might be caused by a mod imcompat not sure i attached modlist

**To Reproduce**
Reproducibility: should be always with showed modlist?
1. start a map, build some drone stations
2. get drones out and working
3.  pause game and save. it will throw a error for each drone
4. reload and it thorw another error

**Expected behavior**
No spam?

**Actual Behavior**
Much spam

**Screenshots**
### When saved:
![image](https://user-images.githubusercontent.com/41029070/90789592-5e9f5d00-e307-11ea-991f-326e2da48c9f.png)
https://gist.github.com/79b3fd442a4e11169be0b609b19a769f

### When loaded
![image](https://user-images.githubusercontent.com/41029070/90789640-6c54e280-e307-11ea-89cb-bbaeb294d6fc.png)
https://gist.github.com/035d944741d413df24b662fb1d88d09f

![image](https://user-images.githubusercontent.com/41029070/90789669-7545b400-e307-11ea-99bf-ecb680b92737.png)

![image](https://user-images.githubusercontent.com/41029070/90789684-7971d180-e307-11ea-9028-e5b79f86e67b.png)

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.1 / 1.2
 - PRF Version: all
 - Link to gist bug report: 
 - Type:
 - Severity:
 - Regression: 
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed:
 - Your modlist (if needed): 
 - Do you know what mod conflicts?:

**Additional context**

**Comment by Sn1p3rr3c0n** [comment]
@zymex22 `Work Tab` is the Mod triggering this issue

**Comment by zymex22** [comment]
make sense =) is it a prf problem or a work tab problem?

**Comment by Sn1p3rr3c0n** [comment]
i think its a `Work Tab` Issue.
see: https://github.com/fluffy-mods/WorkTab/issues/134

**Comment by zymex22** [comment]
so can we patch/fix it for us or something we should leave..
not sure if it causing any problems but its quiet annoying see when looking for other problems :P

if we should not or can not fix it we can close this i guess =)

**Comment by Sn1p3rr3c0n** [comment]
the issue seems to be that `Work Tab` Saves Drone Pawn by reference that do no longer exist.

in my test scenario i use one Drone station with 30 drones active.
`Work Tab` saves 69 Drone Pawns. consequently 39 unique warnings and 39 null ref errors are logged.

I will check if we are doing something wrong with the despawning but otherwise i think its a `Work Tab` bug

**Comment by Sn1p3rr3c0n** [comment]
`Work Tab` dose not save Pawns if they have the `Destroyed `flag set.
Therefor by simply setting this bool to `true` the issue can be resolved.
