### ISSUE TITLE
Cache any calls to ModExtension_Settings's GetByName()

### ISSUE THREAD

**Issue by lilwhitemouse** [zymex22/Project-RimFactory-Revived#154]
GetByName() is slow (Reflection)

For any graphics-related uses, it is important to cache the initial call once.

Smart hoppers need cleanup here.

**Comment by zymex22** [comment]
this? after belts, so still in 2.5.0 @lilwhitemouse if we move deadline a bit further to test with new mech mod, and also gives us time to go over balance, descriptions and more so might be ok? =)

it put 2.5.0 on milestone we can remove after if not =)

**Comment by lilwhitemouse** [comment]
This will help performance (probably after belts are done ;) )

**Comment by Sn1p3rr3c0n** [comment]
Searching for `GetByName` currently yields two use cases.

One is in `Building_SmartHopper` and the other one in `Building_ItemPuller`.

**Building_SmartHopper**
Used to get the `pickupFromGround` setting from the `ModExtension_Settings`
Is not related to Graphics
Looking a bit into it reveals that the only use case of `ModExtension_Settings` is that `pickupFromGround` which is always true _(We have only one Building_SmartHopper)_
This raises the question on why does this `ModExtension_Settings` even exist?
@zymex22 Unless there is a specific reason for it's exitance I would remove it entirely.

**Building_ItemPuller**
Here it is used to get the Correct Graphic for the display of the Pullers _(Specifically the Angled Puller)_ using `ModExtension_Graphic`.
Internally this uses LINQ to select a specific Graphic (so no reflection here)
Adding a Cache here might improve the Performance, however this remains to be tested.
