### ISSUE TITLE
Powered off T0 Smelters give no indication powered off

### ISSUE THREAD

**Issue by lilwhitemouse** [zymex22/Project-RimFactory-Revived#157]
There is neither the vanilla powered-off indicator nor any text indication.

We should either give the vanilla fading in and out switched-off icon, or at least text stating "powered off" or something.

**Comment by lilwhitemouse** [comment]
Also glows red even though not burning anything.

**Comment by zymex22** [comment]
ill check it when i doing some work on drones today =)
is it a xml problem or a c# problem?

**Comment by lilwhitemouse** [comment]
Correction: it IS burning things.  While the switch is flicked off.  That's probably C#.

**Comment by lilwhitemouse** [comment]
Building_ProgrammableAssembler needs logic for flick - same as for fuel and power. Simple fix.
