### ISSUE TITLE
SeedsPlease incompatibility

### ISSUE THREAD

**Issue by Sn1p3rr3c0n** [zymex22/Project-RimFactory-Revived#174]
# Describe the bug
The cultivators are incompatible with the `SeedsPlease` Mod.
They ignore the System where seeds are required in order to plant.

Link to the Mod: https://steamcommunity.com/sharedfiles/filedetails/?id=935732834

Patches if possible are required for:
- [ ] Drone Cultivator
This might be already resolved with the Drone Overhaul #80 (Check Required)
- [x] Mechanites Cultivator

---
Reported on steam by `Extrien`

**Comment by Sn1p3rr3c0n** [comment]
The issue dos not exist for the Mechanites Cultivator.
The Issue for the Drone Station is solved in #80

**Comment by zymex22** [comment]
fixed in #80 thats just merged
