### ISSUE TITLE
Drone Cultivator loses drones on uninstall and reinstall

### ISSUE THREAD

**Issue by Sn1p3rr3c0n** [zymex22/Project-RimFactory-Revived#175]
# Describe the bug
Drones of the Drone Cultivator are lost on reinstall

**To Reproduce**
1. Place the Drone Cultivator
2. Uninstall it while drones are working / Active outside
3. _Drones will disappear_ (i think that's fine) 
4. Install the Drone Cultivator

Now the drone Cultivator has 0 Drones available

---
Reported on steam by `Extrien`

**Comment by Sn1p3rr3c0n** [comment]
To avoid Merge Conflicts i think it will be beneficial to fix this on #80 or after that has been merged to master.

**Comment by zymex22** [comment]
yea just fix this on #80 and lets split up later if we do a partial release =)
