### ISSUE TITLE
Latest version is outdated? (Bug report)

### ISSUE THREAD

**Issue by Lucas559-noob** [zymex22/Project-RimFactory-Revived#177]
# Describe the bug
On rimworld with the mod manager(mod) it say it have a new version and when I click to go to github and download, it still say that is outdated, current version 2.3.91 latest 2.4.5

**Expected behavior**

**Actual Behavior**
Show that it is outdated.

**Screenshots**
![Captura de Tela (19)](https://user-images.githubusercontent.com/54007604/93550515-ee095180-f941-11ea-8906-e1f4c4dc2e85.png)

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.2.2744 (64-bit)
 - PRF Version: 2.3.91
 - Link to gist bug report: 
 - Type:
 - Severity:
 
**Additional context**

**Comment by zymex22** [comment]
made a release now on github also, i usually just use master.
but a release have been made, and also up on steam =)

closing this
