### ISSUE TITLE
repair, attack, transport, miner drones(Request)

### ISSUE THREAD

**Issue by Lucas559-noob** [zymex22/Project-RimFactory-Revived#180]
**Describe the solution you'd like**
They will act like a human or an animal, they will repair, attack(with a gun or dropping bombs), transport like humans or animals, mine like humans

**Comment by zymex22** [comment]
@Lucas559-noob thats kinda already done in Project RimFactory - drones (addon mod)
except attack drones.

also we are working on a drone update atm. wich will bring some new ones, im not sure about a attack one, but rest should be covered =)

**Comment by zymex22** [comment]
ill close this, as its answered with above comment.
