### ISSUE TITLE
Can't build underground and wall conveyor belt because wire connection (Bug report)

### ISSUE THREAD

**Issue by Lucas559-noob** [zymex22/Project-RimFactory-Revived#181]
# Describe the bug
While trying to put a conveyor belt(underground and wall) on wires make it say that place is occupied

**To Reproduce**
Reproducibility: yes
1. build a wire on floor and wall
2. try to build a wall conveyor belt or underground conveyor belt on the wire
3. space occupied

**Expected behavior**
Be able to put on wires

**Actual Behavior**
Wire count as object and can't be placed belts

**Screenshots**
![Captura de Tela (23)](https://user-images.githubusercontent.com/54007604/93725238-d6211000-fb83-11ea-9e18-e393a64ec901.png)

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.2.2744
 - PRF Version: 2.4.5
 - Link to gist bug report: 
 - Type:
 - Severity:

**Comment by zymex22** [comment]
this is known and not really a bug more a mechanic =) its because we use transmit power, and wall and ug version will not replace/destroy on placement.

so they will say occupied if trying to place somewhere they cant.

**Comment by lilwhitemouse** [comment]
It's a bug.

The problem is that we want conveyors to carry their own power, so you can just build them across the map, without having to ALSO build power across the map.  But RW really doesn't like two power transmitters in the same cell, so we can't leave the power around?

We'll see if we can find a way around it.

**Comment by Lucas559-noob** [comment]
The only way is delete the current wire on floor then build the conveyor, but is strange, it don't apply to normal conveyor, only underground and wall conveyor are affected
And in log sometimes i find, bla bla (x,y) bla the same spot, wire and wire

**Comment by lilwhitemouse** [comment]
Any ideas, zymex?

**Comment by Lucas559-noob** [comment]
Is not possible to make a block to electrify all conveyors connected to this block or make them connect like other thing with a distance like lights, or add a substation to give a big area of the auto connect

**Comment by zymex22** [comment]
hmmmm

something like this maybe?
https://steamcommunity.com/sharedfiles/filedetails/?id=1277677885
(Parallel Power Grid (Parallel Conduits)) mod

else only solution is make them not transmit power but we had that before, and then you complained about them being different @lilwhitemouse 

else we need to somehow modify or build our own `<clearBuildingArea>false</clearBuildingArea>`

so if this is used it WILL clear cables but nothing else.
that's your department, to tell if that's a possibility @lilwhitemouse

**Comment by lilwhitemouse** [comment]
Addition of `CompTransmitsPower` now allows placing conveyors anywhere; fixed for new belts
