### ISSUE TITLE
button to change zone shape(Request)

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#186]
**Is your feature request related to a problem? Please describe.**
can we make a button on buildings using our Range comp to swap between range shape types?
so
<rangeType>ProjectRimFactory.Common.RectRange</rangeType>
a button switching between those 3 options:
`RectRange, FacingRectRange, CircleRange`

it would apply to all buildings using: 
`<li Class="ProjectRimFactory.Common.CompProperties_PowerWorkSetting">`

This might be a handy feature and since we already have option to switch between shapes in xml, it might be nice to have for individual player/machine to swap to a circle or beside the building =)

not sure if it should apply to all buildings using above comp or if we should make a
`<showrangebutton>true<showrangebutton>` in xml to be able to disable it?

**Comment by zymex22** [comment]
we can properly just add it to power slider comp if that one is used.
```xml
      <li Class="ProjectRimFactory.Common.CompProperties_PowerWorkSetting">
        <speedSetting>false</speedSetting>
        <!-- range settings -->
        <rangeSetting>true</rangeSetting>
        <minPowerForRange>0</minPowerForRange>
        <minRange>1</minRange>
        <maxPowerForRange>1500</maxPowerForRange>
        <maxRange>5</maxRange>
        <rangeType>ProjectRimFactory.Common.RectRange</rangeType>
      </li>
```
it would be a button/list which change rangetype if range option is used.

**Comment by lilwhitemouse** [comment]
We can add this to the Settings ITab

**Comment by Sn1p3rr3c0n** [comment]
Added test to check if the button should be displayed.
https://github.com/zymex22/Project-RimFactory-Revived/commit/c954721a5e65326eefb8889088530190ece4f60a#diff-eede0cedefb6d116cfc35fa655bacf733a310cc0f664a300eacb66790bae7d6fR197

_only issue is that i currently can find a way to update the value (see line 202)_

**Comment by zymex22** [comment]
LWM gave me a idea for a new input shape...
Single Cell input, that might become usefull also when Oskars comming out those only have one input/output on each side..

**Comment by Sn1p3rr3c0n** [comment]
Basic Function added with: https://github.com/zymex22/Project-RimFactory-Revived/commit/93872b9f7700a720a1c998a354430bd785f09951

**Known Issues / Issues that need to be fixed:**
- [ ] ITab Size Button
- [ ] ITab Size Slaughterhouse
- [ ] ITab Button Language Files
- [ ] Other ITab Enhancements
- [ ] Error on Load (Resetting the saved zone Type)
