### ISSUE TITLE
Add to tile with already a item (Bug report)

### ISSUE THREAD

**Issue by Lucas559-noob** [zymex22/Project-RimFactory-Revived#187]
# Describe the bug
On auto kitchen(idk the name), the output was on a tile with another item, and with produce to have X in inventory was stuck, it can't put on the inventory because the item on output tile, so it was infinite crafting, and when i changed the output tile, the stuck food came out
**To Reproduce**
Reproducibility: yes
1. some crafter with output on an different item
2. craft to have x in inventory
3. and it will infinite craft

**Expected behavior**
it will spawn at side of the item, like on dev mode when you spawn like 75 food and when a tile is full, it spawn at side of the tile

**Actual Behavior**
It try to put on the tile

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.2.2744
 - PRF Version: 2.4.5
 - Link to gist bug report: 
 - Type:
 - Severity:

**Comment by lilwhitemouse** [comment]
Expected Behavior:
It stops producing when it has enough pending placement to bring the total over cutoff.
That is, it counts its [pending] as part of inventory.

Alternatively, we could add a switch to machines?

**Comment by zymex22** [comment]
is this related to #168

**Comment by zymex22** [comment]
this is also part of #168 so i close this and refrence in it stays =)
