### ISSUE TITLE
Underground entrance and exit (Bug report)

### ISSUE THREAD

**Issue by Lucas559-noob** [zymex22/Project-RimFactory-Revived#190]
# Describe the bug
Items can enter and exit with the conveyor being in wrong direction

**To Reproduce**
Reproducibility: yes
1. build underground conveyors
2. build an underground exit towards the underground conveyor
3. items do a 180º turn

**Expected behavior**
Items can't go back, only to front

**Actual Behavior**
Items can go on a 360º

https://youtu.be/ud6ADTny2wM

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.2.2744
 - PRF Version:2.4.5
 - Link to gist bug report: 
 - Type:
 - Severity:

**Comment by lilwhitemouse** [comment]
Major belt update coming soon! If I can figure out graphics.

**Comment by lilwhitemouse** [comment]
This is fixed in the new belts branch
