### ISSUE TITLE
Funky stuff regards new belts (Bug report)

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#192]
@lilwhitemouse i did a test heres some problems i found:

- [x] Pullers do NOT fill a connected stockpile zone it just fill cell in front of it and then gets blocked

- [x] belts over the edge into a stockpill does not fill stockpile anymore it just take that one cell in front of it

- [x]  Blueprint when placing belts doesn't connect like before?

- [x] items in underground belts getting lost?
when i put stuff in a entrance and to a ug belt they go in entrance and disappear, and don't come back at exit?

- [x] is items even visible on ug belts still when they are clicked?

- [x] same goes for wall version they go in and gets lost, also not visable if they even are on wall belts or not?

- [x] splitter tab need to be prettyfied right? :P

- [x] Vacuum hopper still needs to be able to pull from belts also

- Fill DS seems to work.
- assemblers pull from belts seem to work
- splitter seem to work?
- Connection of belts feels odd might be because of it had splitter build in before..
- Old save tranfered to new....what will happens to old splitters?

**Comment by zymex22** [comment]
- [ ] make items on UG belt smaller so it looks like its further down in the ground (for 2,5 tunnel texture)

**Comment by Steague** [comment]
[ ] Items transitioning from regular to wall belts have layer order issues
![unknown 1](https://user-images.githubusercontent.com/909053/96542947-8f6a2700-12a3-11eb-9485-8dc7a4301fbb.png)

**Comment by zymex22** [comment]
new list of things, i'll update when i find more:
tested above list from me, those not checked are not fixed yet.

- [ ] **Arrows** on vertical belts need to be offset a bit up to fit 2.5D belt
- [ ] If a single verical belt are placed it will look strange with **Arrow** placement
- [ ] we need to put in **UI icons** (zymex)
- [ ] When belts are deconstructed they leave a cable, intention or bug?
- [ ] can we add a toggle button to puller setting tab with Pull item or stack, originally nobos version was single items but i made him change it to stacks, but in some cases single items are better.
- [ ] angle pullers arrow not pointing towards output.


**Wall belts**
- [ ] can only be placed 1 at the time not dragged like normal ones?
- [ ] if wall are destroy belt will remain in air (its same as other wall items)
- [ ] wall belts can be stacked because it will not destroy or prevent earlier placed.
- [ ] items on belt should be scaled down in size to fit smaller belts

**Comment by lilwhitemouse** [comment]
1st one: sh--.  That may be complicated to fix.
2nd one: what's the problem?

**Comment by zymex22** [comment]
![image](https://user-images.githubusercontent.com/41029070/96976450-26411880-151c-11eb-836a-67761fc7316b.png)
arrows are too close to the edge 2nd

**Comment by zymex22** [comment]
- [ ] on above picture belts are overlapping like "4 pixels" thorny said, so legs looking squeezed together.

**Comment by lilwhitemouse** [comment]
Okay, yeah, different bugs for each of these is probably a better way to handle this, because there are going to be a lot of comments in here and ...there's no message threading, so ....good luck?

" angle pullers arrow not pointing towards output." -  GIve me an angled arrow.

**Comment by zymex22** [comment]
AerosAtar:
> Very edge-case, since it requires at least one other mod (or GodMode) to be possible, but when the push/pull indicator for the pullers goes off the edge of the map when looking to place (before the blueprint is down), you get this error every time:

```
Exception in UIRootUpdate: System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at (wrapper managed-to-managed) System.Object.ElementAddr_8(object,int,int,int)
  at RimWorld.HaulDestinationManager.SlotGroupAt (Verse.IntVec3 loc) [0x00000] in <d72310b4d8f64d25aee502792b58549f>:0 
  at ProjectRimFactory.AutoMachineTool.Ops.SlotGroupCells (Verse.IntVec3 c, Verse.Map map) [0x00001] in <434c6eecdb424d6e82aa6b324b9dce7c>:0 
  at ProjectRimFactory.AutoMachineTool.OutputCellResolver+<>c__DisplayClass6_0.<OutputZoneCells>b__0 (Verse.IntVec3 c) [0x00000] in <434c6eecdb424d6e82aa6b324b9dce7c>:0 
  at ProjectRimFactory.AutoMachineTool.Option`1[T].Select[TO] (System.Func`2[T,TResult] func) [0x00010] in <434c6eecdb424d6e82aa6b324b9dce7c>:0 
  at ProjectRimFactory.AutoMachineTool.OutputCellResolver.OutputZoneCells (Verse.ThingDef def, Verse.IntVec3 center, Verse.IntVec2 size, Verse.Map map, Verse.Rot4 rot) [0x00020] in <434c6eecdb424d6e82aa6b324b9dce7c>:0 
  at ProjectRimFactory.AutoMachineTool.PlaceWorker_OutputCellsHilight.DrawGhost (Verse.ThingDef def, Verse.IntVec3 center, Verse.Rot4 rot, UnityEngine.Color ghostCol, Verse.Thing thing) [0x0009c] in <434c6eecdb424d6e82aa6b324b9dce7c>:0 
  at Verse.GhostDrawer.DrawGhostThing_NewTmp (Verse.IntVec3 center, Verse.Rot4 rot, Verse.ThingDef thingDef, Verse.Graphic baseGraphic, UnityEngine.Color ghostCol, Verse.AltitudeLayer drawAltitude, Verse.Thing thing, System.Boolean drawPlaceWorkers) [0x00082] in <d72310b4d8f64d25aee502792b58549f>:0 
  at RimWorld.Designator_Place.DrawGhost (UnityEngine.Color ghostCol) [0x0003c] in <d72310b4d8f64d25aee502792b58549f>:0 
  at RimWorld.Designator_Place.SelectedUpdate () [0x00065] in <d72310b4d8f64d25aee502792b58549f>:0 
  at (wrapper dynamic-method) RimWorld.Designator_Build.RimWorld.Designator_Build.SelectedUpdate_Patch2(RimWorld.Designator_Build)
  at Verse.DesignatorManager.DesignatorManagerUpdate () [0x00013] in <d72310b4d8f64d25aee502792b58549f>:0 
  at (wrapper dynamic-method) RimWorld.MapInterface.RimWorld.MapInterface.MapInterfaceUpdate_Patch2(RimWorld.MapInterface)
  at RimWorld.UIRoot_Play.UIRootUpdate () [0x00015] in <d72310b4d8f64d25aee502792b58549f>:0 
Verse.Log:Error(String, Boolean)
RimWorld.UIRoot_Play:UIRootUpdate()
Verse.Root:Verse.Root.Update_Patch1(Root)
Verse.Root_Play:Update()
```

**Comment by zymex22** [comment]
- [ ] a button in Itab for pullers that change if it move 1 item or 1 stack at the time

i think i asked for it before, but can see its still not on so just wrting it here to remember =)

**Comment by zymex22** [comment]
![image](https://user-images.githubusercontent.com/41029070/98298555-7dcc9300-1fb6-11eb-95f7-ee5406502405.png)
AerosAtar:
> Suggestion for underground belts - when the overlay is showing, such as in this screenshot, render them above walls and stuff. For example, you can't tell here but I have belts under all of those walls and it would be nice to be able to see that so I don't forget what is going where...

**Comment by zymex22** [comment]
we are setting speed with this mod extension:
```xml
    <modExtensions>
      <li Class="ProjectRimFactory.AutoMachineTool.ModExtension_WorkSpeed">
        <speedFactor>3.5</speedFactor>
        <minPower>5</minPower>
        <maxPower>5</maxPower>
      </li>
    </modExtensions>
```
so i should be able to use `<li>ProjectRimFactory.Common.ITab_PowerSupply</li>`
but if im adding that and change min/max power it dont show where its at now and speed goes super fast.
no sure why though.

speed setting seem to work otherwise?
no drag bar and cant write anthing in text field... and yes have tried changes values to be different heh 👍 
![image](https://user-images.githubusercontent.com/41029070/98300748-0436a400-1fba-11eb-8323-d75e7306bc1d.png)

**Comment by zymex22** [comment]
- [ ] make arrows above cables on UG belts
- [ ] make ug belts visable under walls when highlighed.
- [ ] fix transition for wall belst apperently broken?
- [ ] power slider seem to stack power in some cases instead of updating total power correctly
(temporary fix would go back to fixed min/max 5 power)
- [ ] WHHHHHHYYY are it 4 pixels overlap?
- [ ] Where is arrows on Splitter ? there is only input not output anymore.

**Comment by zymex22** [comment]
@lilwhitemouse  here is your debug report with graphic conveyor on:
https://gist.github.com/7b2d723cfa072f27441f6c9ffb417443
same setup/save as yesterday, let me know if you need more info from it

**Comment by zymex22** [comment]
oka to make this a bit more clear whats left i check all above and write them here:
@lilwhitemouse here we go let me know if i should specify anything further =)

- [ ] End belts need a button in Itab to "dont output" this will make them act like a "holding belt" usefull for connecting up machines
**(HIGH PRIORITY)**

- [ ] Blueprint when placing belts doesn't connect like before?
(when you placing blueprints they dont connect/link like atlas normal does, either we should change to a single texture or make atlas work)

- [ ]  Belt splitter need to be prettified as its not very uuserfriendly layout right now.
i've asked AvatarFighter to do it

- [ ] A button in Itab for pullers/Belts to switch between output 1 item or 1 stack at the time... this increse control for micromanagement. it was originally items and not stack in first version from nobo but i got him changing it to stack at the time instead.... 
a toggle would be super usefull.

- [ ]  wall belts can be stacked because it will not destroy or prevent earlier placed.
(cant remember if fixed ill check again in a minute)

- [ ]  ug placement of cable is on top of items and looking out of place unless using hidden cable mods.
was implemented right? Zymex need to do some patches eq. for docworld.

- [ ] S.A.L thingclass need to be able to pull from belts too like rest of the buildings can.
(added after your initial work, so they dont support it yet)

- [ ] Arrows on ug belts are almost invisable because they are rendered below cables, should probably move up to a highler layer?

- [ ] Belts are not visable when selected if they are under a wall? probably a render layer problem again?
should probably move to layer gas/projectile when selected..

- [x] power slider.... nah we save this one for later!

- [ ] arrows still gone on my belt splitters why does it only have input arrow but no output arrows anymore?
can we bring them back they were here earlier in belt release.... =)
![image](https://user-images.githubusercontent.com/41029070/101986950-73767680-3c91-11eb-9d33-3a41d94fca21.png)


- [ ] on above picture belts are overlapping like "4 pixels" thorny said, so legs looking squeezed together.
for some reason belt textures overlap like 4 pixel total i couldnt fix in XML so its a C# or texture problem? 
probably, padding is off in either of them.
![image](https://user-images.githubusercontent.com/41029070/101986734-07474300-3c90-11eb-817c-62e9e86e0e42.png)

**Comment by lilwhitemouse** [comment]
Arrows on splitters do not show b/c their offset is too low - the arrows are *below* the building.

**Comment by lilwhitemouse** [comment]
Arrows fixed in 6e45b5e8906c5df282e55c1b16ab6e4a42b2ba48

**Comment by lilwhitemouse** [comment]
SAL unit should work with belts after b92954a755248eb38add131f0ac4a333434fbaad

**Comment by zymex22** [comment]
i close this one... all initial ones are done, new problems should have seprate issues
