### ISSUE TITLE
Cannot use "Better workbench managment" and "[KV] Save Storage, Outfit, Crafting, Drug, & Operation Settings" on Structures (automated) (Bug report)

### ISSUE THREAD

**Issue by Plasmanian** [zymex22/Project-RimFactory-Revived#195]
Cannot use "Better workbench management" and "[KV] Save Storage, Outfit, Crafting, Drug, & Operation Settings" on Structures (automated) (Things that make stuff like miner etc.) (Only the miners)

* https://steamcommunity.com/sharedfiles/filedetails/?id=1180718516&searchtext=bills
* https://steamcommunity.com/sharedfiles/filedetails/?id=935982361&searchtext=better+workbench

**Comment by zymex22** [comment]
related to this PR we had:
https://github.com/zymex22/Project-RimFactory-Revived/pull/116

we said back then we would not support if it makes us need a extra dependency

**Comment by Sn1p3rr3c0n** [comment]
I just made a Attempt to add support for `Better Workbench Management`
unfortunately i have to conclude that it is currently not possible to do so.
The problem originates form the fact that we can't use the Vanilla `ITab_Bills` as it is hardcoded to only work with `Building_WorkTable`.

This accordingly affects mods such as `Better Workbench Management`.
`Better Workbench Management` expects `Building_WorkTable` but we can only provide `ITabBillTable`
unless I am missing something here, this means that we would need to rewrite `Better Workbench Management` to get it to work.

To me this is not a viable option.

Attached is a patch with my progress until i decided to make this post.
[bwm_attempt.zip](https://github.com/zymex22/Project-RimFactory-Revived/files/8715210/bwm_attempt.zip)

---
Todo:
- [ ] Check `[KV] Save Storage, Outfit, Crafting, Drug, & Operation Settings`
