### ISSUE TITLE
research for drones (Drones)

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#199]
Add 3 level drone research.
Level 1 drones will set Baselevel for 10 (properly just set from start)
Level 2 will set level 15
level 3 will set level 20 for base

individual level should properly be same?
or should we add a overwrite option to scale with above research? dunno?

**Comment by zymex22** [comment]
addded research for drone research into master:
https://github.com/zymex22/Project-RimFactory-Revived/commit/b63dd8d296071708c36b179f47acb2503284c0d0

PRF_BasicDrones = 10
PRF_ImprovedDrones = 15
PRF_AdvancedDrones = 20

**Comment by Sn1p3rr3c0n** [comment]
New XML Settings in **ModExtension_Skills**:
`SkillUsage` : 
```
public enum enum_ModExtension_SkillsskillUsage
{
	ThisOverrides = 0,
	ReserchIsCapping = 1,
	ThisIsCapping = 2,
	ReserchOverrides = 3
}
```
**ThisOverrides = 0:**
The Level as defined in `skills` is final

**ReserchIsCapping = 1**
The Level as defined in `skills` is capped by the Research

**ThisIsCapping = 2**
The Level is set via Research is capped by the Level Defined in `skills`

**ReserchOverrides = 3**
The Level is set via Research is final

**TODO**
_Test the XML Setting_
_Optimize when the skill level get refreshed (may need to send drones to base for the update)_
