### ISSUE TITLE
Reinstall "mini" drone station (Bug report)

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#203]
# Describe the bug
When trying to reinstall mini drone station it will disappear and throw a error

it will throw below error when trying to.

https://gist.github.com/c440affc384a0949c1283f180cba2085
![image](https://user-images.githubusercontent.com/41029070/96236513-70fee580-0f9c-11eb-8bad-a8b0d841d479.png)

**Comment by Sn1p3rr3c0n** [comment]
@zymex22 Can you please provide additional details? I cant reproduce that issue.

**Comment by Sn1p3rr3c0n** [comment]
For documentation:
This issue occurs when a drone attempts to reinstall its own base.
See: https://cdn.discordapp.com/attachments/693933621349974040/766924594640453652/unknown.png

Once the Station is uninstalled all spawned drones will be destroyed, this includes the drone currently attempting to move the station.

One side effect see,s to be that the Station will be lost.

**Comment by Sn1p3rr3c0n** [comment]
30e3e74 is a only Partial fix for the issue.

While this change successfully prevents a Drone from:
- Uninstalling its own Station
- Reinstalling its own Station
- Deconstructing its own Station

`Reinstalling its own Station` can cause:
That the Station wont start any job (cause it always selects the undesired one in the scanner)
_For this commit a Log Waring with the offending cells is displayed_
