### ISSUE TITLE
Spawn with full drone bug (Bug report)

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#205]
# Describe the bug
There seem to be something wrong with initial starting drones on drone column/mini drone station?

they are set to:
`<spawnWithFullDrones>true</spawnWithFullDrones>`
but both only start with 1 out of 2

mini drone station has:
`<initialConfigurableTargetFuelLevel>1</initialConfigurableTargetFuelLevel>`

and drone column has:
`<initialConfigurableTargetFuelLevel>2</initialConfigurableTargetFuelLevel>`

and both have
`<fuelCapacity>2</fuelCapacity>`

so why are they only starting with one each?
it seem to work on drone cultivator it starts with 2 drones
is it because `<maxNumDrones>2</maxNumDrones>`  
is not used like on cultivator? i tried that one but that didnt work either

**Comment by Sn1p3rr3c0n** [comment]
Not solved - On reload 1 drone can be missing

**Comment by Sn1p3rr3c0n** [comment]
Refuelable Drone stations currently loose 1 drone on each load compared to the amount saved.

_Note: Only Building_DroneStationRefuelable are affected_
