### ISSUE TITLE
Reinstall cultivator (Bug report)

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#224]
# Describe the bug
When trying to reinstall drone cultivators, drones will not work in new area, and they will fly over to old one instead.....

**To Reproduce**
Reproducibility: always?
1. install a drone cult.
2. reinstall it
3. dont work

**Comment by zymex22** [comment]
Extrien
> so i made a new cultivator on the map. it worked in the area around itself as expected. after doing reinstall, it worked in both the new location and hte old location. i then save and load. now it works in the old location but not the new location

**Comment by Sn1p3rr3c0n** [comment]
For additional Documentation:
This issue is resolved with 93872b9 (as described in the commit)
This Ticket can be closed once the fix is merged to master (blocked by the remaining issues of #186)
