### ISSUE TITLE
Allow Splitters to accept items/links from any direction

### ISSUE THREAD

**Issue by Daemon976** [zymex22/Project-RimFactory-Revived#225]
# Describe the bug
When placed facing North or South Conveyor Splitters stop accepting placement of items after X items pass through (~300?).

**To Reproduce**
Reproducibility: Easy
1. Place splitter (normal or underground) facing north or south per arrow
2. Connect belts in a 'T' formation - input on East, outputs on North and West
3. Configure filters to split contents between North and West
4. Feed items into East input belt

**Expected behavior**
Splitter outputs based on configured filters

**Actual Behavior**
After roughly 300 items pass through, the splitter stops accepting item placement.  However, if you click on the connecting East input belt and 'drop' the item pending placement, the next ~300 items will pass through and filter until it stops again.

![image](https://user-images.githubusercontent.com/73858835/97929688-4d26f800-1d2f-11eb-9a66-9d802c701c26.png)

Note that this does not occur if splitter is placed East/West.

**Rimworld (please complete the following information):**
 - RimWorld Version: Steam current release
 - PRF Version: 2.50 Test
 - Type:
 - Severity:

**Comment by lilwhitemouse** [comment]
Honestly, I'm impressed anything goes through.  Designed behavior for the splitter: if it's pointed N, it accepts items from the S.  If it's pointed S, it accepts items from the N.

Changing the splitters to directly accept items from other directions is planned.  (You can see there's no actual link in the image above)
