### ISSUE TITLE
Expose assembler settings to xml (Request)

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#228]
Can we expose settings for adaptive assemblers to xml, so i can adjust and/or make new settings for adaptive style assemblers also.

im not sure what options there already is in C# but i guess maybe just expose whatever there is?

things i would like to have thoug would be:

- base speed (might already be there with:
`<workSpeedBaseFactor>0.1</workSpeedBaseFactor>`
- Min. speed
- max. speed (now 500%?)
- min. quality (eq. starts at normal instead of awfull)

can properly be added to:
```xml
    <modExtensions>
      <li Class="ProjectRimFactory.SAL3.Exposables.AssemblerDefModExtension">
        <drawStatus>true</drawStatus>
        <doEffect>false</doEffect>
        <skillLevel>10</skillLevel>
        <artSkillLevel>9</artSkillLevel>
      </li>
    </modExtensions>
```
since that one is already used for adaptive assemblers / simple assemblers

**Comment by Sn1p3rr3c0n** [comment]
```XML
<li Class="ProjectRimFactory.SAL3.Things.Assemblers.Special.ModExtension_LearningAssembler">
        <MinSpeed>1</MinSpeed>
        <MaxSpeed>5</MaxSpeed>
        <MinQuality>Masterwork</MinQuality>
        <MaxQuality>Legendary</MaxQuality>
</li>
```
`MinSpeed` and `MaxSpeed` are float values, the are interpreted as %
_So in the example above it starts at 100% and ends at 500%_

if `MaxSpeed` is not set it defaults to infinite
`MinSpeed` defaults to 50%

'MinQuality' & `MaxQuality` are currently only implemented as a hard limits.
