### ISSUE TITLE
PRF Range power slider sound bug (Bug report)

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#233]
# Describe the bug
If your moving range slider to any middle position between min/max it will say clicking sound constantly, until changting to min/max.

its only on Range and not power speed boost for some reason.
its on Part assembler / metal refinery and properly other 

seem to be only "simple assemblers" though?

**Comment by Sn1p3rr3c0n** [comment]
The issue is that `CircleRange` is disregarding the Size of the building.
the other 2 range Types are both considering the size on the building

_Update is in:_
`\ProjectRimFactory\Common\CompPowerWorkSetting.cs`

**Comment by Sn1p3rr3c0n** [comment]
partially a XML issue an partially an oversight in the code 
you need to make sure that a clean division is possible.
in the issue case:
```XML
<li Class="ProjectRimFactory.Common.CompProperties_PowerWorkSetting">
        <!-- speed settings -->
        <speedSetting>true</speedSetting>
        <minPowerForSpeed>750</minPowerForSpeed>
        <minSpeedFactor>1</minSpeedFactor>
        <maxPowerForSpeed>3000</maxPowerForSpeed>
        <maxSpeedFactor>4</maxSpeedFactor>
        <!-- range settings -->
        <rangeSetting>true</rangeSetting>
        <minPowerForRange>0</minPowerForRange>
        <minRange>1</minRange>
        <maxPowerForRange>500</maxPowerForRange>
        <maxRange>4</maxRange>
        <allowManualRangeTypeChange>true</allowManualRangeTypeChange>
        <rangeType>ProjectRimFactory.Common.RectRange</rangeType>
      </li>
```
500/(4-1) = 166.66666 ==> Causes issue

**Comment by zymex22** [comment]
temporary been fixed in xml =) might need a update to not cause this issue, leave open?
