### ISSUE TITLE
Circle shape sould be larger

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#234]
Is there any way to make circle start +1 ? to be right in cell count it should properly be Radius +1 to be closer to Square option

@Sn1p3rr3c0n

**Comment by Sn1p3rr3c0n** [comment]
The issue is that CircleRange is disregarding the Size of the building.
the other 2 range Types are both considering the size on the building

Update is in:
\ProjectRimFactory\Common\CompPowerWorkSetting.cs
