### ISSUE TITLE
ModExtension_BonusYield (Request)

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#238]
@Sn1p3rr3c0n 
> what do you think would it be a good idea to expand `ModExtension_BonusYield` so that you can configure yield depen

I think it would be a great addition to make more use of that comp for special jobs, and will be super nice when starting working on PRF - Insanity and PRF - Materials, as extras/secondaries will be super nice option

**Comment by Sn1p3rr3c0n** [comment]
@zymex22 `ModExtension_BonusYield` now has a bill depended option.
The old way:
```xml
<bonusYields Chance="0.25">
   <SculptureLarge Weight="0.5" Count="1" Quality="6" MaterialDef="Gold" />
</bonusYields>
```
is still available. it can be used when something should happen independent of the bill.

---
The new way:
```xml
<billBonusYields>
   <li>
      <key>Make_SculptureSmall</key>
      <value Chance="1">
         <SculptureLarge Weight="0.5" Count="1" Quality="6" MaterialDef="Gold" />
      </value>
   </li>
</billBonusYields>
```
`<key></key>` holds the RecipeDef name
`Chance=""` is located in the value element
This means that different RecipeDefs can have different chances for different additional things
`<value Chance="1"></value>` Holds the standard Bonus Yield Line

_General note:_ 
The script prioritizes `billBonusYields` over `bonusYields`.
if you get nothing from `billBonusYields` you have a chance for `bonusYields`.
if you get something from `billBonusYields` you have **no** chance for `bonusYields`.
