### ISSUE TITLE
Button for rotate working area/zone (Request)

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#241]
daemon976 asked if we could add a rotate zone button for new change area zone, as it would make it easier setup rectangle one and possible future new shapes if we do other ones later.

i made a suggestion on picture below, maybe just a small button with that arrow we use for output cell might be propiate? =)
![image](https://user-images.githubusercontent.com/41029070/99447005-629b4500-291f-11eb-8e90-13f8bdf077be.png)

**Comment by Sn1p3rr3c0n** [comment]
added with 371fda3

![prfRotZoneTab](https://user-images.githubusercontent.com/68663281/101247663-102d9700-371b-11eb-8253-37b784723ee0.png)
