### ISSUE TITLE
HELP ME?! how does Heat thingy work in vanilla?

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#251]
Vanilla mechanics you can use:

```xml
    <comps>
      <li Class="CompProperties_HeatPusher">
        <compClass>CompHeatPusherPowered</compClass>
        <heatPerSecond>4</heatPerSecond>
      </li>
    </comps>
```

and:
```xml
    <building>
      <isMealSource>true</isMealSource>
      <spawnedConceptLearnOpportunity>BillsTab</spawnedConceptLearnOpportunity>
      <heatPerTickWhileWorking>0.10</heatPerTickWhileWorking>
    </building>
```
(taken from fueled stove)

But does our assemblers and other equipment fully support both above or only one or non of them?
Would properly be good start using `<heatPerTickWhileWorking>0.10</heatPerTickWhileWorking>`
too.

and comp im already using but not sure if it works properly or not xD
what does:
`<compClass>CompHeatPusherPowered</compClass>`
mean? just it will push 5 heat whenever it has power? :D
i can see fueled furnace use it like that too so powered/fueled i guess?

if someone can explain above ill start using it properly lol :P

**Comment by Sn1p3rr3c0n** [comment]
@zymex22 
from my understanding:
```XML
   <comps>
      <li Class="CompProperties_HeatPusher">
        <compClass>CompHeatPusherPowered</compClass>
        <heatPerSecond>4</heatPerSecond>
      </li>
    </comps>
```
is supported by all buildings with no additional code. (-> Should work for PRF)

'CompHeatPusherPowered' pushes Heat if the building is Powered (dos not matter if it is Fuel or Electricity) 
'CompHeatPusher' seems to push no matter what


---
```XML
    <building>
      <isMealSource>true</isMealSource>
      <spawnedConceptLearnOpportunity>BillsTab</spawnedConceptLearnOpportunity>
      <heatPerTickWhileWorking>0.10</heatPerTickWhileWorking>
    </building>
```
is not supported without additional Code (This seems to be not implemented for any PRF Building) (-> Should **not** work for PRF)

**Comment by zymex22** [comment]
thanks ill close this tthen, we might consider if we might add support for heatPerTickWhileWorking but dunno yet.
