### ISSUE TITLE
Compatibility: PRF drones can't store in Deep Storage

### ISSUE THREAD

**Issue by lilwhitemouse** [zymex22/Project-RimFactory-Revived#258]

**Comment by zymex22** [comment]
LWM i think if you use your robot compability setting in DS, it works (need testing)
but if so maybe make that option auto on IF PRF are installed in DS?

**Comment by zymex22** [comment]
probably a wont fix in PRF? i think its a DS issue or?

**Comment by zymex22** [comment]
was fixed in DS i think right? @lilwhitemouse
