### ISSUE TITLE
Belt power settings cannot be adjusted (Bug report)

### ISSUE THREAD

**Issue by JulianSkies** [zymex22/Project-RimFactory-Revived#263]
# Describe the bug
Belts are moving items extremely slowly, if you enter the power settings the slider's knob cannot be seen and the Boost Power is locked to 0, cannot be altered. Messing around with the boost power will cause the items to temporarily move extremely fast.

**To Reproduce**
Reproducibility: ?
1. 
2. 
3. 

**Expected behavior**
The knob for configuring boost power should be selectable, and the value should be between 7 and 15.

**Actual Behavior**
A clear and concise description of what actually happen.

**Screenshots**
![Power Tab](https://user-images.githubusercontent.com/20136904/100294614-188d1180-2f66-11eb-82af-dee28e6c7374.png)

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.2
 - PRF Version: Master branch, 25/11/2020
 - Link to gist bug report: 
 - Type:
 - Severity:
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed:
 - Your modlist (if needed): 
 - Do you know what mod conflicts?:

**Additional context**

**Comment by JulianSkies** [comment]
Additional context:
Simply clicking repeatedly on the text input field will vastly accelerate belts.

**Comment by zymex22** [comment]
known issue and is on the todo list for belts already i close it here because its in the other todo list for belts =)
