### ISSUE TITLE
Unify Output cell rotation

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#268]
Gotten comment a number of times that T3 miner can output diagonally and other only top, buttom, left, right....
its becauuse T3 miner uses nobos output system and can output diagonally....

We should properly swap so all machines use same system?
seems like most wan't it to be able to output diagonally?
so maybe nobo's style win?

**AerosAtar**
> Plasma Drill output cell can be diagonals (it is the only one I've seen that has this)
![image](https://user-images.githubusercontent.com/41029070/100497634-12ad5100-315d-11eb-9218-a3559c34307c.png)

**Comment by Sn1p3rr3c0n** [comment]
Unified the Output Cell rotations with cb3e6a3 and f68787c.

**Todo:**
- [ ] Add XML Setting to allow diagonal Output Cells

**Comment by Sn1p3rr3c0n** [comment]
@zymex22 if you want to set Diagonal Output Cells you can do so like this:
```XML
<li Class="ProjectRimFactory.Common.CompProperties_CompOutputAdjustable">
    <SupportDiagonal>true</SupportDiagonal>
</li>
```
it is set to false by default

**Comment by zymex22** [comment]
cool ill give a try after im done messing with defnames =)
