### ISSUE TITLE
 (Bug report)

### ISSUE THREAD

**Issue by AerosAtar** [zymex22/Project-RimFactory-Revived#270]
# Describe the bug
Any item getting stuck on a splitter will appear to be hovering off in the middle of nowhere, rather than on the splitter's tile.

**To Reproduce**
Reproducibility: ?
1. Place items on a belt
2. Have them move through a splitter with either all outputs off or the output blocked
3. Observe the amazing floating thing!

**Expected behavior**
The item is displayed as stuck on the splitter's tile.

**Actual Behavior**
The item is displayed off in the middle of nowhere.

**Screenshots**
![image](https://user-images.githubusercontent.com/13503100/100700505-88036680-3395-11eb-94bb-e8510f81cb7f.png)

**Comment by zymex22** [comment]
@AerosAtar are this problem still present?

**Comment by AerosAtar** [comment]
I haven't played Rimworld in months, so I have no idea, sorry.

**Comment by zymex22** [comment]
closed, we open if reported again
