### ISSUE TITLE
 (Bug report) Industrial Furnaces disallow some clothing types in the Burn apparel bill

### ISSUE THREAD

**Issue by Riderfighter** [zymex22/Project-RimFactory-Revived#278]
# Describe the bug
The "Burn apparel" task for Industrial Furnaces doesn't fetch all possible types of clothing correctly. With CE loadbearing equipment such as backpacks don't show up in the possible items list. It also seems as if the "Burn apparel" ignores clothing that can be smelted into raw materials, maybe have a way for industrial furnaces to smelt items to their raw materials.

**To Reproduce**
Reproducibility: Common
1. Create "Burn apparel" task in an industrial furnace. 

**Expected behavior**
The expected behavior would be to load all types of clothing and burn(delete) them.

**Actual Behavior**
Not all possible clothing types are being loaded and burnt.

**Screenshots**

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.2
 - PRF Version: Whatever is before 2.5.0 update
 - Type: Annoying
 - Severity: Medium
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed:
 - Your modlist (if needed): 
PRF
CE
 - Do you know what mod conflicts?: Yes(?)

**Additional context**

**Comment by Sn1p3rr3c0n** [comment]
This is not an issue with PRF but it's an XML Error in CE.
The XML for Backpacks dos not set:
```XML
    <burnableByRecipe>true</burnableByRecipe>
    <smeltable>true</smeltable>
```
in the ThingDef. Therefore the game sees them as false. 

The Recipe used by PRF Correctly Checks for `burnableByRecipe` and `smeltable` and therefor it wont work

_Note:_
_This can easily be tested with vanilla Equipment & Stockpiles_

**Comment by MadaraUchiha** [comment]
@Riderfighter Please open an issue with Combat Extended [here](https://github.com/CombatExtended-Continued/CombatExtended/issues/new/) and provide a link to this issue as well.
