### ISSUE TITLE
Compatibility with RimNauts: drills mine moon chunks on the planet

### ISSUE THREAD

**Issue by 1ucket** [zymex22/Project-RimFactory-Revived#288]
# Describe the bug
The drills produce rock chunks which should only be produced on the moon added by RimNauts. The respective chunk types can also be selected in the Plasma Drill.

**To Reproduce**
Reproducibility: ?
1. Have Project RimFactory Revived & RimNauts installed
2. Build any drill

**Expected behavior**
The drill does only mine planet generated rock chunks.

**Actual Behavior**
The drill also produces Maria and Lunar Highland chunks, materials exclusively found on the moon.

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.2.2753
 - PRF Version: 2.4.9
 - Link to gist bug report: 
 - Type: compatibility issue
 - Severity: only balancing
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: no
 - Your modlist (if needed): relevant mod: RimNauts
 - Do you know what mod conflicts?: RimNauts

**Additional context**

**Comment by zymex22** [comment]
ill do a patch for RimNauts in next release =) its because miners will mine ANY minable ores unless i patch them out
=)

**Comment by 1ucket** [comment]
I already guessed so, that's why I opened the bug. I hope it wasn't a duplicate.

Anyways thanks for the great mod, keep it up! :D

**Comment by zymex22** [comment]
there added patch, so i close this, it will be out in next big release comming soon =) tthank you for your report
