### ISSUE TITLE
Drone Stations are saving their areas cell by cell and not as a group

### ISSUE THREAD

**Issue by Daemon976** [zymex22/Project-RimFactory-Revived#291]
Drone Stations are saving every cell in their range as a separate record, causing massive save file bloat.  This appears to be a recent change as of the last 4 days.

1. Start game
2. Build basic base WITHOUT any drone stations.
3. Save as Test1
4. Add a mini-drone helper station
5. Save as Test2
6. Compare save files

In testing found that the longer the game runs the more of these records are generated.  Each has a unique ID, is it not cleaning up old records and just adding new ones?
[Saves.zip](https://github.com/zymex22/Project-RimFactory-Revived/files/5680777/Saves.zip)

4 mini-helpers generated 150K of the following record types:
</arrDeflate>
                            </innerGrid>
                            <label>Area 2</label>
                            <color>RGBA(0.476, 0.433, 0.599, 1.000)</color>
                        </li>
                        <li Class="ProjectRimFactory.Drones.DroneArea">
                            <ID>301557</ID>
                            <innerGrid>
                                <trueCount>361</trueCount>
                                <mapSizeX>325</mapSizeX>
                                <mapSizeZ>325</mapSizeZ>
                                <arrDeflate>
7dCxCYBQEERBxcDQEizF0rQ0S7EEQwNxrUC48Asz8eMWrusAAAAAAADgX5Kx1B1J7eCdudRtyVAKz6y15SdTqduTvhReWWrLnvit
/ScCAAAAANCAFw==
</arrDeflate>

**Rimworld (please complete the following information):**
 - RimWorld Version: Current
 - PRF Version: Core build as of 8:00 AM CST (us) 12/11/20
 - Type: Save game
 - Severity: HIGH - results in 10 minutes to save/load on an Intel i9 to a samsung 980 pro m.2 drive.

**Comment by zymex22** [comment]
@Sn1p3rr3c0n is this expected function?

**Comment by Sn1p3rr3c0n** [comment]
**Points that we should fix** 
- [ ] Not Cleaning up Old Zone Areas

_This issues became noticeable with #283 as a cleanup is not performed_

**Unclear to me:**
- results in 10 minutes to save/load on an Intel i9 to a samsung 980 pro m.2 drive. (i have a weaker system an haven't noticed save/ load Times That Long) (testing with new save pending)
- cell by cell and not as a group (what do you mean as a group?)

**Comment by Sn1p3rr3c0n** [comment]
added Cleanup code with 8405d5e -> the save file is no longer exploding in size.
_please note that this wont fix your old save. just prevent it form occurring again_

@Daemon976 can you please respond to my unclear points?

**TODO**
- [ ] check performance of `.Equals`

**Comment by Daemon976** [comment]
Referring to user impact of bloated save file.

Core area references consolidate their area definition when possible to: from X,Y to X, Y.

And thank you for fixing.
