### ISSUE TITLE
Prefs.ScreenHeight can be 0

### ISSUE THREAD

**Issue by Sn1p3rr3c0n** [zymex22/Project-RimFactory-Revived#296]
`Prefs.ScreenHeight` can be 0
this can be an issue for the `ITab_ProductionSettings`.

The cause for this is currently unknown.

**Comment by Sn1p3rr3c0n** [comment]
@lilwhitemouse ce1ce20 should resolve the issue by not using the clamp if the `Prefs.ScreenHeight` is faulty.

however i have no idea what would be causing this issue.

The following functions could help resolving the issue but possible negative effects are impossible to predict without tests. Those can't be performed as i have no idea what causes the issue in the first place.
```CSharp
RimWorld.ResolutionUtility.SafeSetResolution(Resolution res)
RimWorld.ResolutionUtility.Update()
Verse.Dialog_ResolutionConfirm.Revert()
```

**Comment by lilwhitemouse** [comment]
I made some changes in https://github.com/zymex22/Project-RimFactory-Revived/commit/0d372a8bfda83d61522ec9fc5d1a7b7b496eeedb that might fix this.  I introduced "minHeight = 200f" and "maxHeight=900f" and then used `UI.screenHeight`, which seems to be used a  lot in the vanilla codebase.

More testing would be a good idea.

**Comment by zymex22** [comment]
@Sn1p3rr3c0n @lilwhitemouse i dont have any issues in this branch settings open just fine. (but did also before, after i moved down and up in reso.) so might not be able to test it properly either...

wasnt sure if it was this one or LWM's master commit i should test....


ive tested both and both can open setting window fine..

though on master/lwm's versions some of them seems a bit tooo cramped?! :P
![image](https://user-images.githubusercontent.com/41029070/102053461-17723600-3de8-11eb-8d6d-c9c16c13948a.png)
its only those with those 3 options. if they have more options like cultivator, slaugterhouse and such it become wider

![image](https://user-images.githubusercontent.com/41029070/102053605-4ee0e280-3de8-11eb-8d9f-4f00ab8d7adf.png)
