### ISSUE TITLE
Items Itab add a Toggle button fuzzy search

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#300]
when i click use on a pawn and pawn will come and pickup pants.... it will throw this:
![image](https://user-images.githubusercontent.com/41029070/102047500-a3329500-3ddd-11eb-83c1-3f8717563748.png)

![image](https://user-images.githubusercontent.com/41029070/102047492-9f9f0e00-3ddd-11eb-9f12-9584bf778e2e.png)

![image](https://user-images.githubusercontent.com/41029070/102047482-9c0b8700-3ddd-11eb-911a-ff154501a98b.png)

```
Exception filling tab ProjectRimFactory.Storage.UI.ITab_Items: System.NullReferenceException: Object reference not set to an instance of an object
  at ProjectRimFactory.Storage.UI.ITab_Items.DrawThingRow (System.Single& y, System.Single width, Verse.Thing thing) [0x00109] in <1e70a838b9e54f7ca442a6e30dafcfe1>:0 
  at ProjectRimFactory.Storage.UI.ITab_Items.FillTab () [0x00256] in <1e70a838b9e54f7ca442a6e30dafcfe1>:0 
  at Verse.InspectTabBase+<>c__DisplayClass14_0.<DoTabGUI>b__0 () [0x00039] in <d72310b4d8f64d25aee502792b58549f>:0 
Verse.Log:Error(String, Boolean)
Verse.Log:ErrorOnce(String, Int32, Boolean)
Verse.<>c__DisplayClass14_0:<DoTabGUI>b__0()
Verse.ImmediateWindow:DoWindowContents(Rect)
Verse.Window:InnerWindowOnGUI(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)
```

because it clicked force equip on a pawn and WHEN pawn come and pick it up it ofc throw that error because its not on list anymore
if i use drop/output button it isnt a problem though

**Comment by lilwhitemouse** [comment]
Suggested first attempt to solve this:

First line of `DrawThingRow` should probably be `if (thing==null) return;`

**Comment by zymex22** [comment]
Should add a toggle button for on/off fuzzy search @Riderfighter said was missing and todo for later

This update may be made with #178

**Comment by lilwhitemouse** [comment]
2nd line should probably be
`if (!thing.Spawned) return;`

**Comment by techno156** [comment]
Related:
DSU item list has poor performance if there is a large number of items in the DSU (> 100 stacks). Tested in both vanilla and modded games. This performance impact seems to only affect the DSU, as other storage mods are not affected, and was not observed to occur in older version of RimFactory, that had the old DSU item list behaviour.

Performance decreases as the number of items in the DSU increases, to the point where a vanilla game can experience noticeable lag at high item stack counts (> 100 stacks) if the DSU item list is open.

**Comment by Sn1p3rr3c0n** [comment]
Toggle has been added with #760
Still need to do that check

**Comment by Sn1p3rr3c0n** [comment]
Can't cause any spammy errors.
Closing
