### ISSUE TITLE
Prettify Itab for Belt Splitters (Request)

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#301]
Belt splitter need to be prettified as its not very uuserfriendly layout right now.

Up for any takers?
so we can unload some of the work from LWM
@Riderfighter @Sn1p3rr3c0n 

![image](https://user-images.githubusercontent.com/41029070/102050564-5e116180-3de3-11eb-86d3-12d7db19ce6d.png)
right now it looks like this....
thats pretty unclear ond confusing to both old and new players... i suggest a new layout...

### We have following elements:
**Description**
**Dots** = settings for that directions.
**X/Check** = if it should output at all to that direction.
**Priority** = ...
**Filter settings** = ...

i see to possible better layouts? (might be more feel free to be creative...)
Make its list style instead so
North - Dot - X
West - Dot - X
East - Dot - X
South - Dot - X

-- OR --

Keep layout for
North, West, East, South

but move x/check to a list above the North, West, East, South layout.

Just a small how it works info...

You can click each dot to set filter for specific direction... each can be set independent...
X/check will shot off that output but without need to redo filter settings, usefull for temporal closing a line but want same settings later.

**Comment by lilwhitemouse** [comment]
Belts should not allow activating output when there is input from that direction.

It's funny to watch, but...

**Comment by Sn1p3rr3c0n** [comment]
### Current status of the Updated:
![splitter_UI](https://user-images.githubusercontent.com/68663281/126898835-bd42c9da-1d81-4346-b4d8-1cdb083dda7b.PNG)
**Functionality**
Use the left mouse button to select an input
Use the right mouse button to disable or enable an Output (not possible for inputs)

inputs are currently displayed in green and facing inwards

the rest is untouched for now

**Known Issues / TODO:**
- fix input detection if a Splitter inputs into another Splitter
- fix squished Textures
- add selection Textures for inputs
- use better Textures
