### ISSUE TITLE
T0 miner can't be placed (Bug report)

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#308]
# Describe the bug
When trying to place T0 miner on Mountain rock placeworker works perfectly and it can ONLY be placed on a mountain.
Problem is it even though it uses

```xml
    <clearBuildingArea>false</clearBuildingArea>
    <altitudeLayer>BuildingOnTop</altitudeLayer>
```

Still assign those 3 cell to be mined after placing blueprint...
It does however work fine if placing in godmode, without removing mountain wall before placing.

Problem in above is that it will IF those 3 cells mined remove blueprint and not build.

----- hmm furter testing without "Replace Stuff" mod have shown i cant even get it to highlight / placeworker to function without god mod on a unsmoothed wall...
it can get it to highlight in god mode though.

If i smooth wall first, i can get blueprint layed down with and without god mode.
and they CAN build it without mine wall first...

So might be something to do with unsmoothed wall is "nothing" and not owned/claimed or anything...

-- Another solution may then be just only build on smooth wall if we can't get anything else to work...

**To Reproduce**
Reproducibility: ?
1. place a T0 miner in a mountain
2. Wait for a pawn to try build
3. it will mine cell clear first instead
4. Blueprint then gets removed and will not build

Notes:
- God mode Let you place it correct.
- "Replace stuff" mod make placeworker work on unsmoothed wall
-  There is difference in smooth and unsmoothed wall without godmode

**Expected behavior**
Should not clear mountain before placing T0 Miner.

**Screenshots**
![image](https://user-images.githubusercontent.com/41029070/102687432-54c33300-41ef-11eb-968c-7e58fef9bb8d.png)

**Additional context**
If this isnt fixed before 2.5.0 release we should move this Miner to a later update.
That may however affact functions in PRF - Materials. but i can find a temporary solution instead for materials

**Comment by Sn1p3rr3c0n** [comment]
96ee1f0 resolves the issue.

There is a slight mod conflict with Replace Stuff
When placing the mine over Natural Rock "Replace Stuff" will automatically designate the Rock to be Mined despite that fact that this is not required by our Place Worker.

This has the following Effects for us:
- The Visuals look of as the Rock background is missing
- If the Mine Every gets Destroyed ore deconstructed it can't be placed on the same Spot again as the Required Rock has been removed

I will Open an issue with Replace Stuff and link it to this issue.
