### ISSUE TITLE
Prettify Settings Itab after overclock

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#312]
Ok just so things dont get messed up ill post my suggestion i had in snipers overclock tab issue, here instead =)

- Dunno if this is Related here? for Settings Itab.
but maybe we should update that Output part of it:
![image](https://user-images.githubusercontent.com/41029070/102777859-c20ec980-4391-11eb-81f8-316b76307207.png)
so remove line between those 2 settings as the control same thing..
and a Header that say whatever those options actually do control

- Can T3 miner and other ones that didnt have settings Itab before have that now as well?
(it dont now) but can it? i seet speed works on it =)

- found this, one case where sizeing for some reason was a bit funny? :P
probably came when er resized setting itab i guess? (only on part assembler so far i think?)
![image](https://user-images.githubusercontent.com/41029070/102777922-dfdc2e80-4391-11eb-951f-c5c77c339061.png)

When someone starts work on settings tab let me know and ill make a better todo list for them, for now i just moved notes from other issue into here

**Comment by zymex22** [comment]
Oka now that lwm have updated and made a Item or stack it should be something like this:

![image](https://user-images.githubusercontent.com/41029070/103157838-82901500-47b7-11eb-9613-c5055409950f.png)

### Need to be done

**Output Section:**
- [ ] Add a Header seting "Output Options"
- [ ] Remove line between each type.
- [ ] Add a new line under Output Section so its always under that, and not between.
**Puller Section**
- [ ] Add a header for puller section
- [ ] Move LWM's new Item/stack one to Puller Section probably?
- [ ] "processing stops when...." should be when hover "activate limit"
- [ ] Add hover "Limit Value" so we can add description
- [ ] Add hover "count stacks" so we can add description
- [ ] Add hover "what zone" so we can add description
**Slaughter house**
- [ ] fix sizing its huuuuge (probably just half size for those num boxes)
- [ ] Slaugter seem to have puller output/zone option, they should not have that. i guess? no other building have those.


May be more... but i think theese are a good start?

**Comment by Sn1p3rr3c0n** [comment]
slaughterhouse
Check if it is possible to add support for very low resolution screens. (1366x768)
![unknown](https://user-images.githubusercontent.com/68663281/143786342-b6554db2-2b56-42ee-8e6f-8fb8d36d53cd.png)
reported by `cena#0030` on discored
