### ISSUE TITLE
Pick Up and Haul support for DSU

### ISSUE THREAD

**Issue by lilwhitemouse** [zymex22/Project-RimFactory-Revived#315]
Mehni's Pick Up and Haul requires special logic to avoid pawns looping.

LWM knows what to do here (theoretically)

**Comment by lilwhitemouse** [comment]
This will need these two methods for IHoldMultipleThings:

```CSharp
// true if can store, capacity is how many can store (more than one stack possible)
public bool CapacityAt(Thing thing, IntVec3 cell, Map map, out int capacity)  { ... }
// ...The above? I think?  But without needing to know how many
public bool StackableAt(Thing thing, IntVec3 cell, Map map) { ... }
```

**Comment by zymex22** [comment]
This may be related to numerous bug reports we had earlier where pawns did looping on our storage.....
Even got one more yesterday on Lite. it would say this is important we priortize as PUAH is highly used, and we getting that report frequently =)

@Sn1p3rr3c0n @lilwhitemouse 
Who ever can do this =)

**Comment by magneticflux-** [comment]
Is this fix included in the Legacy mod for 1.2? I'm using legacy and my pawns get stuck on DSUs, but I'm not using Pick up and Haul or Jobs of Opportunity.

**Comment by AerosAtar** [comment]
> Is this fix included in the Legacy mod for 1.2? I'm using legacy and my pawns get stuck on DSUs, but I'm not using Pick up and Haul or Jobs of Opportunity.

No, As stated on the mod page: Legacy is unsupported and does not receive any updates. 

It is purely there to allow people to finish their existing runs due to breaking changes in the 2.5 release on the main mod. It is not meant to be used long-term.

**Comment by lilwhitemouse** [comment]
Also, this is a fix for compatibility with PU&H; if you aren't using it, this wouldn't help anyway?

**Comment by magneticflux-** [comment]
> Also, this is a fix for compatibility with PU&H; if you aren't using it, this wouldn't help anyway?

Well, it seems to be the same symptoms. Perhaps PU&H is only exposing a deeper bug with the DSU that isn't fixed in Legacy or the latest and this fix only works for PU&H?

I'll check the logs to see if anything appears when the pawns loop.
