### ISSUE TITLE
DocWorld compatibility

### ISSUE THREAD

**Issue by RomanBuchtaColeso** [zymex22/Project-RimFactory-Revived#346]
Somewhere between dec 29. and jan 2. I Started to get bunch of red errors after Rimworld startup. Errors appear when I load mod D9 framework, which is dependency for DocWorld. errors like this:
Could not resolve cross-reference: No Verse.DesignationCategoryDef named Industrial found to give to Verse.ThingDef PRF_Conveyor_Connector_To_Floor

**Expected behavior**
When I select industrial category in build menu, there should be buildings from PRF.

**Actual Behavior**
Ingame when I open build menu I dont see any buildings from project rimfactory.

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.2
 - PRF Version: 2.5.1
 - Link to gist bug report: https://gist.github.com/HugsLibRecordKeeper/f6144aef9fbb13bb516a8c03296c79a6
 - Type:
 - Severity: 
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: No
 - Your modlist (if needed): PRF, DocWorld, dependencies
 - Do you know what mod conflicts?: D9 Framework

**Comment by Sn1p3rr3c0n** [comment]
@RomanBuchtaColeso 
did you already do the changes as described by Doc?

> Dr Zhivago 30. Dez. 2020 
> Edit to my message:
> 
> Know that for now PRF is incompatible with DocWorld, but patches will be updated with the next DocWorld release. So use the old version of PRF or disable the Architect Category portion of DocWorld to fix it.
