### ISSUE TITLE
Request: Allow belts to forbid on placing

### ISSUE THREAD

**Issue by lilwhitemouse** [zymex22/Project-RimFactory-Revived#347]
Ghostipedia:
Also, is there any way to set belts to 'forbid' items automatically if they exit the belt (I wouldn't say this is an issue but pawns will proceed to then grab said item, cart it back to an input stockpile and it just loops, needs to dump into factory hoppers for Vanilla factions Expanded : Mechs, and I'm just lost on the solution)

**Comment by zymex22** [comment]
seems related to #394 
ppl. seem to want "forbid option" on all items, can we make a universal system/button i think smart hoppers and simple assemblers already has allow forbidden and forbid stuff....

@Sn1p3rr3c0n @lilwhitemouse

**Comment by lilwhitemouse** [comment]
We can probably manage something that works for all AutoMachineTool &c
