### ISSUE TITLE
Minor bug for batteries (Bug report)

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#354]
Batteries don't report "batteries build" so warning will keep popping up "you need batteries"
im pretty sure that has to do that we swapped over to use our own battery class (originally from insanity)

`<thingClass>ProjectRimFactory.Archo.Things.Building_HexCapacitor</thingClass>`

```xml
    <comps>
      <li Class="CompProperties_Battery">
        <storedEnergyMax>4000</storedEnergyMax>
        <efficiency>0.5</efficiency>
        <shortCircuitInRain>true</shortCircuitInRain>
        <transmitsPower>true</transmitsPower>
      </li>
    <comps>
```

it probably just need updated since its a old class i may lack a newer addition/check that is in vanilla class for it.

problem probably also exist on the other class we have:
 `<thingClass>ProjectRimFactory.Industry.Building_CustomBattery</thingClass>`
 used in insanity.

**Comment by Sn1p3rr3c0n** [comment]
`ProjectRimFactory.Industry.Building_CustomBattery` appears to be a perfect? copy of `RimWorld.Building_Battery`
@zymex22 Can you maybe help me with the history here, as i see no reason for this class existing.

`ProjectRimFactory.Archo.Things.Building_HexCapacitor` is not derived from `RimWorld.Building_Battery`
This i can understand as `RimWorld.Building_Battery` is hard coded to make a battery explode. 
For this one we can add a Harmony Patch.
```CSHARP
public class Alert_NeedBatteries : Alert
private bool NeedBatteries(Map map)
```

**Comment by zymex22** [comment]
only difference i know is battery bar is white and placed horizontal instead of vertical it fits nicely on this texture to give a cool effect:
![MegaCapacitor](https://user-images.githubusercontent.com/41029070/103778148-238d9400-5032-11eb-9614-03a2b799549e.png)
then it looks like power on the battery.

other one is uused original here:
![HexCapacitor](https://user-images.githubusercontent.com/41029070/103778198-3607cd80-5032-11eb-81f2-c8c9468a9427.png)
on this one and i assume its because it has a super high number and easier to see difference.

**Comment by Sn1p3rr3c0n** [comment]
For documentation
`ProjectRimFactory.Industry.Building_CustomBattery` dos not derive from `Building_Battery` as you can't call `Base.Base.MYFunc()`
