### ISSUE TITLE
Items disappearing into the void on underground belt

### ISSUE THREAD

**Issue by Suniver** [zymex22/Project-RimFactory-Revived#362]
# Describe the bug
When using a simple setup with underground belts with a puller at the end of the line, items are disapearing from belts into the void and freeze the belt in time (until save reload) with status: "Placing. [Pending Placement 0]".

**To Reproduce**
Reproducibility: Yes
1.  Build Item Puller Mk1 taking steel slags from stockpile and setup it to take steel slags.
2. Build underground belt entrance.
3. Build underground belts.
4. Build underground belt exit and setup it as end of line.
5. Build Item Puller Mk1 taking steel slags from underground belt exit and setup it to take steel slags.
6. Build a smelter (or any other workbench I guess) and add a bill forever (here smelting steel slags).
7. (Optional the result will be the same without the crate) Build a crate to store items and configure pullers to this crate.
8. Build an Auto-assembler Mk1.
9. Toggle pulling on both pullers.

**Expected behavior**
I expect the items to be moved to the auto-assembler and stop when work is done.

**Actual Behavior**
Items are disappearing from the belts into the void and belts are freezed in time with status: "Placing. [Pending Placement 0]"
Maybe linked error: 
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  at System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) [0x00029] in <567df3e0919241ba98db88bec4c6696f>:0 
  at System.ThrowHelper.ThrowArgumentOutOfRangeException () [0x00000] in <567df3e0919241ba98db88bec4c6696f>:0 
  at ProjectRimFactory.AutoMachineTool.Building_BeltConveyor.AcceptsThing (Verse.Thing newThing, ProjectRimFactory.Common.IPRF_Building giver) [0x000b1] in <084c448145cc4528ba86c8c6026b5123>:0 
  at ProjectRimFactory.AutoMachineTool.Building_BeltConveyor.PlaceProduct (System.Collections.Generic.List`1[Verse.Thing]& products) [0x000b9] in <084c448145cc4528ba86c8c6026b5123>:0 
  at ProjectRimFactory.AutoMachineTool.Building_Base`1[T].Placing () [0x00034] in <084c448145cc4528ba86c8c6026b5123>:0 
  at ProjectRimFactory.AutoMachineTool.MapTickManager.Exec (System.Action act) [0x00002] in <084c448145cc4528ba86c8c6026b5123>:0 
Verse.Log:Error(String, Boolean)
ProjectRimFactory.AutoMachineTool.MapTickManager:Exec(Action)
System.Collections.Generic.List`1:ForEach(Action`1)
ProjectRimFactory.AutoMachineTool.<>c:<MapComponentTick>b__1_1(HashSet`1)
ProjectRimFactory.AutoMachineTool.Option`1:ForEach(Action`1)
ProjectRimFactory.AutoMachineTool.MapTickManager:MapComponentTick()
Verse.MapComponentUtility:MapComponentTick(Map)
Verse.Map:MapPostTick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()
```

**Screenshots**
![prf_undeground_belt_into_puller_setup_error_chunks_destroyed](https://user-images.githubusercontent.com/77306553/104456387-de74df00-55a8-11eb-849a-e34b4f2a5e74.png)

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.2.2753
 - PRF Version: 2.5.2
 - Link to gist bug report: https://gist.github.com/41aebe010814b8e91595651b207a144e
 - Type: Exception
 - Severity: Factory breaking? Makes underground belts not usable for me with a puller and a crate at the end of line.
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: Yes.
 - Your modlist (if needed): 
 -> Harmony
-> Core
-> Royalty
-> HugsLib
-> Mod Manager (by Fluffy)
-> Project Rimfactory Revived
 - Do you know what mod conflicts?: None.

**Comment by lilwhitemouse** [comment]
This is actually going to be 2 problems too:
 * `AcceptsItem(...)` needs to carefully check `products`
  * items are disappearing
