### ISSUE TITLE
Exception filling tab ProjectRimFactory.Storage.UI.ITab_Items when looking into crate items

### ISSUE THREAD

**Issue by Suniver** [zymex22/Project-RimFactory-Revived#363]
# Describe the bug
When I click on the crate an exception is thrown and the crate inventory is empty.

**To Reproduce**
Reproducibility: Yes
1. Build a small steel crate.
2. Put so items in it (in my case steel slags)
3. Select the crate.
4. Click on "items" button.

**Expected behavior**
I expect the crate items list to display the steel slags inside.

**Actual Behavior**
The small steel crate UI is empty and an exception is thrown in the console log. When clicking on the "i" button where the items should be displayed, an blurred window is opening instead (see screenshot).

**Screenshots**
![prf_crate_empty_ui_bug](https://user-images.githubusercontent.com/77306553/104457899-ec2b6400-55aa-11eb-97d2-56070d362859.png)

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.2.2753
 - PRF Version: 2.5.2
 - Link to gist bug report: https://gist.github.com/471602a6ccfe81df854001ea0d735d9a
 - Type: UI Exception.
 - Severity: Low. Not game breaking.
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: Yes.
 - Your modlist (if needed): 
-> Harmony
-> Core
-> Royalty
-> HugsLib
-> Mod Manager (by Fluffy)
-> Project Rimfactory Revived 
- Do you know what mod conflicts?: None.

**Comment by zymex22** [comment]
@Suniver can you let me know if problem is still present in newest version? i was not able to recreate this one =)

**Comment by Suniver** [comment]
@zymex22 I still have the bug in the last version

**Comment by Sn1p3rr3c0n** [comment]
@Suniver 6ec00ed should fix the issue.
this can only happen if there are no player pawns on the map

**Comment by Suniver** [comment]
Tested branch. No bug with colonist on map. Fix didn't worked with no pawns on map.
