### ISSUE TITLE
(SAL) the MK II auto assembler doesnt assemble when overclocked to a larger area

### ISSUE THREAD

**Issue by lilwhitemouse** [zymex22/Project-RimFactory-Revived#383]
Eviance: it will only assemble using ingredients in its base range
Eviance: i have tested this extensively. it is just that issue, other assemblers work normally, its just the MKII overclocked one
Eviance: the blue one

The assembler may be directly computing its target input cells instead of using the comp; see GatherUtility.cs

**Comment by lilwhitemouse** [comment]
See line 240 of Building_ProgrammableAssembler.cs - it's directly checking but it is trying to check the comp

**Comment by Sn1p3rr3c0n** [comment]
Correction this is **SAL** and not `ProgrammableAssembler`

Issue can't be reproduced on my end.
Awaiting Logfile from reporter.
