### ISSUE TITLE
SAL - Improvements & Odd stuff

### ISSUE THREAD

**Issue by Sn1p3rr3c0n** [zymex22/Project-RimFactory-Revived#387]
todo:
- [x] remove `Option` for readability
- [x] Stop pawns from using deep drill while SAL is in place
- [x] Add support for research bench
- [x] Stop pawns from using the ResearchBench wihle SAL is working on it 
- [x] Make Research & Drill Speed / Progress Variable / tune it
- [x] Tune Research & Drill Speed / Progress
- [x] Fix issue where total work to do is ignored (Leading to very fast work times)
- [ ] Verify if potential save game incompatibility
> Saved **while** SAL is Working with old version
> Load that save --> Bills are missing from the Bench
- [ ] check if the above can be resolved. (_Steam users will hate me_)
- [x] Fix Error messages after Load (unsaved reserve)
- [x] Fix Faction Relations Error
- [x] Prevent Player from overriding Reservation by SAL **or** stop SAL from working if target is reserved by someone else
- [ ] Check for odd stuff

**Comment by Sn1p3rr3c0n** [comment]
43ffdcf might be a fix for #383

**Comment by zymex22** [comment]
This resolve
#259 
#314 
also?

**Comment by Sn1p3rr3c0n** [comment]
#259 Yes
#314 maybe

**Comment by zymex22** [comment]
I have tested current state

i agree in your "known issues"
- Deep Drill & Research bench are not reserved (pawns can use them at the same time )
that should probably be changed.


- Speed / Progress for Deep Drill & Research are "static"
What does that mean? it can't change with slider or cant change with xml?

- speed seem fine on research bench maybe.
- speed on deep drill seem very fast even with mk 1. version my base got overfloaded pretty fast xD

**Questions:**
1. Do intelectual stat scale on research speed or is it just with speed setting?
2. When using miner it will just fill next cell if full, should we stop operation if output is blocked?
![image](https://user-images.githubusercontent.com/41029070/106042844-e0c55600-60dd-11eb-83fc-18b054dad9ef.png)


**Other notes:**
- [ ] Should have a tag to set allow research. (so we can make a special type)
- [ ] if above is set to true it should remove output worker slot. and input range.
- [ ] can we change color on "operation cell" from yellow to something else, green maybe?
- [ ]

**Comment by Sn1p3rr3c0n** [comment]
@zymex22 all past points should be resolved. 
You can do some additional Tests.

> Should have a tag to set allow research. (so we can make a special type)
I think we shouldn't do that. 
From my point of view SAL are generic stations that can do everything. some are more suited for specific tasks
