### ISSUE TITLE
I/O port Multiple use a once(Bug/Request)

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#389]
**Jdalt40**
> Also is there a way to have pawns be able to all haul to one I/O Port? I've noticed that I need 3-5 I/O Ports when mass hauling stuff because pawns are unable to haul to already in use I/O Ports (when they're already being hauled to by someone else)
> Isn't that much of a problem, just adds a slight bit to cost

We had that report before a couple of times, in different forms.
But in short everytime ppl complain about pawns go directly to DSU instead of I/O or not taking closest I/O port.
This is likely the problem.

I/O ports gets reserved and can't be used by other until first pawn is done.

im not sure if any mods fixes this like share the load, and such? but we should find a definete answer to fix this anyways =)

**Comment by Sn1p3rr3c0n** [comment]
@zymex22 & Jdalt40

1dc0408 disables the reservation of IO Ports. this allows multiple pawns to use the port at the same time.

**potential issues** (we need to test them)
- two or more pawns trying to place an item on the IO port at the same time / tick
- Missing check for input (can be fixed later)
- Upper limit?

**Questions:**
- Should there be a limit on how many pawns can use a port at the same time?
- Any other Balance concerns?
- other bugs / potential issues?

**Comment by zymex22** [comment]
@Sn1p3rr3c0n 
* What can be done about that?
* ..
* If a problem we can make a upper limit of 5 or 10 pawns if that will cause less problems.
i think even 2-5 pawns would be huge upgrade from just one reservering it.

Q:
* see above, but if no problems with being more, i dont think that would be needed unless it impact performance.
* What balance concern would that be? i don't see it as a gamebreaking/OP feature that pawns can haul to same port at same time =)
* Need to test this my self, but just wanted to answer your questions

**Comment by Sn1p3rr3c0n** [comment]
**Test's should be done for:**
- [ ] performance of `Patch_Reservation_Reservation_IO` in a big (late game) Colony
- [ ] Pawn behavior in cases where the DSU is almost full
--> Expecting a `standing` job in the worst case

**Notes**
Performances seems fine.
Regarding Balance, this feels like a huge buff. Since the IO Port are already super powerful we may need some nerf. (but I'm really no expert on how to handle balance just a thought)
