### ISSUE TITLE
Gizmo to create stockpile (Request)

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#390]
i had an idea when i was testing before...

what about most machines that has a input (assemblers)
have a Gizmo so when you click it, it will create and stockpile zone within current input range.
Same style as our Cultivators does with the create growzone button. 
Just with a normal stockpile, that will make it easier to setup where your not using belts or I/O eq. inside a freezer
![image](https://user-images.githubusercontent.com/41029070/106043497-cd66ba80-60de-11eb-8e52-02c239da348f.png)
![image](https://user-images.githubusercontent.com/41029070/106043584-ed967980-60de-11eb-9d34-99aeda3ea3f2.png)

**Comment by Sn1p3rr3c0n** [comment]
@zymex22 should that zone exclude the output cell or just do it for the entire input range?

**Comment by zymex22** [comment]
hmmm depens how hard it would be to do? exclude output would be awesome but if too hard it can include it? =)
