### ISSUE TITLE
Optimize PatchStorage Harmony Patches

### ISSUE THREAD

**Issue by Sn1p3rr3c0n** [zymex22/Project-RimFactory-Revived#392]
While the patches are working fine in most Scenarios the do seem to cause spikes with Increasing Item Counts.

**Affects:**
Players with a lot of items

---
### Report from dizek11

[HugsLib](https://gist.github.com/HugsLibRecordKeeper/2f7103afc7268b040857788d5edf927b)

**Patch_Thing_DrawGUIOverlay**
![Patch_Thing_DrawGUIOverlay](https://user-images.githubusercontent.com/68663281/107085242-79538880-67f8-11eb-8f28-a884c663719e.png)
Average time is Fine. But it is peeking with 65ms

**Patch_ThingWithComps_Draw**
![Patch_ThingWithComps_Draw](https://user-images.githubusercontent.com/68663281/107085445-c8012280-67f8-11eb-9392-d3559e4ef092.png)
Average time is Fine. But it is peeking with 51ms

---
### #359  Patch_ForbidUtility_IsForbidden

![Patch_ForbidUtility_IsForbidden](https://user-images.githubusercontent.com/68663281/107086054-b704e100-67f9-11eb-95e0-247aeae37a34.png)
Again same situation, average times are fine but it dos spike

**Comment by lilwhitemouse** [comment]
Is `IsForbidden` still causing a problem?

**Comment by Sn1p3rr3c0n** [comment]
I would say that depends.
In the image above a 23ms Spike occurs somewhat regularly being caused by 74,277 Calls.

Personally i never had an issue with it as you seem to need crazy amounts of items & possible another Mod to cause such spam calls.

with an average execution time of 0.095ms I'm not sure that we can do anything besides maybe caching.

**Comment by lilwhitemouse** [comment]
That IS cached.

I'm not sure there is much anyone can do with that many calls at once?

Maybe a really sophisticated cache? But that's ...a lot to ask.

**Comment by Sn1p3rr3c0n** [comment]
Appears to be a user error in relation to mod Order

> dizek11: @Sn1p3rr3c0n  i found the fix !
> dizek11: i sorted the mods
