### ISSUE TITLE
 (Bug report) SAL doing bill with not enough materials

### ISSUE THREAD

**Issue by log163** [zymex22/Project-RimFactory-Revived#393]
# Describe the bug
a SAL will sometimes pull items from a stack that doesnt have enough items for the bill and still work on the bill and throw an error:

**To Reproduce**
Reproducibility: ?
1. have a sal set to do a bill
2. have a stack of resourses that is less then what is needed for the bill
3. get error and watch sal do bill anyway

**Expected behavior**
sal shouldnt do bill

**Actual Behavior**
throws error:
Tried to destroy already-destroyed thing Gasnenkj1710079
Verse.Log:Error(String, Boolean)
Verse.Thing:Destroy(DestroyMode)
Verse.ThingWithComps:Destroy(DestroyMode)
Verse.RecipeWorker:ConsumeIngredient(Thing, RecipeDef, Map)
ProjectRimFactory.AutoMachineTool.Building_AutoMachineTool:<FinishWorking>b__40_0(Thing)
System.Collections.Generic.List`1:ForEach(Action`1)
ProjectRimFactory.AutoMachineTool.Building_AutoMachineTool:FinishWorking(Building_AutoMachineTool, List`1&)
ProjectRimFactory.AutoMachineTool.Building_Base`1:FinishWork()
ProjectRimFactory.AutoMachineTool.MapTickManager:Exec(Action)
System.Collections.Generic.List`1:ForEach(Action`1)
ProjectRimFactory.AutoMachineTool.<>c:<MapComponentTick>b__1_1(HashSet`1)
ProjectRimFactory.AutoMachineTool.Option`1:ForEach(Action`1)
ProjectRimFactory.AutoMachineTool.MapTickManager:MapComponentTick()
Verse.MapComponentUtility:MapComponentTick(Map)
Verse.Map:Verse.Map.MapPostTick_Patch1(Map)
Verse.TickManager:Verse.TickManager.DoSingleTick_Patch1(TickManager)
Verse.TickManager:TickManagerUpdate()
Verse.Game:Verse.Game.UpdatePlay_Patch2(Game)
Verse.Root_Play:Verse.Root_Play.Update_Patch1(Root_Play)

the gas item is the item it didnt have enough of, it used 10 instead of 60 and starts work on bill

**Screenshots**

**Rimworld (please complete the following information):**
 - RimWorld Version:
 - PRF Version:
 - Link to gist bug report: 
 - Type:
 - Severity:
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed:
 - Your modlist (if needed): 
 - Do you know what mod conflicts?:

**Additional context**

**Comment by log163** [comment]
its an older log, but the error is in it and the mod list hasn't changed
https://gist.github.com/c560dcfcd677f339ab5ecf56d385b671

**Comment by log163** [comment]
its an older log, but the error is in it and the mod list hasn't changed except updates
https://gist.github.com/c560dcfcd677f339ab5ecf56d385b671

**Comment by Sn1p3rr3c0n** [comment]
@log163 Do you observe this with any bill or just specific ones?
Please give an example of a affected bill (if it is modded please lent me know what mods adds it)

Also please attach a screenshot of the setup

**Comment by log163** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2389180375

ive only seen it happen on 2 bills so far, compressing blue gel into hexagel at the biofuel refinery (alpha animals), and making vilanite at the gas converter (mechalit core), also the main times ive noticed it happening have been when their were more then 1 stack of material but it only pulled from one of them (a stack of 10 and another stack of 60 but only pulling the 10 from the first stack), my DSU was originally in range of the gas converter, i moved it so that the SAL couldn't see into it and could only see what i sent it with the io ports

**Comment by Sn1p3rr3c0n** [comment]
@log163 just to confirm are you are using IO Ports with are maximum Limit set?

**Comment by log163** [comment]
Usually both max and min, yes

**Comment by Sn1p3rr3c0n** [comment]
This is bug seems to be a odd interaction between SAL and IO ports with an Output limit.
Normal **Assemblers are unaffected** its only SAL.

It appears as if the SAL sees the double amount of items on an IO Port with a limit set.
**Example Simple Helmet (needs 40 Steel):**
2x IO Limit at 10 --> 10 * 2(buggy interaction) * 2(ports) = 40 
1x IO Limit at 20 --> 10 * 2(buggy interaction) = 40 
_10 & 11 would work aswell | 10 & 9 would not_


![SAL_IO_Bug](https://user-images.githubusercontent.com/68663281/107846035-b9aa9c00-6de0-11eb-82b3-2bc4ad72413b.PNG)

**Comment by Sn1p3rr3c0n** [comment]
This issue will be resolved with #387 
fix is in b295d0d

**Comment by zymex22** [comment]
closed as it will be solved with: #387
