### ISSUE TITLE
(Request) io port forbid content setting

### ISSUE THREAD

**Issue by log163** [zymex22/Project-RimFactory-Revived#394]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when: my colonists decide to haul the 1 steel I'm outputting from an io port for a factory when they need to build something nearby

**Describe the solution you'd like**
Setting to allow io ports to forbid contents and all factories to gain setting for using forbidden items 

**Describe alternatives you've considered**

**Additional context**

**Comment by zymex22** [comment]
that would be same technique as in IR where macines can "allow using forbidden" and belts did forbid stuff. 
i think we could implement that, as it will forbid colonist from certain parts if needed.
