### ISSUE TITLE
Help! XML error: Duplicate XML node name designatorDropdown in this XML block

### ISSUE THREAD

**Issue by A2Ring** [zymex22/Project-RimFactory-Revived#398]
# Describe the bug
I'm using a lot of mods.
It seems to conflict with either floor mode or bridge mode.
It's inconvenient to open the debug window every time.

**To Reproduce**
Reproducibility: maybe ez?
1. play game.
2. wait.... 
3. finish?

**Expected behavior**
not opend debug log window.
**Actual Behavior**
opend debug log window after first game loading 

**Screenshots**
![21-02-13(토요일)-21시-54분-05초-3628](https://user-images.githubusercontent.com/28779061/107850461-01174380-6e46-11eb-8f9b-63a033f0c3ee.png)

**Rimworld (please complete the following information):**
 - RimWorld Version:1.2.2900
 - PRF Version: 1.2 / 2.5.51
 - Link to gist bug report:  [link](https://gist.github.com/20c8f8ac3b32bce98304aeb9e8392e96)
 - Type: game loading debug messegs
 - Severity: low
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: no.
 - Your modlist (if needed): 
 - Do you know what mod conflicts?: i dont know.
but maybe floor mode or birdge?

**Additional context**

**Comment by AerosAtar** [comment]
Base PRF doesn't touch Paved Tiles... are you using the Materials addon? If not, this is likely nothing to do with PRF.

**Comment by A2Ring** [comment]
materials mod? hum... my mod list
    <activeMods>
        <li>ludeon.rimworld</li>
        <li>ludeon.rimworld.royalty</li>
        <li>destiny.rktm.core</li>
        <li>automatic.startupimpact</li>
        <li>smashphil.neceros.srtsexpanded</li>
        <li>unlimitedhugs.hugslib</li>
        <li>unlimitedhugs.allowtool</li>
        <li>com.yayo.combat3</li>
        <li>erdelf.humanoidalienraces</li>
        <li>alias.degeneralizework</li>
        <li>chjees.androids</li>
        <li>gloomylynx.dragonianrace</li>
        <li>psyche.kemomimihouse</li>
        <li>seioch.kurin.har</li>
        <li>showhair.kv.rw</li>
        <li>solaris.ratkinracemod</li>
        <li>runnelatki.rabbieracemod</li>
        <li>nemonian.my</li>
        <li>rutranickers.nakedkurinreskin</li>
        <li>roolo.almostthere</li>
        <li>xrushha.animaanimals</li>
        <li>fluffy.animaltab</li>
        <li>jaxe.foodrestrictions</li>
        <li>thegoofyone.animalfoodrestrictionintab</li>
        <li>oblitus.animalslogic</li>
        <li>thecodewarrior.armoredfloors</li>
        <li>razor2.3.anotherrimworldmod.autocutblight</li>
        <li>flyingstar.automortarsunofficial</li>
        <li>rf.autodrill</li>
        <li>ben.automaticnightowl</li>
        <li>cnnuclear.tinkersconstruct</li>
        <li>vanillaexpanded.achievements</li>
        <li>vanillaexpanded.vwe</li>
        <li>notooshabby.awesomeinventory</li>
        <li>meltup.beautifuloutdoors</li>
        <li>mlie.bettermessageplacement</li>
        <li>madeline.modmismatchformatter</li>
        <li>mlie.betterrecordstab</li>
        <li>falconne.bwm</li>
        <li>automatic.bionicicons</li>
        <li>chippedchap.blueprinttotalstooltip</li>
        <li>fluffy.blueprints</li>
        <li>sr.bondagebed</li>
        <li>zetrith.carousel</li>
        <li>neceros.ceilinglights</li>
        <li>kapitanoczywisty.changemapedge</li>
        <li>dylan.csl</li>
        <li>thevillageguy.chocolatemilk.1</li>
        <li>mlie.cleaningpriority</li>
        <li>hatti.cleaningarea</li>
        <li>mlie.clothingsorter</li>
        <li>andross.combatenthusiastscollection</li>
        <li>n7huntsman.combatshields</li>
        <li>mlie.combatshieldsscifiaddon</li>
        <li>dubwise.dubsmintmenus</li>
        <li>petetimessix.compacthediffs</li>
        <li>porohkun.concretewalls</li>
        <li>neceros.craftaicore</li>
        <li>dalrae.custommotemaker</li>
        <li>tammybee.cutplantsbeforebuilding</li>
        <li>caesarv6.damageindicators</li>
        <li>unlimitedhugs.defensivepositions</li>
        <li>merthsoft.designatorshapes</li>
        <li>fluffy.desirepaths</li>
        <li>mlie.desynchronized</li>
        <li>latta.fsharp.core</li>
        <li>latta.devl10n</li>
        <li>tikubonn.dontblockdoor</li>
        <li>dracoix.doormat.r12a</li>
        <li>captainmuscles.dropinventory</li>
        <li>dubwise.dubspaintshop</li>
        <li>dubwise.dubsbadhygiene</li>
        <li>avilmask.commonsense</li>
        <li>dubwise.dubsbreakmod</li>
        <li>dubwise.dubsmintminimap</li>
        <li>dubwise.dubsperformanceanalyzer</li>
        <li>dubwise.dubsskylights</li>
        <li>maaxar.dubsskylights.glasslights.patch</li>
        <li>nilchei.dynamicdiplomacy</li>
        <li>jaxxa.enhanceddevelopment.core</li>
        <li>jaxxa.enhanceddevelopment.laserdrill</li>
        <li>jaxxa.enhanceddevelopment.shields</li>
        <li>edb.preparecarefully</li>
        <li>cocaine.electricstonecuttingtable</li>
        <li>uuugggg.everybodygetsone</li>
        <li>wit.expandedroofing</li>
        <li>nanonator102.farmableneutroamine</li>
        <li>nif.toolbox</li>
        <li>nif.architectexpanded.fences</li>
        <li>mlie.electricfencesandfloors</li>
        <li>mlie.fencesandfloors</li>
        <li>mlie.fireextinguisher</li>
        <li>rimworldsoudanzyo.foragekiller</li>
        <li>alex.friendlyfiretweaks</li>
        <li>denethor0.gainskillpassions</li>
        <li>leafzxg.thrumboextension</li>
        <li>amunra.gmc</li>
        <li>dalrae.gloomydeco</li>
        <li>vanillaexpanded.vfecore</li>
        <li>solaris.furniturebase</li>
        <li>jaxxa.ed.embrasures</li>
        <li>tribeagle.gl.embrasures</li>
        <li>albion.goexplore</li>
        <li>chuiu.greenworld</li>
        <li>ancientgammoner.groundtargeter</li>
        <li>hc.animalreskins.complete</li>
        <li>translucency.braininajar</li>
        <li>ogliss.ykara.harvesteverything</li>
        <li>smuffle.harvestorganspostmortem</li>
        <li>velc.hatsdisplayselection</li>
        <li>falconne.heatmap</li>
        <li>notooshabby.homemover</li>
        <li>orion.hospitality</li>
        <li>oblitus.housekeeperassistancecat</li>
        <li>hanabishi.inwallcoolersandvents</li>
        <li>vanya.tools.incidentpersonstat</li>
        <li>jaxe.bubbles</li>
        <li>mlie.inventorytab</li>
        <li>zzz.invisibleconduit</li>
        <li>insertkey.itemlistselector</li>
        <li>codeoptimist.jobsofopportunity</li>
        <li>dhultgren.keepbedownership</li>
        <li>kenney.kenfix</li>
        <li>falconne.labelsonfloor</li>
        <li>mlie.lessarbitrarysurgery</li>
        <li>mlie.lessstupidromanceattempt</li>
        <li>troopersmith1.lifesupport</li>
        <li>avius.locks</li>
        <li>amunra.lc</li>
        <li>zylle.mapdesigner</li>
        <li>unlimitedhugs.mapreroll</li>
        <li>fluffy.medicaltab</li>
        <li>itchyflea.medicaltraining</li>
        <li>notfood.mendandrecycle</li>
        <li>eagle0600.minetoexhaustion</li>
        <li>uuugggg.miningpriority</li>
        <li>haplo.miscellaneous.training</li>
        <li>fluffy.modmanager</li>
        <li>mlie.modcheck</li>
        <li>cnnuclear.modularizationweapon</li>
        <li>cnnuclear.modularizationweaponvwe</li>
        <li>moloy559.moloytraits</li>
        <li>com.github.alandariva.moreplanning</li>
        <li>bichang.moresculpture</li>
        <li>pinochemicali.moretradeships</li>
        <li>palverz.moretraps</li>
        <li>paradox.morevanillaturrets</li>
        <li>hobtook.mortaraccuracy</li>
        <li>doug.nojobauthors</li>
        <li>bar0th.norandomrelations</li>
        <li>zyxabacab.nosympathyforprisoners</li>
        <li>mehni.numbers</li>
        <li>peppsen.pmusic</li>
        <li>fed1splay.pawntargetfix</li>
        <li>thegoofyone.penoxycyline4more</li>
        <li>jp.perfectpathing</li>
        <li>mlie.pickupandhaul</li>
        <li>neceros.plantgrowthsync</li>
        <li>diddily.poweralerts</li>
        <li>neitsa.preparelanding</li>
        <li>mlie.presetfilteredzones</li>
        <li>spesscarp.pressureplate</li>
        <li>abyss.prisonercaptureandmanipulation</li>
        <li>extracting.organs</li>
        <li>neptimus7.progressrenderer</li>
        <li>spdskatr.projectrimfactory</li>
        <li>spdskatr.projectrimfactory.drones</li>
        <li>prf.materials</li>
        <li>longercfloor.proxyheat</li>
        <li>hatti.qualitybuilder</li>
        <li>spoonshortage.rimkea</li>
        <li>firefoxpdm.researchablestatupgrades</li>
        <li>ratys.rtfuse</li>
        <li>tammybee.raiderinfo</li>
        <li>arandomkiwi.raidsforme</li>
        <li>zzz.raincaller</li>
        <li>com.yayo.racequestpawn</li>
        <li>woolstrand.realruins</li>
        <li>neceros.realsilverweight</li>
        <li>twistedpacifist.reasonablecomponents</li>
        <li>jaxe.rimhud</li>
        <li>automatic.recipeicons</li>
        <li>fluffy.relationstab</li>
        <li>jaxe.reorderer</li>
        <li>uuugggg.replacestuff</li>
        <li>vinalx.researchpalforked</li>
        <li>bdew.restraints</li>
        <li>cabbage.rimcities</li>
        <li>arandomkiwi.rimsaves</li>
        <li>kang060302977.rimsaveshkorean</li>
        <li>arandomkiwi.rimthemes</li>
        <li>nephlite.rimthemeskor</li>
        <li>dubwise.rimatomics</li>
        <li>dubwise.rimefeller</li>
        <li>rimsenal.evp</li>
        <li>rimsenal.federation</li>
        <li>rimsenal.feral</li>
        <li>rimsenal.hair</li>
        <li>rimsenal.core</li>
        <li>rimsenal.security</li>
        <li>rimsenal.storyteller</li>
        <li>rimfridge.kv.rw</li>
        <li>lwm.deepstorage</li>
        <li>lat.rimstro</li>
        <li>mlie.roadsoftherim</li>
        <li>roolo.runandgun</li>
        <li>user19990313.runtimegc</li>
        <li>neceros.srtserealismpatch</li>
        <li>mlie.sslightningrod</li>
        <li>brrainz.samespot</li>
        <li>nykot.rpgstyleinventory</li>
        <li>roolo.searchanddestroy</li>
        <li>flashpoint55.selfreloadingtraps</li>
        <li>dninemfive.settlementdescription</li>
        <li>uuugggg.sharetheload</li>
        <li>mlie.shelfrenamer</li>
        <li>frontierdevelopments.shields</li>
        <li>targhetti.showdrafteesweapon</li>
        <li>erdelf.showmoddesignators</li>
        <li>lanilor189.simplehrecycling</li>
        <li>gguake.ui.simplesearchbar</li>
        <li>petetimessix.simplesidearms</li>
        <li>mlie.simplymorebridges</li>
        <li>pinochemicali.skilledstonecutting</li>
        <li>uuugggg.smartmedicine</li>
        <li>dhultgren.smarterconstruction</li>
        <li>weilbyte.snapout</li>
        <li>yoann.somemorejobs</li>
        <li>linkolas.stabilize</li>
        <li>indeed.stackxxl</li>
        <li>uuugggg.stockpileranking</li>
        <li>tmc.armory.assaultrifle.1</li>
        <li>tmcarmory.attachments</li>
        <li>tmc.armory.communitypack</li>
        <li>tmc.armory.smgs.1</li>
        <li>tmc.armory.shotguns.1</li>
        <li>tmc.armory.rf.1</li>
        <li>tmc.armory.sw.1</li>
        <li>tmc.armory.colony.rifle</li>
        <li>mlie.tabsorting</li>
        <li>antaioz.tdiner</li>
        <li>gt.sam.tilledsoil</li>
        <li>guy258.tcaslib</li>
        <li>mrchimick.toomanyareas</li>
        <li>smashphil.dropspot</li>
        <li>carnysenpai.traitraritycolors</li>
        <li>velc.trapdisable</li>
        <li>ryder.turnitonoff</li>
        <li>eatkenny.leafzxg.turretcollection</li>
        <li>marvinkosh.ughyougotme</li>
        <li>com.yayo.ultravanillatheme</li>
        <li>grimm.unlimited</li>
        <li>madarauchiha.undraftaftertucking</li>
        <li>nephlite.orbitaltradecolumn</li>
        <li>oskarpotocki.vanillafactionsexpanded.core</li>
        <li>oskarpotocki.vfe.mechanoid</li>
        <li>charcoalbirb.vfemstonepatch</li>
        <li>vanillaexpanded.vbrewe</li>
        <li>vanillaexpanded.vcef</li>
        <li>vanillaexpanded.vplantse</li>
        <li>vanillaexpanded.vcooke</li>
        <li>oskarpotocki.vanillafactionsexpanded.settlersmodule</li>
        <li>vanillaexpanded.vtexe</li>
        <li>vanillaexpanded.vfefarming</li>
        <li>vanillaexpanded.vfesecurity</li>
        <li>vanillaexpanded.vfeproduction</li>
        <li>vanillaexpanded.vfemedical</li>
        <li>oskarpotocki.vanillafactionsexpanded.medievalmodule</li>
        <li>oskarpotocki.vfe.vikings</li>
        <li>ratys.rtsolarflareshield</li>
        <li>phoenix.vanillasolarsheild</li>
        <li>vanillaexpanded.vweg</li>
        <li>mlie.variousspaceshipchunk</li>
        <li>murmur.walllight</li>
        <li>mlie.wallmountedturrets</li>
        <li>zzz.wallvitalsmonitor</li>
        <li>mlie.weaponssorter</li>
        <li>tammybee.whereismyweapon</li>
        <li>fluffy.worktab</li>
        <li>odeum.wmbp</li>
        <li>flamethrower.velcroboy333</li>
        <li>bob.draggablecornerss</li>
        <li>proxyer.desurgeries.desurgeries</li>
        <li>walkingproblem.wildanimalsex</li>
        <li>dame.activecircuits</li>
        <li>frozensnowfox.encountermapresources</li>
        <li>crlsniper.realisticrooms</li>
        <li>frozensnowfox.filthvanisheswithrainandtime</li>
        <li>frozensnowfox.indoortreefarms</li>
        <li>frozensnowfox.nodefaultshelfstorage</li>
        <li>jangodsoul.simplestorage</li>
        <li>consolidatedtraits.kv.rw</li>
        <li>moretraitslots.kv.rw</li>
        <li>pathavoid.kv.rw</li>
        <li>savestoragesettings.kv.rw</li>
        <li>tradingspot.kv.rw</li>
        <li>kittahkhan.grazeup</li>
        <li>derekbickley.ltocolonygroupsfinal</li>
        <li>vanya.agent.housemaidnukos</li>
        <li>nals.compatiblebody</li>
        <li>nals.compatiblebody2</li>
        <li>nals.customcoordinateoffsets</li>
        <li>nals.customportraits</li>
        <li>nals.dynamicportraits</li>
        <li>asieruso23.srts.planes</li>
        <li>syrchalis.bulletcasings</li>
        <li>syrchalis.individuality</li>
        <li>syrchalis.scarremoval</li>
        <li>syrchalis.setupcamp</li>
        <li>lat.apparelretextuer</li>
        <li>wemd.barbedwire</li>
        <li>wemd.bettercannons</li>
        <li>wemd.expandedfloors</li>
        <li>wemd.soilcontrast</li>
        <li>mlie.xndnocturnalanimals</li>
        <li>com.distman.gastrap</li>
        <li>archie.chemshinemortar</li>
        <li>poet.retexturedgastrapsshells</li>
        <li>quiabo.autodeepdrill</li>
        <li>mlie.sdadvancedpowergeneration</li>
        <li>mlie.sdbridges</li>
        <li>turkler.guns</li>
        <li>jskyn.vanillahairnomore</li>
        <li>jintuzilamian.hairstyle.afumenshairstyles</li>
        <li>ameiro.animehairs</li>
        <li>gloomy.gloomyfacemk2</li>
        <li>gloomy.gloomyhairmk2</li>
        <li>automatic.gradienthair</li>
        <li>kchair.velcroboy333</li>
        <li>amaji.mokan.hair</li>
        <li>qquack.gfap</li>
        <li>lat.veehair</li>
        <li>jintuzilamian.hairstyle.afuwomenshairstyles</li>
        <li>beta.animehair</li>
        <li>cp.chicken.mitchell.hairstyles</li>
        <li>lingluo.lovelyhairstyle</li>
        <li>lingluo.maidproject</li>
        <li>void.weaponry</li>
        <li>factioncontrol.kv.rw</li>
        <li>murmur.thickroofminer</li>
        <li>plantsavercycles.velcroboy333</li>
        <li>rearden.rnh</li>
        <li>zhrocks11.stackablechunks</li>
        <li>aoba.fortress.neolithic</li>
        <li>fyarn.easyspeedup</li>
        <li>dingo.noforcedslowdown</li>
        <li>notooshabby.rocketman</li>
        <li>azomittle.corners</li>
        <li>mlie.runandhide</li>
        <li>destiny.rktm.mod</li>
    </activeMods>

**Comment by AerosAtar** [comment]
While I cannot say with any certainty which mod is causing the error, I _can_ say that it is nothing to do with Rimfactory.

**Comment by A2Ring** [comment]
so there no problem?

**Comment by zymex22** [comment]
This is caused by PRF materials + some other mod trying to set dropdown to paved tiles. not sure what mod does it?
if you have an idea let me know
