### ISSUE TITLE
Mechanites XL Cultivator's Sun Lamp not working

### ISSUE THREAD

**Issue by MyBigFan2** [zymex22/Project-RimFactory-Revived#404]
# Describe the bug
Mechanites XL Cultivator's Sun Lamp not working (doesn't exist?) although the sun lamp is mentioned in the description of the cultivator

**To Reproduce**
Reproducibility: Yes
1. Place it in a closed room with hydroponics 
2. Wait till day

**Expected behavior**
Expected crops to grow and 22x22 space to be lit up from sun lamp in the cultivator

**Actual Behavior**
Crops do not grow and room remains dark

**Screenshots**
![image](https://user-images.githubusercontent.com/27133275/109141158-61887800-7798-11eb-85fa-0234a57e8a1c.png)
(Note left side are Mechanite Cultivators (Sun Lamp) (11x11 Area) which are working normally, on the right side is the Mechanite XL Cultivator (22x22) which isn't lighting up the space around it at all.)

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.2.2900
 - PRF Version: 2.4.9
 - Link to gist bug report: https://gist.github.com/23e103a12e3aa59ef9d70594fe7f885a
 - Type: Description inaccuracies? 
 - Severity: 
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: Yes
 - Your modlist (if needed): 
- Adjustable Trade Ships
- Allow Tool
- ArchitectExpanded - Fences
- Expanded Roofing
- Harmony
- hugslib
- Improved Workbenches
- LetsTrade
- MinifyEverything
- Miscellaneous Core
- Miscellaneous Robots
- Pick Up and Haul
- PRF
- RT Fuse
- RT Power Switch
- RW Autosell
- sd_adv_powergen
- Stack XXL
- Toolbox
- Worktab

 - Do you know what mod conflicts?:

**Additional context**

**Comment by Sn1p3rr3c0n** [comment]
The description needs to be updated.

**Comment by MyBigFan2** [comment]
It should be more detailed now, sorry that I missed something, I don't really do bug reports.

**Comment by Sn1p3rr3c0n** [comment]
@MyBigFan2 there was no additional information required from you.
I merely documented what we need to do to resolve this issue.

_I'm sorry for not making this clear_

**Comment by MyBigFan2** [comment]
Oh, it was a misunderstanding on my part. So just to make sure, the Mechanite XL Cultivator doesn't have sun lamps in it? If not, are there plans for a variant that has one?
