### ISSUE TITLE
Puller ceases to exist when uninstalled for a relocation order, causing pawns to stall

### ISSUE THREAD

**Issue by JulianSkies** [zymex22/Project-RimFactory-Revived#405]
# Describe the bug
Attempted to move a puller, when the pawn uninstalled it the puller instead vanishes. This caused a series of pawns to stall as they attempt to reinstall an object that no longer exists.

**To Reproduce**
Reproducibility: Difficult
1. Have active puller
2. Select to reinstall
3. Pawn attempts to uninstall
4. Puller disappears
5. Check pawn inventory, no puller
6. Pawn is now stalled

**Expected behavior**
Puller gets placed in pawn inventory and then later installed in the requested position

**Actual Behavior**
Puller ceases to exist and pawn stalls.

**Screenshots**

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.2.29
 - PRF Version: Steam version as of 25/02/2021
 - Link to gist bug report: Having local internet difficulties and can't generate the hugslog, so i've uploaded it as .txt
[git message.txt](https://github.com/zymex22/Project-RimFactory-Revived/files/6045540/git.message.txt)

**Comment by lilwhitemouse** [comment]
"Reached max messages limit. Stopping logging to avoid spam."
You may need to reload that game, clear the log, and THEN try uploading it!

**Comment by Sn1p3rr3c0n** [comment]
@JulianSkies I also attempted to reproduce this but had no success.
Can you provide a updated Trace or provide addition hints on how to reproduce this?

**Comment by JulianSkies** [comment]
Unfortunately that save file is long gone due to mounting issues, so can't provide any further information.
I will attempt to provide further information if I ever run into it again

**Comment by zymex22** [comment]
i'll close it for now as no one is able to repro.
if issue popsup for someone else, reopen this and provide more info on subject =)
