### ISSUE TITLE
Godly S.A.L deletes items from some workbenches

### ISSUE THREAD

**Issue by Meatsofa** [zymex22/Project-RimFactory-Revived#407]
The SAL will do a bill at a table, taking time and resources only to produce nothing.
only happens to some recipes, i tested it with:
- medically extract organs from the harvest post mortem mod
- weave plasteel from the sparkling worlds full mod.

weave plasteel works fine with the overclocked SAL MK2 so i dont know why the godly SAL would have this problem..

**Comment by Sn1p3rr3c0n** [comment]
> weave plasteel works fine with the overclocked SAL MK2 so i dont know why the godly SAL would have this problem..
How did you test this? this works fine for me.
![image](https://user-images.githubusercontent.com/68663281/109397454-e9a48400-7936-11eb-9821-00ce9232bcfd.png)

in any case please attach a HugsLib Trace and provide a clear description of the issue.

**Comment by Sn1p3rr3c0n** [comment]
@Meatsofa if you still face this issue please provide the requested feedback.

**Comment by Sn1p3rr3c0n** [comment]
Issue Can't be reproduced, Reporter is unresponsive. --> Closing
