### ISSUE TITLE
 (Bug report) Mini Workshop Helper Station Zone Expanding

### ISSUE THREAD

**Issue by WinteryCart** [zymex22/Project-RimFactory-Revived#415]
# Describe the bug
I've just got this mod and I found this glitch pretty easily so I'm not sure if this has been reported yet. I noticed that you can expand the radius that the Workshop helper does jobs in by going to "manage areas" and inverting the Drone's allowed area. By doing this you can have the drones do work everywhere but the desired location but this can be abused pretty easily. It does cause lag which can be a pretty big deterrent but I still think this can be impactful enough to be patched. I'm not sure if this is a result of my mods but after removing most of them I wasn't able to find any mods that are impacting this.
**To Reproduce**
Reproducibility: ?
1. place down the mini-workshop helper
2.  go to the "Manage Areas" menu
3.  click "Invert area" on the Drone's allowed area
4. Drones will now do jobs everywhere but the original set radius

**Expected behavior**
drones clean and haul in the set radius
**Actual Behavior**
A clear and concise description of what actually happens.
drones have a much larger radius to do jobs, effectively increasing their effectiveness.

**Screenshots**

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.2.2900
 - PRF Version:
 - Link to gist bug report: 
 - Type:
 - Severity: Medium
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: not sure
 - Your modlist (if needed): 
 - Do you know what mod conflicts?: none

**Additional context**

**Comment by Sn1p3rr3c0n** [comment]
@WinteryCart Please a Hugs Lib Trace or your modlist.
I'm relevantly certain that you normally can't invert it

**Comment by Sn1p3rr3c0n** [comment]
wow apparently there was a rimwold base game update that:
- Made the previously invisible Zones Visible
- Gave the Player the right to edit them
