### ISSUE TITLE
Industrial Stoneworks cannot place directly to puller

### ISSUE THREAD

**Issue by lilwhitemouse** [zymex22/Project-RimFactory-Revived#417]
Any automated building should be able to place directly to a puller (and probably any other building):

![Example Setup](https://user-images.githubusercontent.com/45579454/111851993-c775a480-88eb-11eb-8c81-a6b4bfd926ab.png)

Not sure which part needs fixing here
* Industrial Stoneworks may not be using PlaceThingUtility
* PlaceThingUtility might have a bug
* Pullers might not be set up to accept items from other buildings (check here first)

**Comment by lilwhitemouse** [comment]
Looks like the puller cannot accept items from anyone.  I'll see if I can fix that!

**Comment by zymex22** [comment]
meh....
i would not say it should be able to place directly on a puller, it should be able to place on a belt or on a single tile/stockpile that a puller can pick from.
(it can even output directly into a crate instead, and puller can pick from that)

never been intention to go directly in a puller.
as pullers not take it out of the machines "inventory" in the first place, like in factorio.

i would say not fix? unless this is gamebreaking in some mechanic way.... =)

**Comment by lilwhitemouse** [comment]
I think it's one of those "allow the player to do what they want...." and it shouldn't be hard to implement at all. I hope.
