### ISSUE TITLE
Auto Description (Request)

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#436]
As talked about on steam i think we should implement that system from miners posible yield output to work on other buildings too, to show usefull informations in descriptions...

This should help players and make less work on XML/documentation side, as it will "auto generate" instead.

i think following machines could use it:

### Cultivators
Showing:
Drones: 2
WorkArea: 11x11
Jobtypes: Growing + hauling
Worktime: fulltime
Skill lv.: 15
(as they already do)

### Drone stations
showing
Drones:
...
...
?? not sure need to figure? guess not duplicate from info itab though?

### Assemblers
Skill level
Speed factor
Heat produced
some sort of info on possible overclock?
- like is can boost range
- can boost speed

### SAL
Probably just same as assemblers

### other note?
we could make a universal system so machines get more info in general so its easier to find around.
im thinking
something like this layout:

(Orange/yellow **header**) **PRF Description**
- Research needed
- CATEGORY SYSTEM**? 
- Heat produced
- Can overclock

(Orange/yellow **Subheader**) **Other stats**
- Other specific stats to machine

** should we make some sort of category system/tag/label like: cultivators, miners, assemblers, and such. so ppl know what "line" its part of

**Comment by Sn1p3rr3c0n** [comment]
Generated portions marked with green 
![image](https://user-images.githubusercontent.com/68663281/170949256-fb01f936-8270-4f03-ad38-40e2ad89c4ef.png)
![image](https://user-images.githubusercontent.com/68663281/170949806-5e4d3027-39fa-488c-9c4e-39c4517562cc.png)
![image](https://user-images.githubusercontent.com/68663281/170949930-41f97001-224d-40c2-96ba-fb9f6db83c07.png)
![image](https://user-images.githubusercontent.com/68663281/170953485-5bdd2b2a-6906-4631-90ad-f0fd7c0cc137.png)
![image](https://user-images.githubusercontent.com/68663281/170953559-938f9f49-b625-4984-a593-b84b0533ff2c.png)
![image](https://user-images.githubusercontent.com/68663281/170953796-427a7cbd-c3bf-47e4-b352-72f01b7f29ad.png)

Todo / fix:

- [ ] Cultivators
- [ ] Refuel type Drone Stations
- [ ] ...

**Comment by Sn1p3rr3c0n** [comment]
![image](https://user-images.githubusercontent.com/68663281/171989773-f3d3a901-3921-45df-88b6-d5334dc78dd4.png)

@zymex22 should the Work area for Cultivators be displayed like
`Workarea: 22x22` (current manual info)
or
`Range: 11`
_Note that 22x22 is incorrect. it is 23x23 minus the center_

**Comment by Sn1p3rr3c0n** [comment]
![image](https://user-images.githubusercontent.com/68663281/171991322-6ee4ec7b-189b-4825-b145-0f299f3c699b.png)

**Comment by Sn1p3rr3c0n** [comment]
**TODO:**
- [ ] Styling (open for feedback)
