### ISSUE TITLE
Meat Grinder infinite searching (Bug report)

### ISSUE THREAD

**Issue by Lucas559-noob** [zymex22/Project-RimFactory-Revived#440]
# Describe the bug
I have a meat grinder, a dead animal, a bill and it don't do nothing, keep searching.

**To Reproduce**
Reproducibility: maybe
1. have a meat grinder
2. have a dead animal in collect zone(white zone)
3. done

**Expected behavior**
Transform the animal into raw food.

**Actual Behavior**
Can't find the animal.

**Screenshots**
![screenshot6](https://user-images.githubusercontent.com/54007604/115981029-4e5f1200-a567-11eb-98dd-411e0cb05fb8.png)

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.2.2900
 - PRF Version: 2.5.6

**Comment by Sn1p3rr3c0n** [comment]
@Lucas559-noob
Please verify:
- That the corpse is not rotting _(kinda looks like it)_
- The Corpse is allowed by the Bill

**Comment by Lucas559-noob** [comment]
> @Lucas559-noob
> Please verify:
> 
> * That the corpse is not rotting _(kinda looks like it)_
> * The Corpse is allowed by the Bill

yeah I think it was rotting, because it was cremate some minutes later
the settings on Bill was the default, so all things enabled(human and insect disabled)

**Comment by Sn1p3rr3c0n** [comment]
You can't butcher a rotting corpse.
Working as expected.
