### ISSUE TITLE
Patch_Building_Storage_Accepts scales badly (even without PRF Buildings)

### ISSUE THREAD

**Issue by Sn1p3rr3c0n** [zymex22/Project-RimFactory-Revived#449]
# Describe the bug

**To Reproduce**
Have many Pawns And or Haul Animals
Also place many `Building_Storage` Buildings.
![unknown](https://user-images.githubusercontent.com/68663281/118678842-a94df700-b7fd-11eb-83b3-9214aff182b9.png)
https://github.com/zymex22/Project-RimFactory-Revived/blob/master/Source/ProjectRimFactory/Common/HarmonyPatches/PatchStorage.cs#L32

Replacing `PatchStorageUtil.Get<IForbidPawnInputItem>(__instance.Map, __instance.Position)` with `(__instance as IForbidPawnInputItem)` seems to significantly improve performance.

Result after the change:
![unknown_Fixed](https://user-images.githubusercontent.com/68663281/118679898-91c33e00-b7fe-11eb-9722-bd287dbad2e2.png)

**Comment by mwcrow** [comment]
Hi. I understand Lite is just a side project and not up to speed with core, but could we at least get a release with this patch only?
