### ISSUE TITLE
Description Update Industrial Stoneworks

### ISSUE THREAD

**Issue by Sn1p3rr3c0n** [zymex22/Project-RimFactory-Revived#451]
The description of the `Industrial Stoneworks` needs to Exclude the Reference to Art.
Also the Art skill shall be removed as it serves no purpose.
https://github.com/zymex22/Project-RimFactory-Revived/blob/master/Defs/ThingDefs_Buildings/Buildings_Industry.xml#L47

**Comment by zymex22** [comment]
fixed with above
