### ISSUE TITLE
 (Bug report) Belt Splitters do not correctly load the Output Link Setting if it links to a Splitter

### ISSUE THREAD

**Issue by Sn1p3rr3c0n** [zymex22/Project-RimFactory-Revived#452]
> Reported by `ChrisF0001` on Steam. Confirmed by me

# Describe the bug
If a Splitter Outputs to another Splitter then the `Active` Setting of the Output gets set to `false` regardless of the Saved Value.

**To Reproduce**
Reproducibility: easy
1. Place a Splitter leading into another splitter
2. Activate the Output of the First Splitter
3. Save the Game
4. Load the Game
5. Observe that the setting is set to False.

**Expected behavior**
If a Link is Saved as active it should load as active 

**Actual Behavior**
The Saved Value gets Ignored.
This can be verified by checking the Savefile.

**Screenshots**
Before & after Saving
![image](https://user-images.githubusercontent.com/68663281/118971205-6ad84980-b96f-11eb-9997-4e55959c587b.png)
After Loading
![image](https://user-images.githubusercontent.com/68663281/118971307-8cd1cc00-b96f-11eb-8fcb-a6940342067a.png)

**Comment by lilwhitemouse** [comment]
I suspect this is a result of the change to allow splitters to input from multiple directions at the same time.  I'll take a look.

**Comment by lilwhitemouse** [comment]
Okay, I think it's because of the way Splitters Link() when they Spawn() - they explicitly deactivate incoming links, and the logic isn't set up to handle that scenario.  I'll figure out how to make it work; it may need nothing more than removing that.
