### ISSUE TITLE
 Duplicate defNames (Bug report)

### ISSUE THREAD

**Issue by DrZhivago1** [zymex22/Project-RimFactory-Revived#454]
# Describe the bug
Research defNames are duplicates of Resource defNames. This causes an incompatibility with DocUniversalResources. All references of any resource defName are replaced with a unique one. Since Research and Resource names are the same, it also replaces Research defNames.

**Solution**
Include some temporary code that finds and replaces all current Research defNames with a new unique name for backwards compatibility. Rename all current research defs with the same unique name.

**Comment by Sn1p3rr3c0n** [comment]
This only seems to affect PRF Materials. (https://github.com/zymex22/Project-RimFactory-Revived-Materials)

A simple prefix or postfix might be the best solution to prevent this,
`PRF_Research_....` or `PRF_..._Reserch`
personally i think a prefix looks better. 

if we do that and this replacement code works, we should consider to add the same naming convention to **all** PRF research. (Core, Drones, Insanity)

any thoughts @zymex22 @DrZhivago1 @lilwhitemouse ?

**Comment by DrZhivago1** [comment]
Prefix seems good to me.

That's probably also correct, at least I only noticed it while working with PRF Materials.
