### ISSUE TITLE
Adding new text for PRF

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#473]
Shipidge have provided us with some new descriptions ill apply into PRF soonish.

I need to figure if we should change our system for info in descriptions before or just apply as is now and change later?
#436 Auto Description (Request) 

i have gotten all new descriptions / names in a word file so ill need to go over all of them anyways and convert to XML.

Text are here if anyone else wanna see comment on them:
[RIMFACTORY_REVIVED_NEW_DESCRIPTIONS (1).docx](https://github.com/zymex22/Project-RimFactory-Revived/files/6874132/RIMFACTORY_REVIVED_NEW_DESCRIPTIONS.1.docx)

**Comment by zymex22** [comment]
See https://github.com/zymex22/Project-RimFactory-Revived/pull/479#pullrequestreview-719813815
Commitments from @InsanityPrelude 

these overlap with our latest upload from Shipidge https://github.com/zymex22/Project-RimFactory-Revived/commit/92a144035c51edf93495f91e7c615d8908e370dd
but it has some extra he didnt. so we should about cover it all i guess.
but it will need some manual resolving.

i got files from sihpi in a word attached above and also this one:
[RIMFACTORY_REVIVED_LETTERS (2).docx](https://github.com/zymex22/Project-RimFactory-Revived/files/6914640/RIMFACTORY_REVIVED_LETTERS.2.docx)

He will post last few overhaul of Dicovered letter within a few days.

One last thing what could need a remake would be our Scenario to complete this transformation.
but it would prob. need a new story and start setup.

@lilwhitemouse i added you here too as you seemed to take part of conversation with @InsanityPrelude
just so we are all on same page :P
Shipigde are not on Githhub but can be contacted on our discord or PM there =)

**Comment by zymex22** [comment]
Okay we hit a wall with this project and PR #479 

Problem being both @InsanityPrelude and Shipidge was working on updating text at the same time, one in just word and manual import, and other on a old fork.
Those then overlapped and conflicted, some text are simple just been updated twice in 2 different versions.
and some are fine only touched by one of them.

to make things more confusing dear @lilwhitemouse have also started to resolve and fix conflicts and some text he wanted to change.

I'm not sure what best path forward is now?
but if i have to do it, it would just be manually look at that PR and put into our Master one by one, where fit and which one are best. old, new or new by shipidge.

(i have no idea how to resolve Conflicts in that PR in a good way, there might be a better way than just copy over to master one by one, as i would do xD)
@Sn1p3rr3c0n @lilwhitemouse @InsanityPrelude

**Comment by InsanityPrelude** [comment]
I'm not even sure how the hell I got an old fork anyway, which is what pisses me off.  I literally created my fork and then immediately began working on it, so it _should_ have been the latest version.

I'm not particularly arsed, either way, if you want to just include all of @Sn1p3rr3c0n changes, then have LWM stuff on top.  If I need to I can honestly just run over it all again and see if there's anything missed by either of them.  The fixes don't have to be _my_ fixes, in particular, it's just that it was all in a pretty bad shape.  Hence why three different people have all decided that something needs to be done about it lol.

**Comment by zymex22** [comment]
@InsanityPrelude i think either i just uploaded master update while your PR was open or else i just uploaded right before yours came in, but they was scary close, so much that i thought it was same person or something as i literally just spend 3 hours pasting thins from word document into master xD

**Comment by Sn1p3rr3c0n** [comment]
Closing this issue as the changes from `Shipidge` and @InsanityPrelude have been merged.
