### ISSUE TITLE
 (Bug report) JobDriver Exception when placing items in digi/crate storage. Items don't count within the stockpile.

### ISSUE THREAD

**Issue by ConTacMight** [zymex22/Project-RimFactory-Revived#476]
# Describe the bug
JobDriver Exception when placing items in digi/crate storage. Items don't count within the stockpile.

**To Reproduce**
Reproducibility: Good
1. Spawn Into Quickstart World.
2. Spawn either storage crate or digi. 
3. Haul to storage.
4. Error appears.

**Expected behavior**
Items are placed into storage and counted on the item list.

**Actual Behavior**
Items are placed into storage, the items show up within the storage menu but do not count in the item list and an exception is thrown. 

**Screenshots**
![image](https://user-images.githubusercontent.com/69330350/127261068-77e495f6-f74d-4d4b-a5da-06d761cfd4d0.png)
![image](https://user-images.githubusercontent.com/69330350/127261082-19e3c70f-1529-4de0-bcc9-32c9795db578.png)
![image](https://user-images.githubusercontent.com/69330350/127261218-b46ce373-3d4c-4aed-829b-965ac3255468.png)

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.2.3005
 - PRF Version: 2.6.2
 - Link to gist bug report: https://gist.github.com/HugsLibRecordKeeper/613f46971a65de1fa3176aab1df190c6
 - Type: Mod Conflict/ Exception
 - Severity: 
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed:
 - Your modlist (if needed): 
 - Do you know what mod conflicts?:
Combat Extended 1.2.3.7-1.2.4.7 
These versions cause the issue.
**Additional context**

**Comment by Sn1p3rr3c0n** [comment]
The Log clearly indicates that this issue occurred with an incompatible version of CE.
see: https://gist.github.com/HugsLibRecordKeeper/613f46971a65de1fa3176aab1df190c6#file-output_log-txt-L2721

The CE Devs fixed this issue with their 1.3 release.
Therefor this issue is closed
