### ISSUE TITLE
[Bug] The™ Food Poisoning™ Issue™

### ISSUE THREAD

**Issue by MadaraUchiha** [zymex22/Project-RimFactory-Revived#48]
# The bug
T1 automatic cooker has a high food poisoning chance.

Steps:
1. Build a T1 cooker in a sterile room
2. Have it cook a few meals

Expected:
- Minimal food poisoning chance

Actual:
- A large portion of the meals are poisoned

# Research

So I've looked into the code, and stepped with the debugger -- These are my findings:
1. You create a dummy pawn with the skills and background you want to take on the work.
2. You place that pawn on the same tile as the machine
3. The vanilla code determining the food poison chance has this check in it:
    ```cs
    Room room = worker.GetRoom(RegionType.Set_Passable);
    if (Rand.Chance((room != null) ? room.GetStat(RoomStatDefOf.FoodPoisonChance) : RoomStatDefOf.FoodPoisonChance.roomlessScore))
    ```
4. Because the worker is placed "inside" the machine, `room` *always* returns `null` (pawn is standing on something that's not passable). Which means that no matter how clean the environment around the machine is, there's no effect on food poisoning. The food poison chance is always set to 0.02.
5. With 13 pawns eating 2 meals a day, on average, 1 pawn every 2 days would get food poisoned, which is consistent with playtesting.

# Proposed Solution
A patch to this line `Room room = worker.GetRoom(RegionType.Set_Passable);` to detect whether `worker` is a dummy worker, and call the machine's `GetRoom` instead.

This can be implemented by adding a Comp on `PRFSlavePawn` to keep track of the machine that spawned it.

~This can be done in addition to the current patch which makes the T3 bypass the chance completely, as even without this bug at cooker level 10 there is a 0.01% chance of food poisoning (which, as we know, infects the whole stack)~

This can be done by selecting the billGiver's room instead of the pawn's.

I am still playing around with it, may put up a PR, but thought to write my findings if I don't get the chance.

**Comment by lilwhitemouse** [comment]
The patch for pawn skill check only applies to the T3 cooker; the T1 cooker WILL have a food poisoning chance.  You feel that chance is too high?

It looks like the T3 cooker will also still cause food poisoning?

**Comment by MadaraUchiha** [comment]
My issue is that no matter what you do, the T1 cooker will always have the same food poisoning chance, 2%, which is very high.

The T3 cooker will not have food poisoning, as there is a patch to vanilla code to skip the poison check altogether (for both the room cleanliness and the cook's skill) when the billGiver is the spacer cooker.

Also, the difference between the T1 cooker and the T3 cooker in terms of research needed is vast. I'd feel better if there was a T2 cooker somewhere in the middle that you can upgrade to to reduce the chance, making the T1 into an early game option. But this theoretical T2 cooker would suffer from the same problem as the T1 cooker.

More findings:
- The cooker creates a region and a room for itself. I'm not sure why. 
- Asking for the cooker's room with `GetRoom(RegionType.Set_All)` results in a 3x3 room on the cooker which has nothing in it listed (not even the cooker itself!) 
![image](https://user-images.githubusercontent.com/1188951/82095450-b2e2e180-9707-11ea-9c08-dd2a4e259bdc.png)

**Comment by lilwhitemouse** [comment]
Basically it's not a real room :p

**Comment by MadaraUchiha** [comment]
Apparently, because it is impassable, it cannot be a part of any room. It is considered a wall.

**Comment by MadaraUchiha** [comment]
So I've looked at what other mods do, and apparently the practice is to use the "interaction spot" of the building in the case it's impassable (for example: for the Nutrient Paste Dispenser it would be the tile in front of it where colonist get food).

I've used the billGiver's OutputComp.CurrentCell, and it works!

```cs
public static Room GetRoomOfPawnOrGiver(Pawn pawn, RegionType allowedRegionTypes, IBillGiver billGiver)
{
    if (pawn.kindDef == PRFDefOf.PRFSlavePawn && billGiver is Building_SimpleAssembler assembler)
    {
        return RegionAndRoomQuery.RoomAt(assembler.OutputComp.CurrentCell, billGiver.Map, RegionType.Set_Passable);
    }
    return pawn.GetRoom(allowedRegionTypes);
}
```

I'll wrap it into a PR soon

**Comment by lilwhitemouse** [comment]
It may make sense (in universe, as it were) that there's no risk of food poisoning from dirty room - it should (in theory) be a sealed unit, and the only risk should come from the Pawn running it.

**Comment by MadaraUchiha** [comment]
@lilwhitemouse Supposedly, the T1 cooker is not an airtight sterile machine, that's what the spacer T3 cooker is.

**Comment by zymex22** [comment]
@MadaraUchiha added you on steam feel free to accept or join our discord abit easier to talk about things =)
