### ISSUE TITLE
Steel keeps getting forbidden by the digital storage unit (Bug report)

### ISSUE THREAD

**Issue by godspeedfunnyman** [zymex22/Project-RimFactory-Revived#480]
# Describe the bug
Steel keeps getting forbidden by the digital storage unit for some reason, I just have shit tons of steel and that could be the problem(?)
When you try to unforbid it, it works but it then forbids it back
**To Reproduce**
Reproducibility: Unknown, I just have 450k of steel

**Expected behavior**
Steel not being forbidden by the storage unit
**Actual Behavior**
Steel being forbidden for some reason

**Screenshots**

https://user-images.githubusercontent.com/79808856/127764798-d1afc76a-cb73-4b3c-ae77-ac359de79480.mp4

**Rimworld (please complete the following information):**
 - RimWorld Version:1.3.3072 (64 bit)
 - PRF Version: Update: 30 Jul @ 4:48pm (Latest one)
 - Link to gist bug report: ?
 - Type: ?
 - Severity: Low
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: Tested the save with only PRF, game got fucked but I can unforbid stuff without it being forbidden again
 - Your modlist (if needed): 
[modlist.txt](https://github.com/zymex22/Project-RimFactory-Revived/files/6912386/modlist.txt)
 
 - Do you know what mod conflicts?: No

**Comment by Sn1p3rr3c0n** [comment]
Do you have any linked IO Ports where:
- They output the item that gets forbidden (in this case steel)?
- are the setup to forbid the Output?
- is a minimum / maximum limit set?

> but I can unforbid stuff without it being forbidden again

just to confirm dos this apply with both setups (eg with your full mod list) ?

---

while i can reproduce this issue to some extend it never reaches such a extend.
_although this could simply be a matter of time._

**Comment by godspeedfunnyman** [comment]
> Do you have any linked IO Ports where:
> 
> * They output the item that gets forbidden (in this case steel)?
> * are the setup to forbid the Output?
> * is a minimum / maximum limit set?

Nope, I don't have any IO Ports linked to it actually

>>but I can unforbid stuff without it being forbidden again

>just to confirm dos this apply with both setups (eg with your full mod list) ?

I can only unforbid them after removing every mod.

**Comment by Sn1p3rr3c0n** [comment]
so unless you remove all other mods you can't unforbid any items.

in that case this is likely caused by a mod conflict.
Please attach a HugsLib Log (link)
Can you reproduce the issue in a fresh save?
what about replacing the DSU with a new one. dos the issue still occur?

**Comment by godspeedfunnyman** [comment]
> what about replacing the DSU with a new one. dos the issue still occur?

Did this first and it worked normally, could it be because I placed the DSU in an old version of this mod then updated to the newest version? I did have a bug where I had no items appear on the Items tab after updating the game then updated the mod, so there's that I guess
(second DSU didn't have this happen to it, it was placed after the mod was updated)

**Comment by godspeedfunnyman** [comment]
OH could've this been caused by Industrial Rollers? since they forbid everything on the rollers and can sometimes get forbidden items in stockpiles

**Comment by Sn1p3rr3c0n** [comment]
This issue is ether caused by a non reproducible update issue or potentially IR.
therefor i will **close** this issue.

---

a96a44755afbcf19b7485c61a6646800fc40a3df fixed the only way i could reproduce this kind of behavior.
but according to @godspeedfunnyman this issue is a separate one as no IO ports are in use.

---

on a side note @godspeedfunnyman there should be no reason to use IR with this mod.
we add our own conveners that should be better then the ones added by IR

**Comment by godspeedfunnyman** [comment]
> on a side note @godspeedfunnyman there should be no reason to use IR with this mod.
> we add our own conveners that should be better then the ones added by IR

Hah yeah I should replace them, although I had IR before I added the mod and I couldn't bother replacing my setup
