### ISSUE TITLE
Duplicate translation key

### ISSUE THREAD

**Issue by brustmopf** [zymex22/Project-RimFactory-Revived#495]
The following translation key is duplicated (same file a few lines below):

https://github.com/zymex22/Project-RimFactory-Revived/blob/846bae44ad63c9402084811a32c8d6be8d44b12f/Languages/English/Keyed/AllKeyed_AutoMachineTool.xml#L111

Not a big issue, but quick to fix

**Comment by Sn1p3rr3c0n** [comment]
@zymex22 i believe the first key is currently in use.
![image](https://user-images.githubusercontent.com/68663281/131339796-292b7de6-b804-41d0-9b1a-7b86279cd12a.png)

so the question is what key shall we use going forward?
it might it be even better to ask `Shipidge` or @InsanityPrelude to take a look at the language files as a whole, as i don't think either one of them changed anything about them.

what do you think?

**Comment by InsanityPrelude** [comment]
Reference #496 

I went and gave a quick pass (three hours, dammit, I forgot to rebase!) pass over most of the translation keys to see about standardizing/updating the grammar.  I looked at the duplicate keys and decided to remove the second set because it wouldn't do anything.

**Comment by Sn1p3rr3c0n** [comment]
resolved with https://github.com/zymex22/Project-RimFactory-Revived/pull/496
