### ISSUE TITLE
 (Bug report)

### ISSUE THREAD

**Issue by AndrewTru** [zymex22/Project-RimFactory-Revived#502]
# Describe the bug

**To Reproduce**
Reproducibility: easy
1. boot up rim world
2. go to the mods window
3. version checker finds 2.6.1, expects 2.6.2

**Expected behavior**
Mod is up to date and ready to play

**Actual Behavior**
update can't be found.

**Screenshots**
![Update_maybe](https://user-images.githubusercontent.com/26558556/132862227-428f733a-b691-4ff1-bace-6952fe68578b.png)

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.3
 - PRF Version: 2.6.1 installed, shows a 1.6.2 update
 - Link to gist bug report: ?
 - Type: update issue
 - Severity: minor.

**Comment by Sn1p3rr3c0n** [comment]
not a bug.
the mod is ready to play & and the update is here on GitHub. (master branch)
_the steam version will be updated when @zymex22 finds time for it_
