### ISSUE TITLE
Conveyors and machines not able to place (Bug report)

### ISSUE THREAD

**Issue by Jacbo1** [zymex22/Project-RimFactory-Revived#504]
Switched to my old laptop to get my new one fixed today and RimFactory is having issues. Items can only be put into an I/O port once before it breaks for that port and conveyors will build up starting from the end with "Placing [pending placement 0]" and new items get deleted if they move onto it. Machines will not be able to place items onto conveyor belts or into I/O ports after this.
It hasn't done this on my good laptop. The save is also continued from my good laptop (from steam cloud).
![image](https://user-images.githubusercontent.com/86734639/133002610-e2b36f25-9b6c-455a-88d5-c62e1d89b236.png)

 - RimWorld Version: 1.2.3005 (64-bit)
 - PRF Version: Workshop version as of 9/12/2021 (page says last updated Aug 4 @ 6:00pm)
 - Severity: Makes the mod fairly unusable without another mod such as Industrial Rollers using their conveyor belts and pullers/pushers to insert into the I/O ports. Those belts do not insert into ports, only the pullers/pushers do.
 

**Modlist**
 - Does this problem exist if only prf is installed: Yes (unable to remove Combat Extended mid-game without the screen going gray with fog of war)
 - Your modlist (if needed):
1. Harmony
2. Core
3. Combat Extended
4. Project RimFactory Revived
5. Project RimFactory - Drones
6. Project RimFactory - Insanity

Error upon starting game (there may be errors from mods being removed mid-save): https://gist.github.com/Jacbo1/eb0c3190e0aad2105a34ff57e97de645
Error upon loading (there may be errors from mods being removed mid-save): https://gist.github.com/Jacbo1/d797808c4bb33a7f41e33cf83a1605f5

**Comment by Sn1p3rr3c0n** [comment]
which version of CE are you using? 
the most recent steam version **for 1.2** is incompatible with PRF. (v1.2.3.6 should be compatible)

if the above is not the cause of your issue please reproduce the error and then post a Hugs Lib Log

**Comment by Jacbo1** [comment]
Thank you it was CE v1.2.3.8. Switching to v1.2.3.6 fixed it.
