### ISSUE TITLE
IO Port teleporting items between worlds

### ISSUE THREAD

**Issue by AmCh-Q** [zymex22/Project-RimFactory-Revived#505]
(Not sure if this count as a bug or feature request, but I can't find other places to discuss this so here I am.)

I noticed that the IO ports can be used to teleport items between maps in a semi-hacky way, which is very useful when playing on multiple bases or with mods like Z-Levels or Pocket Dimensions.

The current way it can be done is as follows:
(1) Build a Digital Storage Unit (DSU) and an IOPort on the same map, config the IOPort to bound to the DSU;
(2) Uninstall the IOPort and reinstall it on another map.

However, it often works but does not always work, for reasons such as the Thing being teleported would be marked with a Map different from the actual map it is being placed in, or when map sizes differ so items might get registered/deregistered in a cell that doesn't exist (is out of bounds).

Some solutions I have:
(0) (The obvious solution) Ignore it; it's low priority because this won't ever be of concern if player never tries to teleport items between maps.
(1) (The simple solution) Completely patch(ban) it by checking if the IOPort and DSU are on the same map before sending items, no items can be teleported between maps;
(2) Make this an actual feature, I've already done this in my local game with code changes in only two places (if you are interested I can submit a PR for review):
(2.1) In GetGizmos() of Building_StorageUnitIOPort.cs , search all maps (instead of just the current map) for DSU to bound to, this allows IOPorts to bound to DSU from different maps without the reinstalling hacks.
(2.2) In RegisterNewItem(Thing newItem) of Building_MassStorageUnit.cs , check if newItem.Map == currentMap, and if not fix newItem, this fixes the issues I mentioned.

**Comment by Sn1p3rr3c0n** [comment]
This is a bug and i can also confirm it.
we should be able to fix that by checking if the link is still valid in the `SpawnSetup`.

Cross map Logistics is a separate topic. i think i might create a issue for later today
