### ISSUE TITLE
Digital storage unit causing lag

### ISSUE THREAD

**Issue by Silfalion** [zymex22/Project-RimFactory-Revived#53]
Lags caused by using digital storage units filled at a high capacity. Made sure of it after deleting the mod and putting it back in.

Edit: deleted the the storage unit one by one and the game started running as butter the moment the last one was deleted.

**Comment by zymex22** [comment]
how many did you had?
did you extend maximum limit?

**Comment by Silfalion** [comment]
Have currently 6 units.

Tried to extend the storage limit but the problem remains.

**Comment by zymex22** [comment]
limit should be left on default unless you have a very good system, over 1k items in a dsu have been known to cause lag.

below default 768 stack should not cause lag on a normal setup unless overdoing it, i dont think 6 units should be overdoing it.

do you have stack mod installed?

**Comment by Silfalion** [comment]
The lag happened even with the default limit(768) and no stack mod installed. 

So maybe I should lower the limit and increase the number of DSU’s as you said.

**Comment by Silfalion** [comment]
Any idea on a fix for it?

**Comment by zymex22** [comment]
I havent heard other with similar problem after we updated DSU but, i would suggest when playing with mods like PRF that you get a stacking mod like ogre stacks or stack xxl.
 that would take alot less stacks, prf makes too many resources to be in vanilla stacks.

**Comment by Silfalion** [comment]
So you mean I should use custom stacks from other mods instead of DSU or in conjunction with it?

**Comment by Silfalion** [comment]
Good news, I think I may not have enabled the limit option earlier, I did now and put it to 149, now everything is smooth, didnt test it for 768.

Thanks a lot for your help.
