### ISSUE TITLE
 (Bug report) Can't see the content of the Digital Storage Unit

### ISSUE THREAD

**Issue by Ahima86** [zymex22/Project-RimFactory-Revived#534]
# Describe the bug
When i click on the Digital Storage Unit and click the item button i can see there is stack on it but can't see what is in. (screen 1)

Also when i try to open option during Digital Storage Unit is selected the option panel is like an overlay and display nothing.(screen 2)

If i click on reorganize button on the DSU and after open item panel the information alerte moove frpm the top of the screen IN the item panel of the DSU but only if there are something IN the DSU.(screen 3)

**To Reproduce**
Reproducibility: Yes
1. fill something on the DSU
2. open the item panel of the DSU

**Expected behavior**
I expected to see the content of the DSU when i click on the item button on it.

**Actual Behavior**
I just see the number of stack in the DSU but nothing else.

**Screenshots**
[screen](https://imgur.com/a/8SdcOcU)

**Rimworld (please complete the following information):**
 - RimWorld Version:13.3066 (64 bit)
 - Harmony version : Lib v2.1.1.0, Mod v1.1.1.0
 - PRF Version: 2.6.3
 - Link to gist bug report: I don't have bug report
 - Type: display
 - Severity: Hard (can't use the DSU)
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: YES (screen 4), and its worst, police problem also (screen 4)
 - Your modlist (if needed): [mod list](https://pastebin.com/1wMSALaH)
 - Do you know what mod conflicts?: i think there is no conflict, same with just your mod

Thanks for you job, i hope my report can help, feel free to ask precisions.
Best regard

**Comment by Sn1p3rr3c0n** [comment]
Please attach a HugsLib Log.

1. Load the game
2. observe your issue
3. Press CTRL & F12
4. Share the link here

**Comment by Sn1p3rr3c0n** [comment]
@Ahima86 it has been over 2 weeks since I requested a HugsLib Log.
If you can't provide the requested information I will have to close this issue.

**Comment by Sn1p3rr3c0n** [comment]
Closing issue as reporter is unresponsive.
This issue may be reopened if the requested information is provided.
