### ISSUE TITLE
Assembler DB connection

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#54]
Sometimes Assemblers dont see recipes within range of db.

Create problem:
1. Buil 1 smart assembler
2. build a db import adv. component recipe
3. Move to range of assembler
4. build another assembler, some times that one will not see recipe.
- its abit random when they will work or not only got 3 out of 30 tested.
(first ones was worst cant seem to replicate after 3 wrong one)

Occour:
- Seem to be random when placing new assemblers, some time they dont work?
- seem to be a problem after db range update

Fix:
- Build new assembler. (reinstall dont seem to work) 

More info needed

![](https://media.discordapp.net/attachments/635926003423641611/712263234060812299/unknown.png)
Lower left dont see it lower right does.
if rebuild lower left both see it.

**Comment by Maelstraz** [comment]
Sometimes basic assembler cannot see and use some recipes, but adaptive assembler can.

Example: interaction with mod "Craftable synthetics" with recipes for synthread and hyperweave. First is fine for basic assembler, second is recognisable only by adaptive.

**Comment by zymex22** [comment]
@Maelstraz basic assembler only has skill level 10 adaptive have 20. thats why some recipes dont show up.

i included this info in help tab also in next update.

**Comment by zymex22** [comment]
might be something to do with this:
https://github.com/nullre/Project-RimFactory-Revived/commit/56034adea7a995b062c85410b48ce95467ca047f
problem seem to started after that.
or here?
https://github.com/zymex22/Project-RimFactory-Revived/pull/41/commits/2d409006129a75ac6d0ed2eb99a887f5300226db


implementet in this PR:
https://github.com/zymex22/Project-RimFactory-Revived/pull/41

**Comment by zymex22** [comment]
merged into master
