### ISSUE TITLE
(Lite) Factory Entrepreneur Start includes non Lite Defs

### ISSUE THREAD

**Issue by Ltserb** [zymex22/Project-RimFactory-Revived#549]
When loading a save without quitting to OS, installed and minified machines disappear.

HugsLibLog
https://gist.github.com/HugsLibRecordKeeper/c66c05c84bdc5ecf132c1328dc02e63e

Modlist
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Ideology
  - Ludeon.RimWorld.Royalty
  - UnlimitedHugs.HugsLib
  - Fluffy.ModManager
  - spdskatr.projectrimfactory

Steps to Reproduce
Method 1
1 - Create new colony
2 - Use "Factory Entrepreneur" and any other settings
3 - Install Industrial Cooker and Meat Grinder 
4 - Save
5 - Load save
6 - Machines have failed to load

Method 2
0 - Follow steps 1-4 in Method 1
1 - Quit to OS or start with game closed
2 - Start game
3 - Load save
4 - Machines load properly
5 - (Optional) Quit to Main Menu
6 - Load save
7 - Machines have failed to load

HugsLibLog Line 125
Could not load reference to Verse.ThingDef named PRF_SelfCookerI

**Comment by Sn1p3rr3c0n** [comment]
Can you please verify if you are using the lite mode?
If yes, dos the issue persist if it is disabled?

**Comment by Ltserb** [comment]
Issue does only occur when using "PRF Lite Mode"

**Comment by Sn1p3rr3c0n** [comment]
Thanks for the report.
I have confirmed the issue.

The Lite Version is not supposed to contain this Scenario.
