### ISSUE TITLE
search bar on the puller storage UI

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#55]
MatsuseIzuna :

> Would it be possible to put a search bar on the puller storage UI? Since it's pretty frustrating to have to manually find every item you want to use for the filter.

**Comment by zymex22** [comment]
![image](https://user-images.githubusercontent.com/41029070/84621340-8ecb1980-aeda-11ea-8089-664d5e1d4ec8.png)
PRF storage tab on prf puller

![image](https://user-images.githubusercontent.com/41029070/84621362-9c809f00-aeda-11ea-93a1-fc9e7b7c6e1a.png)
IR storage tab on puller/pusher

**Comment by zymex22** [comment]
change `<li>ProjectRimFactory.AutoMachineTool.ITab_PullerFilter</li>`
to `<li>ITab_Storage</li>`

dont seem to apeer working just by swap those 2, update puller code for it?

alternative update `<li>ProjectRimFactory.AutoMachineTool.ITab_PullerFilter</li>`
to have a search bar or support Rim search agency

**Comment by Sn1p3rr3c0n** [comment]
I dont think it makes sense to do a new implementation of a search bar.
There are two Mods on Steam that add one:

- https://steamcommunity.com/sharedfiles/filedetails/?id=726479594 Rimworld Search Agency **(needs a Patch)**
- https://steamcommunity.com/sharedfiles/filedetails/?id=1827546987 Simple Search Bar **(Already Works)**

**Comment by zymex22** [comment]
@Sn1p3rr3c0n  that one just need to swap to `<li>ITab_Storage</li>`
instead of nobos custom one `<li>ProjectRimFactory.AutoMachineTool.ITab_PullerFilter</li>`

that willl make it work with both Rimworld Search Agency and Simple Search Bar

original commenter asked for support for Rimworld Search Agency 
and since it have gotten copy/paste option outsite the tab anyways it might aswell just swap to use vanilla ITab_Storage instead.

that need to be changed in C# though as i tried doing it in xml with no luck

**Comment by lilwhitemouse** [comment]
It WILL need some C# - ITab_Storage expects the building to have some interface. It should be fairly easy to implement that interface.

**Comment by zymex22** [comment]
Fixed with #130 PR
