### ISSUE TITLE
 (Bug report) No bills showing up under Plasma Drill's tab

### ISSUE THREAD

**Issue by aspecttiamat** [zymex22/Project-RimFactory-Revived#555]
### The Issue
During my current custom modpack playthrough, I just finished researching plasma drills, and upon making a plasma drill (t3), it does not have any bills available. I'm certain its a mod conflict but I'm wondering if there is a known issue / solution to this problem. 

### Expected Behavior
Simply put, I was expecting to be able to use the plasma miner to generate materials as I have in the past. 

### Actual Behavior
No bills in the work tab. 

 - RimWorld Version: 1.3.3200 (64-bit)
 - PRF Version: 2.6.4

### Mod List
                

> <li>Harmony</li>
> 		<li>Visual Exceptions</li>
> 		<li>BetterLoading</li>
> 		<li>Core</li>
> 		<li>Royalty</li>
> 		<li>Ideology</li>
> 		<li>SRTS Expanded</li>
> 		<li>Achtung!</li>
> 		<li>HugsLib</li>
> 		<li>RunAndGun</li>
> 		<li>[BETA] Simple Warrants</li>
> 		<li>RimSaves</li>
> 		<li>Trade UI Revised</li>
> 		<li>Dual Wield</li>
> 		<li>Yayo's Combat 3 [Adopted]</li>
> 		<li>A Dog Said... Animal Prosthetics</li>
> 		<li>Vanilla Achievements Expanded</li>
> 		<li>Vanilla Expanded Framework</li>
> 		<li>Vanilla Cooking Expanded</li>
> 		<li>Advanced soup pot</li>
> 		<li>Age Matters 2.0 [1.2+]</li>
> 		<li>Windows</li>
> 		<li>Age of the Rim Material Cost Patch</li>
> 		<li>Age of the Rim Research Patch</li>
> 		<li>Almost There!</li>
> 		<li>Anima Gear</li>
> 		<li>Archotech++</li>
> 		<li>Area Unlocker</li>
> 		<li>Argon's Basic Components</li>
> 		<li>Armor Racks</li>
> 		<li>Auto-Cut Blight</li>
> 		<li>AutoDrill 1.2</li>
> 		<li>Automatic Night Owl</li>
> 		<li>Children, school and learning</li>
> 		<li>Humanoid Alien Races</li>
> 		<li>Babies and Children [1.3]</li>
> 		<li>Bed Rest For Food Poisoning</li>
> 		<li>Better Linkable Colors</li>
> 		<li>Better Map Sizes</li>
> 		<li>Better Pawn Control</li>
> 		<li>Better Transhumanists</li>
> 		<li>Better Workbench Management</li>
> 		<li>Blueprints</li>
> 		<li>Camera+</li>
> 		<li>Capture Them</li>
> 		<li>Character Editor</li>
> 		<li>Choose Your Recipe</li>
> 		<li>Clean Pathfinding</li>
> 		<li>CleaningArea</li>
> 		<li>Combat Readiness Check (Continued)</li>
> 		<li>Combat Update</li>
> 		<li>Enable Oversized Weapons</li>
> 		<li>Vanilla Traits Expanded</li>
> 		<li>Android tiers</li>
> 		<li>Dubs Bad Hygiene</li>
> 		<li>Common Sense</li>
> 		<li>Cremate Auto Strip</li>
> 		<li>Crowns and Regalia</li>
> 		<li>Defensive Positions</li>
> 		<li>Desalination plant</li>
> 		<li>Designator Shapes</li>
> 		<li>Destroy Item</li>
> 		<li>Doors Expanded</li>
> 		<li>Draftable Animals</li>
> 		<li>DragSelect</li>
> 		<li>Dress Patients</li>
> 		<li>Dubs Bad Hygiene Water Tower patch</li>
> 		<li>Dubs Central Heating</li>
> 		<li>Allow Tool</li>
> 		<li>Dubs Mint Menus</li>
> 		<li>Dubs Mint Minimap</li>
> 		<li>Dubs Paint Shop</li>
> 		<li>Ducks' Insane Skills</li>
> 		<li>Dynamic Diplomacy</li>
> 		<li>Dynamic Population</li>
> 		<li>Eccentric Tech - Core</li>
> 		<li>Eccentric Tech - Advanced Shields</li>
> 		<li>Mechanoid Bench 2</li>
> 		<li>Vanilla Factions Expanded - Mechanoids</li>
> 		<li>Vanilla Weapons Expanded</li>
> 		<li>Vanilla Weapons Expanded - Heavy Weapons</li>
> 		<li>Vanilla Weapons Expanded - Laser</li>
> 		<li>Vanilla Weapons Expanded - Frontier</li>
> 		<li>Expanded Materials - Metals</li>
> 		<li>Faster Aging (unofficial 1.3 Update)</li>
> 		<li>Fortifications - Neolithic</li>
> 		<li>Gauranlen Tree Expanded</li>
> 		<li>Gemstones</li>
> 		<li>What the hack?!</li>
> 		<li>Giddy-up! Core</li>
> 		<li>Giddy-up! Battle Mounts</li>
> 		<li>Giddy-up! Mechanoids</li>
> 		<li>Gizmo Begone! (Continued)</li>
> 		<li>Graphics Settings+</li>
> 		<li>Guards For Me</li>
> 		<li>Haul to Stack</li>
> 		<li>Rim-Hivers!</li>
> 		<li>Hive Armory</li>
> 		<li>LWM's Fuel Filter</li>
> 		<li>Less Arbitrary Surgery (Continued)</li>
> 		<li>List Everything</li>
> 		<li>Loading In Progress</li>
> 		<li>Map Reroll</li>
> 		<li>Medical Tab</li>
> 		<li>MendAndRecycle</li>
> 		<li>Midworld Expanded: Flak Armor</li>
> 		<li>Mining Priority</li>
> 		<li>Mod Manager</li>
> 		<li>Cybernetic Organism and Neural Network</li>
> 		<li>Expanded Prosthetics and Organ Engineering</li>
> 		<li>Medical System Expansion 2</li>
> 		<li>Proximity (Continued)</li>
> 		<li>More Archotech Garbage Reupload</li>
> 		<li>More Planning 1.3</li>
> 		<li>More Psycasts</li>
> 		<li>Mortar Accuracy</li>
> 		<li>Need Bar Overflow</li>
> 		<li>No Job Authors</li>
> 		<li>No Lazy Doctors</li>
> 		<li>No Natural Psyfocus Decrease</li>
> 		<li>No Research 1.3</li>
> 		<li>No Sieges</li>
> 		<li>Numbers</li>
> 		<li>OgreStack</li>
> 		<li>Packs Are Not Belts</li>
> 		<li>Perspective: Buildings</li>
> 		<li>Perspective: Doors</li>
> 		<li>Perspective: Trees</li>
> 		<li>Pharmacist</li>
> 		<li>Plasteel Surgery (Continued)</li>
> 		<li>Power Tools</li>
> 		<li>Prisoners Are Not Swines</li>
> 		<li>Prisoners Dont Have Keys</li>
> 		<li>QualityBuilder</li>
> 		<li>Quarry</li>
> 		<li>Quest Reward Rebalance</li>
> 		<li>RPG Style Inventory Revamped</li>
> 		<li>RT Fuse</li>
> 		<li>Vanilla Fishing Expanded</li>
> 		<li>Vanilla Outposts Expanded</li>
> 		<li>ReGrowth: Core and Framework</li>
> 		<li>ReGrowth: Boreal Forest Expansion</li>
> 		<li>ReGrowth: Cold Bog Expansion</li>
> 		<li>ReGrowth: Desert Expansion</li>
> 		<li>ReGrowth: Expanded World Generation - BETA</li>
> 		<li>ReGrowth: Extinct Animals Pack</li>
> 		<li>Vanilla Factions Expanded - Insectoids</li>
> 		<li>ReGrowth: Wastelands</li>
> 		<li>ReGrowth: Mutated Animals Pack</li>
> 		<li>ReGrowth: Temperate Forest Expansion</li>
> 		<li>ReGrowth: Tundra Expansion</li>
> 		<li>Real Ruins</li>
> 		<li>Realistic Rooms Rewritten</li>
> 		<li>Recycle This</li>
> 		<li>Remote Tech</li>
> 		<li>Replace Stuff</li>
> 		<li>Replantable Anima Trees</li>
> 		<li>Research Spot</li>
> 		<li>ResearchPal - Forked</li>
> 		<li>Rim-Effect: Core</li>
> 		<li>Rim-Effect: SRTS Shuttles</li>
> 		<li>RimHUD</li>
> 		<li>RimNauts</li>
> 		<li>Dubs Rimatomics</li>
> 		<li>SF Grim Reality</li>
> 		<li>SRTS Expanded: RotorCraft</li>
> 		<li>Vanilla Events Expanded</li>
> 		<li>Save Our Ship 2</li>
> 		<li>Scavenging mod</li>
> 		<li>Sealed Power Armour</li>
> 		<li>Search and Destroy</li>
> 		<li>Share The Load</li>
> 		<li>Shiny Androids</li>
> 		<li>Show Me Your Hands</li>
> 		<li>[SYR] Processor Framework</li>
> 		<li>Simple Chains: Leather</li>
> 		<li>Simple Industrial Factions</li>
> 		<li>Project RimFactory Revived</li>
> 		<li>Simple Utilities: Ceiling</li>
> 		<li>Simple sidearms</li>
> 		<li>Skilled Stonecutting [1.3]</li>
> 		<li>Smarter Construction</li>
> 		<li>Smarter Deconstruction and Mining</li>
> 		<li>Snap Out!</li>
> 		<li>Stabilize</li>
> 		<li>Stackable Chunks [1.3+]</li>
> 		<li>[KV] RimFridge</li>
> 		<li>LWM's Deep Storage</li>
> 		<li>Pick Up And Haul</li>
> 		<li>Stockpile Limit</li>
> 		<li>Stuff on Tables</li>
> 		<li>Tech Advancing</li>
> 		<li>Thick Armor</li>
> 		<li>Throw Them</li>
> 		<li>Time Kills</li>
> 		<li>Trade Ships Drop Spot</li>
> 		<li>TradeHelper</li>
> 		<li>Trader ships</li>
>  		<li>True Asphalt! Finally!</li>
> 		<li>Vanilla Animals Expanded — Arid Shrubland</li>
> 		<li>Vanilla Animals Expanded — Australia</li>
> 		<li>Vanilla Animals Expanded — Boreal Forest</li>
> 		<li>Vanilla Animals Expanded — Cats and Dogs</li>
> 		<li>Vanilla Animals Expanded — Caves</li>
> 		<li>Vanilla Animals Expanded — Desert</li>
> 		<li>Vanilla Animals Expanded — Extreme Desert</li>
> 		<li>Vanilla Animals Expanded — Ice Sheet</li>
> 		<li>Vanilla Animals Expanded — Temperate Forest</li>
> 		<li>Vanilla Animals Expanded — Tropical Rainforest</li>
> 		<li>Vanilla Animals Expanded — Tropical Swamp</li>
> 		<li>Vanilla Animals Expanded — Tundra</li>
> 		<li>Vanilla Apparel Expanded</li>
> 		<li>Vanilla Apparel Expanded — Accessories</li>
> 		<li>Vanilla Armour Expanded</li>
> 		<li>Vanilla Cooking Expanded - Stews</li>
> 		<li>Vanilla Expanded - Ideology Patches</li>
> 		<li>Vanilla Expanded - Royalty Patches</li>
> 		<li>Vanilla Factions Expanded - Vikings</li>
> 		<li>Vanilla Fishing Expanded - Fishing Treasures AddOn</li>
> 		<li>Vanilla Furniture Expanded - Architect</li>
> 		<li>Vanilla Furniture Expanded - Art</li>
> 		<li>Vanilla Furniture Expanded - Farming</li>
> 		<li>Vanilla Furniture Expanded - Medical Module</li>
> 		<li>Vanilla Furniture Expanded - Production</li>
> 		<li>Vanilla Furniture Expanded - Props and Decor</li>
> 		<li>Vanilla Furniture Expanded</li>
> 		<li>Vanilla Furniture Expanded - Spacer Module</li>
> 		<li>Vanilla Hair Expanded</li>
> 		<li>Vanilla Ideology Expanded - Hats and Rags</li>
> 		<li>Vanilla Ideology Expanded - Icons and Symbols</li>
> 		<li>Vanilla Books Expanded</li>
> 		<li>Vanilla Ideology Expanded - Memes and Structures</li>
> 		<li>Vanilla Ideology Expanded - Relics and Artifacts</li>
> 		<li>ReGrowth: Aspen Forests</li>
> 		<li>Vanilla Plants Expanded</li>
> 		<li>Vanilla Social Interactions Expanded</li>
> 		<li>Vanilla Storytellers Expanded - Igor Invader</li>
> 		<li>Vanilla Weapons Expanded - Grenades</li>
> 		<li>Vanilla Weapons Expanded - Non-Lethal</li>
> 		<li>Vanilla Weapons Expanded - Tribal</li>
> 		<li>Various Space Ship Chunk (Continued)</li>
> 		<li>Visible Raid Points</li>
> 		<li>Wake Up</li>
> 		<li>Wall Light</li>
> 		<li>What's That Mod</li>
> 		<li>Where is my weapon?</li>
> 		<li>While You're Up / PUAH+</li>
> 		<li>Worthless Junk</li>
> 		<li>Yayo's Animation</li>
> 		<li>[D] Ignorance Is Bliss</li>
> 		<li>[FSF] Advanced Bionics Expansion</li>
> 		<li>[FSF] Better Ancient Complex Loot</li>
> 		<li>[FSF] Better Camp Loot</li>
> 		<li>Colony Manager</li>
> 		<li>Harvest Organs Post Mortem</li>
> 		<li>Hospitality</li>
> 		<li>Rimefeller</li>
> 		<li>Vanilla Factions Expanded - Medieval</li>
> 		<li>Vanilla Furniture Expanded - Power</li>
> 		<li>Vanilla Furniture Expanded - Security</li>
> 		<li>[FSF] Complex Jobs</li>
> 		<li>[FSF] Growable Grass</li>
> 		<li>[FSF] More Quests</li>
> 		<li>Let's Trade! [1.3+]</li>
> 		<li>[FSF] Simply Soil</li>
> 		<li>[JAIL] Prison Walls</li>
> 		<li>[KV] Trading Spot</li>
> 		<li>[Kit] Graze up</li>
> 		<li>[LTO] Colony Groups</li>
> 		<li>[O21] Ancient Demolition</li>
> 		<li>[O21] Adjustable Anima</li>
> 		<li>[O21] Seamless Embrasures</li>
> 		<li>[SYR] Coffee and Tea</li>
> 		<li>[SYR] Doormats</li>
> 		<li>[SYR] Harvest Yield</li>
> 		<li>[SYR] Metallic Batteries</li>
> 		<li>[SYR] Set Up Camp</li>
> 		<li>[SYR] Terrain</li>
> 		<li>[XND] Turret Extensions</li>
> 		<li>Xenobionic Patcher</li>
> 		<li>More Linkables</li>
> 		<li>RocketMan - Performance Mod</li>
> 		<li>Vanilla Textures Expanded</li>
> 		<li>Architect Icons</li>
> 		<li>Vanilla Textures Expanded - Variations</li>
> 		<li>Colony Manager retexture</li>
> 		<li>EPOE retexture</li>
> 		<li>QualityBuilder retexture</li>
> 		<li>Repair Mod retexture</li>
> 		<li>SRTS Expanded retexture</li>
> 		<li>SkyMind retexture</li>
> 		<li>WTH retexture</li>
> 		<li>Bionic icons</li>
> 		<li>High quality textures</li>
> 		<li>HD Pawn Rendering</li>
>

**Comment by Sn1p3rr3c0n** [comment]
`Recycle This` is incompatible with `BetterLoading`.
remove one of them and it should work again.

**Comment by aspecttiamat** [comment]
> `Recycle This` is incompatible with `BetterLoading`. remove one of them and it should work again.

I can confirm it was this mod conflict causing the issue. Thank you much!
