### ISSUE TITLE
drones death count

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#56]
Need testing and more info when occur? 

### Problem
- When Drones in drone stations going back to their station they are counted as a "dead pawn" this adds up over time and make save file huge over time.
- this is a thing in PRF - Drones
- and Cultivators. just in a smaller scale on cultivators (less drones)

**Solution:**
- remove dead  drones from dead pawn list when they come back to drone station / "being killed"
- RuntimeCG cleanup dead pawn seem to fix problem, but need performed every time drones return to station to many times.

Malkav:

> I think there may be some third-party mod or possibly something like Hugslib or some such causing this dead drone issue, as I've had both Caretaker and Construction Drone stations up & running in my current playthrough since last weekend, and I have yet to experience this issue. I'm going to keep playing and stay on the lookout for it.
> 
> I just noticed, in the test scenario, you mention a Growing Drone Station. Is it that one specifically that is having this problem, or all 3 types? If it's just the farming drones, that would explain why I haven't seen it.

Malkav:
> Interesting data. I'm not sure how to describe/explain this. My first instinct is to call it WAI, meaning this is how the original creator of the mod built it to work - in B18. But I suspect B18 didn't track dead pawns the same way and so this method was not an issue.
> 
> As for what will be done / what to do about it? Nothing much about this mod is even going to be looked at until Zymex is done improving PRF - core. In the meantime, it sounds like cleaning up the dead pawns with RuntimeGC is a viable stopgap measure.

news.od :

> Just a simple scenario:
> 1. Build farmer drone station
> 2. Fill it with 10 drones and do not touch it
> 3. Create a rice farm
> 4. Play at maximum speed for 2 hours
> The game starts freezing.
> Check dead pawns counter - is above 100000.
> 
> Each time drones returned to the base, counter increased + 10.
> Looks like drone = pawn, at the base station they getting status "dead" and system created new drones if it sees the active task. But information about old drones always keeping in memory.

news.od :
> Strange bug. Each time then the drone returns to the base station - dead pawns counter increments +1. After a few hours save file increased more than 1gb and the game working really slowly. Found it with RuntimeGC

**Comment by lilwhitemouse** [comment]
This was fixed by the "deadpawn count fix " commit, but that introduced a problem (issue #152  ) that was resolved with the 2nd commit.
