### ISSUE TITLE
(Lite) (Bug report) Robotic Arm requires Euler's Identity Research

### ISSUE THREAD

**Issue by Drunkender** [zymex22/Project-RimFactory-Revived#565]
# Describe the bug
In the lite mode the recipe for robotic arm requires the research Eulers Identity which is not available in lite mode.

**To Reproduce**
Reproducibility: ?
1. Enable lite mode
2. Research all avalable RF research
3. Items not craftable(Not appearing in the bills tab of machining table)

**Expected behavior**
The recipe is in the machining tables bill tab or in a different research that is avalable in ltie mode.

**Actual Behavior**
There is no way to craft the robotic arm in lite mode without dev mode.

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.3.3287(Plus the version before)
 - PRF Version: Latest version as of Dec 5, 2021

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: Yes

********
Additional stuff that probably needs its own report, can't seem to make the robotic Machining Table no matter what i do (Dosen't show up in the architect menu even in dev mode), and if it is supposed to be disabled in lite mode there is no way to craft Simple Machine Frames, Advanced Machine Frames, Advanced Ai Cores or Weak Ai Chips  without it (Which are required to make most of the items in PRF Lite). The Adv Ai Cores also require disabled research. **If this needs its own report let me know**.

**Comment by Sn1p3rr3c0n** [comment]
Robotic Arms or any other of the intermediate resources do not exist it the lite mode.
All Recipe's and Build requirements are automatically updated to not include those things.

If some reason this dose not work for you please post more specific details and a HugsLib Log

**Comment by Drunkender** [comment]
Apparently when testing RF with no other mods my mod list reset itself back to full. This issue does NOT happen when only RF and base game files are loaded. Will report back when I find the incompatible mod. So far it is not a mod that checks for the mod name or the packageid in xml patches(F***in love dnGrep).

**Comment by Drunkender** [comment]
[Bulk Recipe Generator (Continued)](https://steamcommunity.com/sharedfiles/filedetails/?id=2377889028) is the conflicting mod.

```
System.ArgumentException: An item with the same key has already been added. Key: PRF_DataDisk
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000c1] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at ProjectRimFactory.Common.PRF_CustomizeDefs.removeComponents (System.Collections.Generic.List`1[T] defNames) [0x0004d] in <72a93ba175f6484d8cb0c2e1e0a34c09>:0 
  at ProjectRimFactory.Common.PRF_CustomizeDefs.ToggleLiteMode (System.Boolean remove) [0x004f1] in <72a93ba175f6484d8cb0c2e1e0a34c09>:0 
  at ProjectRimFactory.PRFGameComponent.StartedNewGame () [0x00024] in <72a93ba175f6484d8cb0c2e1e0a34c09>:0 
  at Verse.GameComponentUtility.StartedNewGame () [0x00017] in <360933dd75ad47e8a6d2a631ae77b5d8>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.GameComponentUtility:StartedNewGame ()
Verse.Game:InitNewGame ()
Verse.Root_Play/<>c:<Start>b__1_2 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()
```

Tested with only RImworld Harmony Hugslib PRF and Bulk Recipe Generator.

**Comment by Drunkender** [comment]
https://github.com/zymex22/Project-RimFactory-Revived/issues/567
