### ISSUE TITLE
Smart Recycler does not consider Centipedes to me mechanoide (Bug report)

### ISSUE THREAD

**Issue by PortableTech** [zymex22/Project-RimFactory-Revived#575]
# Describe the bug

The Smart Recycler seems quite happy to shred mechanoide of any kind I give it except for Centipedes.  I am still able to use the shred mechanoide option at the Machining Table to take care of them, but guessing this is some simple exclusion of this specific items from it's list of things it considers mechanoids.

**To Reproduce**
Reproducibility: ?
1.  Place Centipedes in work are of Smart Recycler and setup bill to shred mechanoids.
2. 
3. 

**Expected behavior**

Should shred Centipedes as it does other mechanoids.

**Actual Behavior**

Leaves them sitting in the queue.

**Screenshots**

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.3
 - PRF Version: MArch 23 Release
 - Link to gist bug report: 
 - Type:
 - Severity:
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: Have not yet tested
 - Your modlist (if needed): 
 - Do you know what mod conflicts?:

**Additional context**

**Comment by Sn1p3rr3c0n** [comment]
I cannot reproduce this issue. it works just fine for me.
![image](https://user-images.githubusercontent.com/68663281/162560719-72cb4b2c-6052-4a53-a30e-ddbbe7c247ab.png)

Please verify that the bill you configured allows Centipedes.
Should the issue persist please post a HugsLib log. (CTRL & F12) _(then paste the link here)_

**Comment by Sn1p3rr3c0n** [comment]
@PortableTech Due to lack of feedback & not being able to reproduce the issue I am closing this issue.
This issue may be reopened if the requested information is provided.
