### ISSUE TITLE
Consider whether 0NoMessySpawns should be used/separate/etc

### ISSUE THREAD

**Issue by lilwhitemouse** [zymex22/Project-RimFactory-Revived#58]
Should 0NoMessySpawns be used by PRF?
If so, should PRF have a fork of its code? (yes)
If not, PRF will need to fold the Harmony patch into base code.

**Comment by zymex22** [comment]
https://media.discordapp.net/attachments/635926003423641611/714336426908450826/unknown.png?width=1185&height=1019

https://gist.github.com/HugsLibRecordKeeper/e4ae486639f646848b54174e23b6e570

https://github.com/DoctorVanGogh/NoMessySpawns

![](https://media.discordapp.net/attachments/635926003423641611/714347882576347217/unknown.png)

**Comment by zymex22** [comment]
have we considered yet? no? :p

**Comment by lilwhitemouse** [comment]
This might be applicable to this issue: https://git-scm.com/book/en/v2/Git-Tools-Submodules
