### ISSUE TITLE
 (Bug report) by aef8234

### ISSUE THREAD

**Issue by Sn1p3rr3c0n** [zymex22/Project-RimFactory-Revived#590]
Post by @aef8234
> This same exact issue is happening to me too so it might not have been fixed.
Here's my log: https://gist.github.com/7dcb16709110615a90d472cde3b584e3
>
>I saw a pattern though shorter belts and belts underneath roofing like sensor panels from expanded roofing will get turned into whatever "placement 0-3" is. Also it isn't just SAL robots, drillers and just all around putting things in a conveyor belt is doing it. Maybe it's lag-related?

No part of you log Indicates that your issues relate to the issue you posted it under.
As a general recommendation don't post on closed issues unless you have actual knowledge of that exact issue. 
Instead open a new issue (I have done this for you here).

**Comment by Sn1p3rr3c0n** [comment]
@aef8234
The vast majority of your errors seem to be caused by `Nature's Pretty Sweet` using the following postfix `TKKN_NPS.PatchSpawnSetupThing.Postfix`

There is an `System.ArgumentOutOfRangeException` in `ProjectRimFactory.AutoMachineTool.Building_BeltConveyor.AcceptsThing` but I would not be surprised if this is a direct result of the errors caused by  `Nature's Pretty Sweet`.

additionally it appears that  `Nature's Pretty Sweet` is also causing drone jobs to fail.

Lastly i recommend that you order you mod list, a bad load order can cause all kinds of issues. I would recommend you to use RimPy.

Please check if the issue persists if you order your modlist & remove `Nature's Pretty Sweet`

**Comment by aef8234** [comment]
Yeah it was Nature's Pretty Sweet. I got rid of it and everything seems to be working fine. It's a shame but that mod really doesn't like a lot of other mods.

**Comment by Sn1p3rr3c0n** [comment]
Closing. caused by `Nature's Pretty Sweet`
