### ISSUE TITLE
(Request) Give Smart Hoppers a "Pickup from Stockpile" Toggle

### ISSUE THREAD

**Issue by fludd12** [zymex22/Project-RimFactory-Revived#594]
**Is your feature request related to a problem? Please describe.**
Smart Hoppers are a fantastic feature in RimFactory, allowing for quick collection of resources dropped from various machines or tasks in the area, but I've noticed an issue that can limit their usage. Placing one near a stockpile or DSU output will cause it to rapidly pull from the stockpile - expected behavior, but this can be annoying if I want to collect from specific, non-stockpile tiles.

**Describe the solution you'd like**
There is an existing toggle on the Smart Hopper which lets you choose if it can pull from the ground or only from stockpiles. I would like the inverse as an option - toggle if it can pull from stockpiles, or only the ground.

**Describe alternatives you've considered**
The use cases I imagine this for can already be handled by drone stations with hauler drones, so this feature request may be considered redundant. However, in cases like the harvest drone station, there is an alternative in the nano-harvester stations. Personally, I consider the Smart Hopper to be the nano- equivalent to a drone set to haul; faster, with less impact on pseudo-colonist creation and removal.

Alternatively, a new device could created that performs this same feature; if local hauling is intended to be balanced by the delay caused by drone usage, this could be a more expensive nano-haul station that fulfills a similar task.

**Additional context**
![image](https://user-images.githubusercontent.com/11167153/173638221-acd430e7-8672-4b30-8f53-b404be03982f.png)
Here's an example use case - if the SAL autocrafters abort a task, they tend to drop the steel used in the task on top of themselves or on surrounding tiles. Unfortunately, the smart hopper to the bottom right prioritizes targets based on nearness, so the steel just above the DSU I/O port will never be collected automatically, meaning a hauler must do the job instead.

**Comment by Sn1p3rr3c0n** [comment]
I think it might be worth to consider implementing this as an ITab instead.
Where a user can specify all the possible different sources that they want to allow.

- Ground (Y/N)
- Stockpile (Y/N)
- ? Building Storage (Y/N)
- ? Allow forbidden  (Y/N)

**Comment by Sn1p3rr3c0n** [comment]
Tab is mostly done.
Time to add some logic
![image](https://github.com/zymex22/Project-RimFactory-Revived/assets/68663281/a25cbbfc-6e75-45f3-98ba-e69b6505eb4d)

**Comment by Sn1p3rr3c0n** [comment]
Todo Implement Functionality for:
- [ ] Stockpile
- [ ] Storage Building

**Comment by Sn1p3rr3c0n** [comment]
Currently Allow Ground is required to pick up from Belts.
we might want to change that. maybe another toggle?

The green overlay helper seems broken

**Comment by Sn1p3rr3c0n** [comment]
New functional Belt Toggle
![image](https://github.com/zymex22/Project-RimFactory-Revived/assets/68663281/13296e39-91f0-4dca-a80f-117b8aa4cd70)

**Comment by Sn1p3rr3c0n** [comment]
since fixing the Overlay i might be able to remove some duplicated logic.
that's the last todo for this issue i think
