### ISSUE TITLE
General IO Access 

### ISSUE THREAD

**Issue by Sn1p3rr3c0n** [zymex22/Project-RimFactory-Revived#595]
The Idea of this Feature is that a pawn can access any item that is included in a DSU with a single port.

While this has been requested countless times and is often the expected behavior of IO Ports for new users we have never really put this Feature request in Writing. _(unless i have missed it somehow)_

In the past I was convinced that such a feature would surely have a massive negative impact on the performance (TPS).
But a recent test showed great promise with an unexpectedly low impact.

I think this Issue can be considered a sub point of #342

**Comment by Sn1p3rr3c0n** [comment]
**Known issue / notes**
- [ ] not working for animals (that might be a good thing)
- [ ] traders can cause null refs (kindof fixed with 44f932a57d29ddcea35ed104ae80edc304e4e6b5 but I am not happy with that)
- [ ] some kind of Joberror related to the `GauranlenSeed`
- [ ] Pawns refuel the `Wood generator` with `Pemican`
- [ ] Patches should be transpiles instead of semi destructive prefixes

**Comment by Scorpiopt** [comment]
Been wanting this feature for quite a while mentioned on discord several times but was told it was not possible

**Comment by Sn1p3rr3c0n** [comment]
From the Technical side this should be done now.
Open Topics:

- [ ] Should there be a different / unique Texture?
- [ ] "Final" Name & Description?
- [ ] Construction Cost? _maybe bump to advanced AI_
- [ ] Research requirement? _same as IO pusher?_  
---

The remaining noted / known "issues" are basically just how rimworld things work. I think woking one them is not worth the hassle at this point. And it is also not the Job of this mod to make Pawns act smarter, such changes are better off in dedicated mods.

**Comment by Sn1p3rr3c0n** [comment]
Currently working on some additional Code Updates.

Most notably using a better calculation for the distance (eg.: Pawn -> Item -> Target)

I Also attempted to use Pathing to find the real cost _(Walls exist...)_
However this is very expensive and I therefore plan not to use it. 
This can result in some questionable pathing choices, but I think it is better to pay that price.
_Fore reference: with ~0.4ms per call this is 2000 times worse. (without Pathing it takes ~0.2us)_
