### ISSUE TITLE
Vacuum hopper auto unforbid

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#60]
Let PRF item puller `(ThingDef Name="Building_AutoMachineTool_Puller_Base")`

Be able to unforbid stuff after it pull items, so it dont let items pulled from Vacuum hopper, stay forbidden when pulled into Storage containers like DSU.

Thingclass: ProjectRimFactory.AutoMachineTool.Building_ItemPuller

https://github.com/zymex22/Project-RimFactory-Revived/blob/master/Source/ProjectRimFactory/AutoMachineTool/Building_ItemPuller.cs

**Comment by zymex22** [comment]
should be:
Forbid --> unforbidden output
unforbidden --> unforbidden output

so forbidden stuff from vacuum hopper, gets unforbidden when placed into storage / I/O port.
else it will become forbidden inside DSU

**Comment by lilwhitemouse** [comment]
Total set of options for the puller:
"Also pull forbidden items; always unforbid"
"Also pull forbidden items; leave alone"
"Pull all items; always forbid"
"Only pull items not forbidden"
"Only pull items not forbidden; set as forbidden"

**Comment by lilwhitemouse** [comment]
zymex: anyways i think right way would be:
update puller to
- gizmo button allow take forbidden stuff
- if forbidden stuff is taken it will unforbid when push it out.

that way it give flexibility to player not take in forbidden stuff (they dont have that now)
and it will fix problem when moving forbidden stuff into storage and getting stuck.

**Comment by zymex22** [comment]
![image](https://user-images.githubusercontent.com/41029070/84593826-8af1b580-ae4e-11ea-9ed0-c3d6e4cff39c.png)
