### ISSUE TITLE
adding resources from other mods to drills

### ISSUE THREAD

**Issue by AtmosDragon** [zymex22/Project-RimFactory-Revived#608]
How to add resources from other mods to plasma drill (and other drills), I tried to add this to thingDefs_buildings/buildings_miners, but there is no place.

**Comment by Sn1p3rr3c0n** [comment]
Github Issues are not really the best place to request support on how you can mod things. 
Our discord would be a better place for this.

Drills automatically add recourses from other mods to its bills.

With Patches you may set disallowed items and or configure the chance element of it.
See https://github.com/zymex22/Project-RimFactory-Revived/tree/master/Patches/Drill%20patches for exampels.

_closing issue_
