### ISSUE TITLE
Inability to select assembler 

### ISSUE THREAD

**Issue by Areskiko** [zymex22/Project-RimFactory-Revived#61]
After selecting the "Recipe database" from the architect menu there's no way to select the assembler, other than reloading. It's possible to change from assembler to Recipe database, but not the other way around. I have attached a video showcasing the problem.

[example of problem.zip](https://github.com/zymex22/Project-RimFactory-Revived/files/4740110/example.of.problem.zip)

**Comment by zymex22** [comment]
problem due to load order of dropdown.

fixed in next release
