### ISSUE TITLE
PRF_StorageIO_II, not buildable, including in god mode (Bug report)

### ISSUE THREAD

**Issue by AtmosDragon** [zymex22/Project-RimFactory-Revived#611]
Nothing happens when i try to build. Perhaps i decided to check it too early, only today it came out of 595 in master.

**Comment by Sn1p3rr3c0n** [comment]
I understand that you cloned the current master.
But did you also build the assembly?

**Comment by Sn1p3rr3c0n** [comment]
so you did not compile the assembly's.
In this case this is the expected result, without a updated assembly containing the logic for the building it can't work.

To prevent unnecessary merge conflicts and data we only upload a updated dll when we release an update. 
if you want to use the current master you need to compile it yourself.

_if you can't compile i can post the current assembly on our discord if you ask nicely_

**Comment by AtmosDragon** [comment]
Oh, just like I thought, I'm too early.
