### ISSUE TITLE
more c.GetFirstBuilding(map);

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#62]
Thornsworth found some more places where `c.GetFirstBuilding(map);`
is used:

https://github.com/zymex22/Project-RimFactory-Revived/search?q=GetFirstBuilding&unscoped_q=GetFirstBuilding

theese should be fixed as it properly will fix my db connection problem there have been for some time now.
also apperently on I/O

**Comment by lilwhitemouse** [comment]
Note the fix is in the lwmfixes branch

**Comment by zymex22** [comment]
at first glance it worked fine, i will test further tomorrow and then close this topic
