### ISSUE TITLE
(Request) Clear Confusion around Cold Storage Unit

### ISSUE THREAD

**Issue by Sn1p3rr3c0n** [zymex22/Project-RimFactory-Revived#652]
From multiple comments on Steam and Discord it is Clear 
that the Name `Cold Storage Unit` and or it's Description are confusing / not obvious to many users.

### Cold Storage Unit
A storage Unit designed to store lots of Things With a low Performance Impact
Has some downsides for Usability but those improve Performance.

### Refrigerated Storage Unit
A storage Unit to keep Things Refrigerated.
Available as a Patch for Supported Fridge Mods

---

### The Confusion
Users think the `Cold Storage Unit` is Intended to be used to keep Things Refrigerated.
They seem to think this is the replacement for the Refrigerated Storage Unit. (probably partially caused by the Updated RimFrige Mod currently being unsupported(as of release versions - Support has been added with #641 ))

**Inspiration for the Name `Cold Storage Unit`**
I intended the name to relate to "Cold Storage" in the Digital Storage sense.
> In the context of [computer data storage](https://en.wikipedia.org/wiki/Computer_data_storage) (and [backup](https://en.wikipedia.org/wiki/Backup#Storage_media)) the term "cold storage" is "long term storage". See also [Cold data](https://en.wikipedia.org/wiki/Cold_data).

- stores lots of things
- not in constantly active use

**What to do?**
This is the Central Question. What can we do to avoid this?
Should we change the Name?
Can we Improve the Description (is that even read?)?

**Comment by Sn1p3rr3c0n** [comment]
**Suggested names:**

- `Digital Storage Vault` by NULL★Sparkle
- `Long Term Storage Unit` by @InsanityPrelude 
- `Archival Storage Unit`by @InsanityPrelude 
- `High Capacity Storage Terminal` by Madman666

**Comment by eRaz0rHead** [comment]
Heh. I absolutely thought this was for refrigeration!

IIRC (I'm away from my game at the moment, so I can't verify until later), I _can_ connect Fridge I/O ports to the Cold Storage unit, but _not_ to the DSU.  Similarly, I _cannot_ connect the Adv I/O units to the CSU. 

Also, it seems that many items in the CSU no longer lose durability (e.g. foodstuffs that degrade when not frozen), so in effect, CSU is acting as if it were a refrigerator anyway.

Are those all intended behaviours?

**Comment by eRaz0rHead** [comment]
BTW -- It isn't really clear what the effect of putting things in here does to the Pawns ability to use those items.  Calling it "High Capacity" was appealing at first (since the main feature seemed to be the much larger number of stacks supported), but from what I've gathered, Pawns don't see those items (and neither do mods like Inventory Tab), unless you have an I/O output port pulling from there, is that correct? 
If so, how about "Offline Storage"? And update the help-text to indicate what that means to Pawns.

**Comment by Sn1p3rr3c0n** [comment]
@eRaz0rHead 
Please note that Github is intended for the Development.
Issues are Created for Specific topics and discussions on them should be kept to that scope.
If you want to chat or maybe have general Questions, then our Discord would be a much more suitable Platform.
If you think some descriptions can / should be improved please feel free to let us know on our Discord.
In any case Please be specific

**Comment by eRaz0rHead** [comment]
Understood.

**Comment by Sn1p3rr3c0n** [comment]
I think i will rebrand it to `Archival Storage Unit` as suggested by @InsanityPrelude
