### ISSUE TITLE
 (Bug report) Rimworld will CTD when construction drones are trapped.

### ISSUE THREAD

**Issue by ElectroTiger** [zymex22/Project-RimFactory-Revived#661]
# Describe the bug
Rimworld will CTD when construction drones become trapped. 

**To Reproduce**
Reproducibility: I can consistently reproduce this with only Harmony, All Rimworld Expansions, Hugslib, PRF, and PRF Drones loaded.

1. Spawn a construction drone station. I filled it with 20 out of 20 drones. 
2. Create a new construction and wait for the drones to start building it.
3. Either let the drones trap themselves (e.g. they build a wall encasing themselves) or use Godmode to build a wall around them.
4. When the drones finish construction, and finish building any roofs in their encasement, the game will crash. 
5. Alternatively, with trapped drones on the map, select the drone station and press "lockdown". The game will crash. 

**Expected behavior**
Drones should hang around and do nothing just like pawns do when trapped. 

**Actual Behavior**
The game will crash to desktop. 

**Screenshots**
Below screenshot shows one drone trapped inside wooden walls. This is taken while the game is crashing; everything is frozen, and in a few seconds, it will CTD. 
![20221126210330_1](https://user-images.githubusercontent.com/19162027/204117738-a5b28222-3854-4628-8be2-40276f228768.jpg)

Below screenshot shows one drone trapped inside marble walls. Once the drone finishes construction, the game will crash. 
![20221126211205_1](https://user-images.githubusercontent.com/19162027/204117918-ed93f5d2-9ba2-4b27-9590-86f238da6291.jpg)

**Rimworld (please complete the following information):**
See Hugslib for version information:
https://gist.github.com/HugsLibRecordKeeper/b1c5e79dbbcb3b6d0575deb10992a288

**Modlist (please com
[Player.log](https://github.com/zymex22/Project-RimFactory-Revived/files/10097454/Player.log)
plete the following information):**
 - Does this problem exist if only prf is installed: Yes
 - Your modlist (if needed): Harmony, All Rimworld Expansions, Hugslib, PRF, PRF Drones
 - Do you know what mod conflicts?: None

**Additional context**

Player.log is attached below from a game that crashed. Savegame with minimal loadset is also attached. 

[Player.log](https://github.com/zymex22/Project-RimFactory-Revived/files/10097457/Player.log)

Note: Savegame is from first screenshot. It does not even have Hugslib loaded. I loaded Hugslib to create the report & take the second screenshot. 
[CrashNow.zip](https://github.com/zymex22/Project-RimFactory-Revived/files/10097458/CrashNow.zip)

**Comment by Sn1p3rr3c0n** [comment]
Thanks for your report.

We obviously need to prevent the crash. 
For the expected behaviour however we don't want you to be able to trap them.
I believe the best Solution in this Scenario would be to kill the drone an place a module in its place.
