### ISSUE TITLE
mod setting bug with Startup Impact

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#67]
> I also found another mod conflict that's oddly specific. If you have Startup Impact installed and turn off the Miner's Nerf in the mod settings, it will cause an error and disable all mods when the game restarts.

**Comment by zymex22** [comment]
If any mod settings in PRF are set to True it will conflict with Automatics : Startup Impact mod.
i have no clue why that happens but it seem to be true for all settings, so i guess its method that does it.

if any set to true it willl crashh RW on startup and reset modlist, so for now its put on incompatible list for that reason

it could be a priority? but not sure if it can be fixed or not, and its not that it impact any gameplay if not able to have Startup Impact

**Comment by lilwhitemouse** [comment]
Is there any word on error messages (if RW is run from the command line, for example, or in the system log that RW writes to?)

**Comment by Sn1p3rr3c0n** [comment]
the issue is that for 2 of our patches configured via the settings `patch.sourceFile` can be null.
More specifically the issue occurs cause Startup Impact attempts to write that null as a key to a dict. 
```Csharp

private static void Postfix(ModContentPack __instance)
{
	ModInfo modInfo = StartupImpact.modlist.Get(__instance);
	modInfo.Stop("load-patches");
	foreach (PatchOperation patch in __instance.get_Patches())
	{
		patchMods[patch.sourceFile] = modInfo;
	}
}
```

I have identified the following two patches to be at fault:
```
Patch Verse.PatchOperationRemove(/Defs/ThingDef/modExtensions/li[@Class="ProjectRimFactory.SAL3.Exposables.AssemblerDefModExtension"]/workingGraphicData) - path: 
Patch Verse.PatchOperationRemove(/Defs/ThingDef/modExtensions/li[@Class="ProjectRimFactory.SAL3.Exposables.AssemblerDefModExtension"]/powerOffGraphicData) - path: 
```
I initially disabled them with b955c4e33aa6eeaec61ec846cbb4cf3d52b42461 allowing a Startup with Settings & Startup Impact

**TODO**
Check why they have a null of the `.sourceFile` & fix it

**Comment by Sn1p3rr3c0n** [comment]
Have to add the correction that none of the patches have `.sourceFile` set.
i only got the stated ones based upon my settings
