### ISSUE TITLE
(Request) Add support for `RimFridge: Now with Shelves!`

### ISSUE THREAD

**Issue by 71e6fd52** [zymex22/Project-RimFactory-Revived#673]
[RimFridge: Now with Shelves!](https://steamcommunity.com/sharedfiles/filedetails/?id=2898411376) is a fork of `[KV] RimFridge`, with support for three stacks of items per fridge-cell 

RimFactory is able to patch RimFridge and add Fridge Digital Storage Unit, but it does not detect `RimFridge: Now with Shelves!`.

Since "RimFridge: Now with Shelves!" is a popular mod and it is among the top on the Steam workshop's trending page, adding support for it would be beneficial.

**Comment by Sn1p3rr3c0n** [comment]
Unfortunately that Mod is a replacement and not a XML Addon Mod like it should be.
For Compatibility will also require Code Changes for the Compatibility Patch.

**Comment by Sn1p3rr3c0n** [comment]
Solved in 1.5 with #784
Closing.
