### ISSUE TITLE
mod conflict Technology Blueprints & Reverse Engineering

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#68]
> I mentioned the conflict with Technology Blueprints & Reverse Engineering hiding/disabling the T3 miner bills in another thread.

For some reason Technology Blueprints & Reverse Engineering mess with bill menu on T3 miner.

**Comment by Sn1p3rr3c0n** [comment]
`Technology Blueprints & Reverse Engineering` seems to remove our bill after we create it dynamically on startup.
Im not sure why it dose that or what the conditions for removal are (even after a short look at the decompiled code).

At the time of writing `Technology Blueprints & Reverse Engineering` is still on 1.1 and has 2k subs

as recommended by @zymex22 i will not investigate further for now.

**Comment by zymex22** [comment]
We will close this and reopen if updated to 1.2

im subbed to that mod and will keep and eye out for it.

**Comment by Sn1p3rr3c0n** [comment]
The issue was caused by `Technology Blueprints & Reverse Engineering` calling `AllRecipes` before our Recipes where added to the miner.
`AllRecipes` will internally cache the `recipes` once when it fist gets called.
To fully add them in a usable capacity we need to clear that cache.
