### ISSUE TITLE
 (Bug report)Problems in item handling with ports

### ISSUE THREAD

**Issue by bloodstone1476** [zymex22/Project-RimFactory-Revived#699]
# Describe the bug
Pawns are moving Items from “most” Output to any Input (Or i could say that items in the same slot as the port are no longer considered stored in the storage)

Steam latest version of rimworld and factory
The log file is below, including the mod list, and because there are too many mods, it is really hard to directly test whether the problem will be triggered when there is only with the factory

**Additional context**
[Player.log](https://github.com/zymex22/Project-RimFactory-Revived/files/11205989/Player.log)

**Comment by Sn1p3rr3c0n** [comment]
Took me a bit to track this down. 
This only occurs if the Limit is used.

Seems like there was a reason for https://github.com/zymex22/Project-RimFactory-Revived/pull/679/files#diff-c6c732b2abf073ef68b0c14074ea6cb07465e99818c54a6975b22328a77b3b0bL37-L40 afterall.
