### ISSUE TITLE
(Bug report) Incompatibility's [KV] Save Storage, Outfit, Crafting, Drug, & Operation Settings [1.4]

### ISSUE THREAD

**Issue by zxdao** [zymex22/Project-RimFactory-Revived#704]
# Name of the Incompatible Mod
[KV] Save Storage, Outfit, Crafting, Drug, & Operation Settings [1.4]
[https://steamcommunity.com/sharedfiles/filedetails/?id=2878346181](url)
![image](https://user-images.githubusercontent.com/33011461/231938281-06ec1557-03ab-4682-8b33-2278045444ae.png)

# Description of the Incompatibility
This mod may make the "save settings" and "load settings" disappear

**a HugsLib Log**
In fact, it didn't appear at all (I know it's ridiculous)

**Screenshots(Streamlined testing for other mods)**
 - When only using KV save setting mod:
     My Modlist:
![mod列表（取消工厂）](https://user-images.githubusercontent.com/33011461/231940294-3184b53e-fcad-4134-885f-25de569ee3be.png)

    We're going to have "save setting" and "load settings" right here:
![清单正常了](https://user-images.githubusercontent.com/33011461/231940301-71e615cc-481e-4d70-83d4-cbb2cf86b7a7.png)

 - When both mods are used:
     My Modlist:
![mod列表 ](https://user-images.githubusercontent.com/33011461/231939505-c558119a-c4c0-4db8-9e1c-0a27d1ea85df.png)
     
     "save setting" and "load settings" are gone:
![清单不正常](https://user-images.githubusercontent.com/33011461/231939523-8eb37185-c364-4644-8c6d-31018a9d256c.png)

     But KV save setting's other features, such as the plan list, are still there(The Chinese meaning is "Load a new setting"):
![方针正常](https://user-images.githubusercontent.com/33011461/231939535-2cca4156-a945-47db-9dbb-9bb80bd323bb.png)

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.4.3682 rev789
 - PRF Version: 2.7.9
 - Type: UI
 - Severity: Not too much, I can temporarily find an alternative that doesn't work as well
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: Yes
 - This is the Modlist I usually use：
![image](https://user-images.githubusercontent.com/33011461/231942294-ae33a019-8a76-48af-8cd9-a9a4f88a9926.png)
![image](https://user-images.githubusercontent.com/33011461/231942337-7077d074-a2ce-4242-8a99-933516c27b4f.png)
![image](https://user-images.githubusercontent.com/33011461/231942460-6fb1103d-c9a5-47f0-8bf7-064ebac6654a.png)
![image](https://user-images.githubusercontent.com/33011461/231942527-b4c45125-c7e9-4a51-bfbc-9f063078f9ff.png)
![image](https://user-images.githubusercontent.com/33011461/231942564-08700d03-c7d6-40f8-837e-38e7cb986f4d.png)
![image](https://user-images.githubusercontent.com/33011461/231943104-5a42b210-bfc6-4e31-891c-4827e4cb4656.png)
![image](https://user-images.githubusercontent.com/33011461/231943130-fc12e5af-7550-4ce1-a56e-fbcc4f015607.png)
![image](https://user-images.githubusercontent.com/33011461/231943160-6d23bcb2-1adf-404e-abf7-8ff1a0efc53f.png)
![image](https://user-images.githubusercontent.com/33011461/231943198-383e8f73-3895-4c58-9229-e52f0be2dc5c.png)
![image](https://user-images.githubusercontent.com/33011461/231943236-eeb24f36-b4ee-4a06-9696-0150a56faaf4.png)
 - Even if I use the full list of mods and only change the use of prf, this is still the result of the above test

**Additional**
I tried changing the mod Settings, but it didn't seem to work (Not trying all)
This is my usual setting:
![边缘工厂设置](https://user-images.githubusercontent.com/33011461/231939561-c0c112db-9514-4fc5-8f8d-7ba532ac186b.png)
![边缘工厂设置2](https://user-images.githubusercontent.com/33011461/231939571-e4bb00c4-057f-4d28-b242-6d48b513f494.png)

Thank you for your efforts, I really like your mod ：）

**Comment by Sn1p3rr3c0n** [comment]
Ah now i understand your issue.
The gizmos are missing on other buildings.
baffaf591201c9e72d7d235b812d8e6581fa0a71 should fix the issue.
Compiled version in zip: [ProjectRimFactory.zip](https://github.com/zymex22/Project-RimFactory-Revived/files/11230173/ProjectRimFactory.zip)
