### ISSUE TITLE
t3 Miner does not have Bills (Bug report)

### ISSUE THREAD

**Issue by SneakyDevil** [zymex22/Project-RimFactory-Revived#711]
Bug: T3 Miner doe not have bills

**Screenshots**
![image](https://github.com/zymex22/Project-RimFactory-Revived/assets/11374726/9a94e223-1fb1-41fe-986e-c88718543101)

**Rimworld (please complete the following information):**
 - RimWorld Version: latest stable
 - PRF Version: 2.7.9

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: no
 - _Removed list from Post (will be included with the log alongside other usefull information in a more manageable format_
 - Do you know what mod conflicts?: I checked all issues involving the miner + wiki to ensure no listed conflicts

**Comment by SneakyDevil** [comment]
[hug lib log.txt](https://github.com/zymex22/Project-RimFactory-Revived/files/11599127/hug.lib.log.txt)

upload failed so heres the file directly

**Comment by Sn1p3rr3c0n** [comment]
Hmm I was expecting some error to be the culprit but that's not the case.
I have a feeling that your mod list might be unsorted. (Unsorted Mod lists can cause all sorts of issues)

The log shows that you have the `RimPy Mod Manager Database` loaded. This is not how you use rimpy, you don't need to have that loaded. Try to read the description of Rimpy again.
Should the issue persist after sorting with rimpy please send an updated HugsLib Log.

**Comment by Sn1p3rr3c0n** [comment]
Hmm.
So this work's with only Rimfactory right?
If so then it is some kind of Mod conflict.
I might be able to get you a debug build tomorrow, although I doubt it will be able to point to the conflicting mod.

You could try to use a binary search to narrow down the conflicting mod.

**Comment by SneakyDevil** [comment]
I'm thinking it might be another AllRecipe situation, how would I go about combing for which mods might modify/overwrite that.

**Comment by Sn1p3rr3c0n** [comment]
The Attached Zip Contains an Updated Dll with some extra Debug Contest on the Recipe generation
[ProjectRimFactory.zip](https://github.com/zymex22/Project-RimFactory-Revived/files/11612729/ProjectRimFactory.zip)

Sample Output: https://gist.github.com/HugsLibRecordKeeper/90c6ad9866cb0cc92732a2869edf50ae

**Comment by SneakyDevil** [comment]
Sorry about the wait had to do some onsite work today. 

I was able to narrow it down to these two being the cause:
https://steamcommunity.com/sharedfiles/filedetails/?id=2868392160
https://steamcommunity.com/sharedfiles/filedetails/?id=2868389782

I replaced the DLL in the assemblies folder with the attached. Here is the new log: 
[debugged hug log.txt](https://github.com/zymex22/Project-RimFactory-Revived/files/11619514/debugged.hug.log.txt)

**Comment by SneakyDevil** [comment]
I can narrow it down even more https://steamcommunity.com/sharedfiles/filedetails/?id=2868389782 had a May 2023 update that caused this issue. 

Its possible this issue is caused by the fact that I bought the T3 instead of researching it due to how this mod now works from what the comments are saying. I'll look into this further.

**Comment by SneakyDevil** [comment]
Yeah, it looks like the May update added the T3's bills to its unlocking tech. I'll close the ticket, thanks for taking the time to help me look into it.
