### ISSUE TITLE
(Bug report) Plasma drill not showing all recipes after enabling them in the mod settings 

### ISSUE THREAD

**Issue by pc-rig** [zymex22/Project-RimFactory-Revived#717]
I enabled the option for the autominers to mine all ores, but when I checked in-game, only the chunks and steel were available.    

**To Reproduce**
Reproducibility: ?
1. Download the save file
2. Enable the setting
3. Check the plasma drill

**Expected behavior**
Ores like gold and plasteel should be available to mine.

**Actual Behavior**
Only the default ores are shown.

**Screenshots**
![Screenshot 2023-07-06 213938](https://github.com/zymex22/Project-RimFactory-Revived/assets/138834321/2bd38dda-8564-465e-9f37-e3ff015a6369)

**Rimworld (please complete the following information):**
 - RimWorld Version: Latest on Steam as of 6th of July
 - PRF Version: Latest on Steam as of 6th of July
 - Link to gist bug report: https://gist.github.com/HugsLibRecordKeeper/5c92bbfeeafd9274293fbe0eca3b56a8
 - Type: Feature not working
 - Severity: Mild
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: Yes
 - Your modlist (if needed): https://pastebin.com/td52FuK0
 - Do you know what mod conflicts?: No

**Additional context**
This is from a save I made in a different computer with the same load order. I installed Windows, downloaded RimPy, imported my load order, and copied the config files, but after booting the game, the machine wasn't mining the ores that should be mined.

**Save File**
https://we.tl/t-YH7Q4pw7MC

**Comment by pc-rig** [comment]
Another note: it might be a problem with the mods I added after making that save. The load order is different from the save.

**Comment by Sn1p3rr3c0n** [comment]
Two things:
1. Did you restart the game after changing the settings?
2. Please sort your mod list (Use Rimpy or RimSort)

**Comment by pc-rig** [comment]
I did do both of those things.

**Comment by pc-rig** [comment]
I removed all the mods added between saves and it started working again. I added them back one by one and it kept working for some reason. I think it might be the brainwash chair mod, but I'm really not sure. 
Here's an updated log, might not be useful since it fixed itself: https://gist.github.com/HugsLibRecordKeeper/c2a2fae23acb9cc568589340179c1907

**Comment by Sn1p3rr3c0n** [comment]
Issue resolved. Closing
