### ISSUE TITLE
VE Season Timeskip / "increment time" Command - breaking `AutoMachineTool` Type buildings

### ISSUE THREAD

**Issue by Sn1p3rr3c0n** [zymex22/Project-RimFactory-Revived#726]
There are some reports form the Rimworld Discord that the `Season Timeskip` included in [Vanilla Psycasts Expanded](https://steamcommunity.com/workshop/filedetails/?id=2842502659) breaks the Belts.

Going back to the main menu reportedly resolves the issue.

Reports by: `Masao, Seeker of Monster Girls` _maybe more but I can't locate them now_

According to `OscarPotocki` that ability uses the Vanila dev command "increment time"

_At this time I have not tested this myself_

**Comment by Sn1p3rr3c0n** [comment]
This issue appears to affect all `AutoMachineTool` Type Buildings

**Comment by legodude17** [comment]
I'd say it works more like the fast ecology dev option. Patching `GenDate.Season` would have a performance impact, especially given it's called in the UI code which runs every frame. It would also require setting up a data structure for tracking how many season have been skipped.

**Comment by Sn1p3rr3c0n** [comment]
fair point
