### ISSUE TITLE
 (Bug report) - Blank interface on overlock tabs or tabs that use sliders

### ISSUE THREAD

**Issue by dgloveruk** [zymex22/Project-RimFactory-Revived#734]
# Describe the bug
Firstly thank you [IoD]Sn1p3rr3c0n for responding to my post on Steam and suggesting I verify my game files.  I did this but there were no issues detecte and the bug persisted. 
Basically any construction that uses a slider in the overclock or similar tab e.g the assemblers, some of the drone towers that have variable range, the interface tabs come up blank.  Strangely I have seen on occasion that they will start working again part way through a game but most of the time they are blank.

**To Reproduce**
Reproducibility: ?
1. Create a new game
2. Used developer mode to drop an assembler
3. Click overclock tab

**Expected behavior**
Overclock tab to show interface and sliders for range/overclock

**Actual Behavior**
Overclock tabs are blank.

**Screenshots**
I have attached screenshots which include an error I get when starting, the mods active which is literally just bio, 1.4 core , rimfactory revived, harmony and the screen that shows the harmony error which seems central since it comes up when you click the overclock tab and contains a reference to the sliders which don't show.  Since the error seemed directed towards harmony I have tried unsubscribing harmony, restarting and resubscribing but to no avail.
I have attached my test save game in case it is somehow useful.
This issue is not present if I roll back to 1.3.

**Rimworld (please complete the following information):**
 - RimWorld Version:1.4.3563
 - Harmony v2.2.2.0 mod v1.5.0.0

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: yes

**Additional context**
![20230823232830_1](https://github.com/zymex22/Project-RimFactory-Revived/assets/24853746/b8232640-41dc-4f5c-a3cc-e98e4831068d)
![20230823232855_1](https://github.com/zymex22/Project-RimFactory-Revived/assets/24853746/8c1952c5-85e0-4b11-931d-8c21da5fee1b)
![20230823232900_1](https://github.com/zymex22/Project-RimFactory-Revived/assets/24853746/0d3802de-ed5f-4780-ae2b-c20cb8d09c20)
![20230823232925_1](https://github.com/zymex22/Project-RimFactory-Revived/assets/24853746/1587c6ba-ee9b-4bd7-86f7-8520e01a3e13)
![20230823232815_1](https://github.com/zymex22/Project-RimFactory-Revived/assets/24853746/e09983c0-eb39-4725-ae8f-d692168b9eb8)

Thanks,

**Comment by Sn1p3rr3c0n** [comment]
You are running an Outdated 1.4 Version.
The current Version is 1.4.3704 rev 896.
Updating your Game should resolve all shown errors

**Comment by dgloveruk** [comment]
![Capture](https://github.com/zymex22/Project-RimFactory-Revived/assets/24853746/ed3a5253-9b30-44ee-8577-089da651f4cd)
Oh my goodness, what a fool I am.  
Sorry, all these years I have been having niggles and its probably because when I have always tried the 'latest' version, I have simply gone to the bottom of the list in Steam..... not realising there was a 'None' at the top!
Sorry to waste your time, I thought there must be something stupid and particular to my computer... didn't realise it was stupid and particular to me!
Cheers,
