### ISSUE TITLE
(Request) seedsplease:lite

### ISSUE THREAD

**Issue by energy11a** [zymex22/Project-RimFactory-Revived#739]
**Is your feature request related to a problem? Please describe.**
Autofarmers dont need seeds to plant.
**Describe the solution you'd like**
I'd like to have mod Seedsplease:lite (https://steamcommunity.com/sharedfiles/filedetails/?id=2586052937) have its seeds required for autofarmers when the mod is loaded. Like the original mod SeedsPlease.

**Comment by Sn1p3rr3c0n** [comment]
What do you mean by `Autofarmers` ?

**Comment by energy11a** [comment]
drone cultivators and nano cultivators

**Comment by Sn1p3rr3c0n** [comment]
well those do require seeds to work with that mod.
If they don't work like that for you please attach a [HugsLib Log](https://github.com/zymex22/Project-RimFactory-Revived/wiki/How-to-Report#a-hugslib-log)

**Comment by energy11a** [comment]
[HugsLib][ERR] Exception during PrepareLogData: System.UnauthorizedAccessException: Access to the path "C:\Users\User\AppData\Local\Temp\tmp1aecfdb4.tmp" is denied.
  at System.IO.File.Delete (System.String path) [0x00073] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at HugsLib.Logs.LogPublisher.GetLogFileContents () [0x0004d] in <4a46802aeab646ab99159f7eecb6b57e>:0 
  at HugsLib.Logs.LogPublisher.PrepareLogData () [0x00002] in <4a46802aeab646ab99159f7eecb6b57e>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch3 (string)
HugsLib.Utils.ModLogger:ReportException (System.Exception,string,bool,string)
HugsLib.Logs.LogPublisher:PrepareLogData ()
HugsLib.Logs.LogPublisher:CopyToClipboard ()
HugsLib.Logs.Dialog_PublishLogsOptions:DoWindowContents (UnityEngine.Rect)
Verse.Window:InnerWindowOnGUI (int)
UnityEngine.GUI:CallWindowDelegate (UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle)

**Comment by Sn1p3rr3c0n** [comment]
@energy11a are you sure you have https://steamcommunity.com/sharedfiles/filedetails/?id=2873415404 Installed?
If that always occurs when you attempt to generate a log, you would probably want to report it to the author.

In case you are unable to upload a HugsLib Log:
Post a Rentry Link (Generate it with rimpy)
and upload your player log content to a Gist posting the link here (https://gist.github.com/)

**Comment by energy11a** [comment]
mods https://rentry.co/qim59b
player.log https://gist.github.com/energy11a/fff4c583ee2cfcd60903388e1625a848
mod load order https://gist.github.com/energy11a/5c0c15199923a340840ffa210dbbd3b7

**Comment by Sn1p3rr3c0n** [comment]
You are running an Outdated Rimworld Version the current version is `1.4.3704 rev896` you are on `1.4.3580 rev1304`.
Please also make sure that your modlist is sorted with Rimpy or Rimsort

**Comment by energy11a** [comment]
It was sorted with rimpy

**Comment by Sn1p3rr3c0n** [comment]
Great, Does the issue still occur when using the current Rimworld version?
I can't see the mod version in your files. can you please also verify that Rimfactory is up to date?

**Comment by energy11a** [comment]
Upgrading rimfactory fixed it. I was usinng build from late august. Thanks for help.
