### ISSUE TITLE
T1 Miner Fueled

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#74]
Change T1 miner to be fueled (dont work atm because thinclass dont support vanilla fueled comp)

Nobo made some progress on it but used Normal Tick
LWM want to use Rare tick to increase performance

Both examples are included in link below and need to be put together and implemented

info here
https://github.com/nullre/Project-RimFactory-Revived/issues/55

**Comment by lilwhitemouse** [comment]
Note: earlier commit was based on https://github.com/nullre/Project-RimFactory-Revived/issues/55

**Comment by zymex22** [comment]
i Tried download an build branch Issue 74.
and remove power and add fueled comp.

i noticed it was complaining about tickertype...
apparently old one was Long tick and new are Rare

Should it be changed back to Long tick or should we go with Rare now?

**Comment by zymex22** [comment]
Should be good now ? and implemented into master.

its changed from rare into Long tick instead, we'll see if thats good
