### ISSUE TITLE
Pawns will not haul resource from I/O Port IF AND ONLY IF the building requires more than material present on all I/O port

### ISSUE THREAD

**Issue by girisado** [zymex22/Project-RimFactory-Revived#759]
**Bug description**
Pawns will not haul resources to building if the resource available in the map, not including archival storage, is less than the resource required.

**To Reproduce**
1. **IF** a building requires 2000 steel to build
2. **AND** there are 2 I/O ports which holds **1 STACK OF STEEL EACH**
3. **AND** there are a total of 2 stacks of **STEEL** (1 stack = 750) which results in **1500** **STEEL** in the map,
4. **THEN AND ONLY THEN* the pawns will not haul to the building even if there are more than 2000 steel required available in the **ARCHIVAL STORAGE UNIT**.

**Expected behavior**
Pawns will haul from the I/O port since there are more than enough steel to build the building available **in the archival storage**.

**Actual Behavior**
Pawns will not haul at all even if there are enough resources in the archival storage, as long as the resource on the map is less than required to build.

**Screenshots**

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.4.3901
 - PRF Version: 2.8.1
 - Link to gist bug report: 
 - Type: Hauling, resource, building
 - Severity: minor
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: Unsure
 - Your modlist (if needed): Version: 0
Mods:
- Id: zetrith.prepatcher
  Name: Prepatcher
  SteamWorkshopId: 2934420800
- Id: brrainz.harmony
  Name: Harmony
  SteamWorkshopId: 2009463077
- Id: bs.fishery
  Name: Fishery - Modding Library
  SteamWorkshopId: 0
- Id: ludeon.rimworld
  Name: Core
  SteamWorkshopId: 0
- Id: bs.performance
  Name: Performance Fish
  SteamWorkshopId: 0
- Id: ludeon.rimworld.royalty
  Name: Royalty
  SteamWorkshopId: 0
- Id: ludeon.rimworld.ideology
  Name: Ideology
  SteamWorkshopId: 0
- Id: ludeon.rimworld.biotech
  Name: Biotech
  SteamWorkshopId: 0
- Id: unlimitedhugs.hugslib
  Name: HugsLib
  SteamWorkshopId: 818773962
- Id: owlchemist.cherrypicker
  Name: Cherry Picker
  SteamWorkshopId: 2633276599
- Id: neptimus7.progressrenderer
  Name: Progress Renderer
  SteamWorkshopId: 2010777010
- Id: fluffy.modmanager
  Name: Mod Manager
  SteamWorkshopId: 1507748539
- Id: v1024.ebframework
  Name: Elite Bionics Framework
  SteamWorkshopId: 1665403571
- Id: isorex.communityframework
  Name: Community Framework
  SteamWorkshopId: 2585162118
- Id: oskarpotocki.vanillafactionsexpanded.core
  Name: Vanilla Expanded Framework
  SteamWorkshopId: 2023507013
- Id: bs.oversizedapparel
  Name: Oversized Apparel Framework
  SteamWorkshopId: 2630800313
- Id: carnysenpai.enableoversizedweapons
  Name: Enable Oversized Weapons
  SteamWorkshopId: 2543371889
- Id: imranfish.xmlextensions
  Name: XML Extensions
  SteamWorkshopId: 2574315206
- Id: mlie.feedingtubes
  Name: Feeding Tubes (Continued)
  SteamWorkshopId: 2590309006
- Id: sarg.alphagenes
  Name: Alpha Genes
  SteamWorkshopId: 2891845502
- Id: danielwedemeyer.generipper
  Name: Gene Ripper
  SteamWorkshopId: 2885485814
- Id: nibato.autoextractgenes
  Name: AutoExtractGenes
  SteamWorkshopId: 2882834449
- Id: redundant.oopsallgenepacks
  Name: Oops All Gene Banks
  SteamWorkshopId: 2883683444
- Id: waether.geneextractionqol.dev
  Name: Gene Extraction QOL
  SteamWorkshopId: 2882743092
- Id: kathanon.growthaccelerator
  Name: Growth Accelerator
  SteamWorkshopId: 2994273559
- Id: nals.facialanimation
  Name: '[NL] Facial Animation - WIP'
  SteamWorkshopId: 1635901197
- Id: nals.facialanimationexperimentals
  Name: '[NL] Facial Animation - Experimentals'
  SteamWorkshopId: 2581693737
- Id: erdelf.humanoidalienraces
  Name: Humanoid Alien Races
  SteamWorkshopId: 839005762
- Id: velc.hatsdisplayselection
  Name: Hats Display Selection
  SteamWorkshopId: 1542291825
- Id: nals.compatiblebody2
  Name: '[NL] Compatible Body 2'
  SteamWorkshopId: 1906148376
- Id: nals.realisticbody
  Name: '[NL] Realistic Body'
  SteamWorkshopId: 2820615654
- Id: nalsnoir.apparelpaperpattern
  Name: '[NL] Apparel Paper Pattern'
  SteamWorkshopId: 2480887589
- Id: nalsnoir.appcompatiblebody2
  Name: '[NL] Apparel Paper Pattern for Compatible Body 2'
  SteamWorkshopId: 2480905277
- Id: tammybee.appearanceclothes
  Name: Appearance clothes
  SteamWorkshopId: 1537867047
- Id: tammybee.appearanceclothes.alienracespatch
  Name: Appearance clothes - Humanoid Alien Races Patch
  SteamWorkshopId: 2086669503
- Id: jintuzilamian.hairstyle.afumenshairstyles
  Name: AFU男士发型_Men's hairstyles
  SteamWorkshopId: 2072106893
- Id: jintuzilamian.hairstyle.afuwomenshairstyles
  Name: AFU女士发型_Women's hairstyles
  SteamWorkshopId: 2020779666
- Id: mlie.gopnivanillahairreplace
  Name: GOPNI VanillaHair Replace (Continued)
  SteamWorkshopId: 2039018341
- Id: ayameduki.harqualeela
  Name: '[1.4]Qualeela Race'
  SteamWorkshopId: 2763078885
- Id: ayameduki.harnearmare
  Name: '[1.4]Nearmare Race'
  SteamWorkshopId: 2198830432
- Id: belvaleth.nearmare.englishtranslation
  Name: Nearmare Race[English Translation]
  SteamWorkshopId: 2804450452
- Id: ayameduki.haridearn
  Name: '[1.4]Idearn Race'
  SteamWorkshopId: 2871413100
- Id: ayameduki.haridhale
  Name: '[1.4]Idhale Race'
  SteamWorkshopId: 2227425882
- Id: ayarace.facialanimation
  Name: Ayameduki Race Facial Animation
  SteamWorkshopId: 2875882493
- Id: yuki.noharhairsonhumans
  Name: No HAR Hairs on Humans
  SteamWorkshopId: 2770999870
- Id: gilieart.beautifulbodyapparel
  Name: Female Apparel for Beautiful Bodies
  SteamWorkshopId: 2881748658
- Id: rimsenal.core
  Name: Rimsenal - Core
  SteamWorkshopId: 725947920
- Id: vanillaexpanded.vpersonaweaponse
  Name: Vanilla Persona Weapons Expanded
  SteamWorkshopId: 2826922787
- Id: nephlite.carryalls
  Name: Carryalls | Intercontinental Transport
  SteamWorkshopId: 2901034783
- Id: teok25.archotechexpanded
  Name: Archotech Expanded
  SteamWorkshopId: 1442734859
- Id: v1024.elitearchotech
  Name: Elite Archotech
  SteamWorkshopId: 1744648077
- Id: vat.epoeforked
  Name: Expanded Prosthetics and Organ Engineering - Forked
  SteamWorkshopId: 1949064302
- Id: vat.epoeforkedroyalty
  Name: 'EPOE-Forked: Royalty DLC expansion'
  SteamWorkshopId: 2008970276
- Id: 004gp.internalarmorplatesepoe
  Name: Internal Armor Plates EPOE
  SteamWorkshopId: 2103181887
- Id: turnovus.morebionicimplants
  Name: Simply More Implants
  SteamWorkshopId: 2616600036
- Id: xrushha.superbprosthetics
  Name: Superb Prosthetics
  SteamWorkshopId: 2714931682
- Id: mrkociak.yetanotherprostheticexpansionmodcore
  Name: Yet another prosthetic expansion mod - Core
  SteamWorkshopId: 2808872704
- Id: mlie.prostheticnomissingbodyparts
  Name: Prosthetic No Missing Body Parts (Continued)
  SteamWorkshopId: 2739055353
- Id: grimm.unlimited
  Name: Un-Limited
  SteamWorkshopId: 1668141382
- Id: statistno1.evolvedorgansredux
  Name: EvolvedOrgansRedux
  SteamWorkshopId: 2424381146
- Id: grimworld.melee
  Name: 'Grimworld: Melee'
  SteamWorkshopId: 2899647650
- Id: neru.yayo
  Name: YAYO EMPIRE
  SteamWorkshopId: 2917215986
- Id: andery233xj.mod.mechanicalpoweredarmor
  Name: XVI-MECHFRAME
  SteamWorkshopId: 2844617885
- Id: cp.rimmunation.2.weapons
  Name: '[RH2] Rimmu-Nation² - Weapons'
  SteamWorkshopId: 2563507593
- Id: cp.rimmunation.2.security
  Name: '[RH2] Rimmu-Nation² - Security'
  SteamWorkshopId: 2563504596
- Id: cp.rimmunation.2.clothing
  Name: '[RH2] Rimmu-Nation² - Clothing'
  SteamWorkshopId: 2563506048
- Id: jangodsoul.archotech.powerarmor
  Name: Archotech PowerArmor
  SteamWorkshopId: 2844715384
- Id: ogliss.ykara.harvesteverything
  Name: Harvest Everything!
  SteamWorkshopId: 2007485974
- Id: mersid.powertab
  Name: Power Tab
  SteamWorkshopId: 2503083820
- Id: automatic.bionicicons
  Name: Bionic icons
  SteamWorkshopId: 1677616980
- Id: owlchemist.fridgeutilities
  Name: 'Simple Utilities: Fridge'
  SteamWorkshopId: 2645100914
- Id: rimfridge.kv.rw
  Name: RimFridge Updated
  SteamWorkshopId: 2878183338
- Id: lwm.deepstorage
  Name: LWM's Deep Storage
  SteamWorkshopId: 1617282896
- Id: murmur.walllight
  Name: Wall Light
  SteamWorkshopId: 1423699208
- Id: vanillaexpanded.vfecore
  Name: Vanilla Furniture Expanded
  SteamWorkshopId: 1718190143
- Id: vanillaexpanded.varme
  Name: Vanilla Armour Expanded
  SteamWorkshopId: 1814988282
- Id: vanillaexpanded.vappe
  Name: Vanilla Apparel Expanded
  SteamWorkshopId: 1814987817
- Id: vanillaexpanded.vwe
  Name: Vanilla Weapons Expanded
  SteamWorkshopId: 1814383360
- Id: oskarpotocki.vfe.mechanoid
  Name: Vanilla Factions Expanded - Mechanoids
  SteamWorkshopId: 2329011599
- Id: oskarpotocki.vfe.insectoid
  Name: Vanilla Factions Expanded - Insectoids
  SteamWorkshopId: 2149755445
- Id: vanillaexpanded.vfea
  Name: Vanilla Factions Expanded - Ancients
  SteamWorkshopId: 2654846754
- Id: spdskatr.projectrimfactory
  Name: Project RimFactory Revived
  SteamWorkshopId: 2033979700
- Id: spdskatr.projectrimfactory.drones
  Name: Project RimFactory - Drones
  SteamWorkshopId: 2037491557
- Id: com.spdskatr.projectrimfactory.insanity
  Name: Project RimFactory - Insanity
  SteamWorkshopId: 2037492036
- Id: vanillaexpanded.vanillatraitsexpanded
  Name: Vanilla Traits Expanded
  SteamWorkshopId: 2296404655
- Id: vanillaexpanded.vpsycastse
  Name: Vanilla Psycasts Expanded
  SteamWorkshopId: 2842502659
- Id: vanillaexpanded.vaeaccessories
  Name: Vanilla Apparel Expanded — Accessories
  SteamWorkshopId: 2521176396
- Id: mlie.rimworldspartanfoundry
  Name: 'Rimworld: Spartan Foundry (Continued)'
  SteamWorkshopId: 2562018758
- Id: mlie.spartanfoundrywarcraft
  Name: Spartan Foundry Warcraft (Continued)
  SteamWorkshopId: 2024346916
- Id: mlie.halorimworldpsychicpulsearmory
  Name: 'HALO: Rimworld Psychic Pulse Armory (Continued)'
  SteamWorkshopId: 2266844058
- Id: vanillaexpanded.vbookse
  Name: Vanilla Books Expanded
  SteamWorkshopId: 2193152410
- Id: vanillaexpanded.vplantse
  Name: Vanilla Plants Expanded
  SteamWorkshopId: 2134308522
- Id: vanillaexpanded.vfefarming
  Name: Vanilla Furniture Expanded - Farming
  SteamWorkshopId: 1957158779
- Id: vanillaexpanded.vfearchitect
  Name: Vanilla Furniture Expanded - Architect
  SteamWorkshopId: 2608762624
- Id: vanillaexpanded.vfeart
  Name: Vanilla Furniture Expanded - Art
  SteamWorkshopId: 1968134023
- Id: vanillaexpanded.vfespacer
  Name: Vanilla Furniture Expanded - Spacer Module
  SteamWorkshopId: 2028381079
- Id: vanillaexpanded.vfemedical
  Name: Vanilla Furniture Expanded - Medical Module
  SteamWorkshopId: 1718191613
- Id: vanillaexpanded.vfepower
  Name: Vanilla Furniture Expanded - Power
  SteamWorkshopId: 2062943477
- Id: vanillaexpanded.vfeproduction
  Name: Vanilla Furniture Expanded - Production
  SteamWorkshopId: 1880253632
- Id: vanillaexpanded.vfepropsanddecor
  Name: Vanilla Furniture Expanded - Props and Decor
  SteamWorkshopId: 2102143149
- Id: vanillaexpanded.vfesecurity
  Name: Vanilla Furniture Expanded - Security
  SteamWorkshopId: 1845154007
- Id: owlchemist.wallutilities
  Name: 'Simple Utilities: Wall'
  SteamWorkshopId: 2565545335
- Id: vanillaexpanded.helixiengas
  Name: Vanilla Helixien Gas Expanded
  SteamWorkshopId: 2877699803
- Id: vanillaexpanded.vchemfuele
  Name: Vanilla Chemfuel Expanded
  SteamWorkshopId: 2792917473
- Id: vanillaexpanded.vwenl
  Name: Vanilla Weapons Expanded - Non-Lethal
  SteamWorkshopId: 2454918354
- Id: vanillaexpanded.vweg
  Name: Vanilla Weapons Expanded - Grenades
  SteamWorkshopId: 2194472657
- Id: vanillaexpanded.vwec
  Name: Vanilla Weapons Expanded - Coilguns
  SteamWorkshopId: 2375692535
- Id: vanillaexpanded.vwel
  Name: Vanilla Weapons Expanded - Laser
  SteamWorkshopId: 1989352844
- Id: vanillaexpanded.vwehw
  Name: Vanilla Weapons Expanded - Heavy Weapons
  SteamWorkshopId: 2329126791
- Id: vanillaexpanded.vweq
  Name: Vanilla Weapons Expanded - Quickdraw
  SteamWorkshopId: 1906780517
- Id: vanillaexpanded.vwems
  Name: Vanilla Weapons Expanded - Makeshift
  SteamWorkshopId: 2419690698
- Id: vanillaexpanded.vwetb
  Name: Vanilla Weapons Expanded - Tribal
  SteamWorkshopId: 2454918552
- Id: vanillaexpanded.vweft
  Name: Vanilla Weapons Expanded - Frontier
  SteamWorkshopId: 2454918139
- Id: vanillaexpanded.skills
  Name: Vanilla Skills Expanded
  SteamWorkshopId: 2854967442
- Id: flangopink.vanillaxcomweapons
  Name: Vanilla XCOM Weapons
  SteamWorkshopId: 2831331035
- Id: halituisamaricanous.vswbeam
  Name: Vanilla Spacer weapons - Beam Gun
  SteamWorkshopId: 2906455995
- Id: halituisamaricanous.vswebolt
  Name: Vanilla Spacer weapons - Explosive Bolt
  SteamWorkshopId: 2906456426
- Id: oskarpotocki.vfe.pirates
  Name: Vanilla Factions Expanded - Pirates
  SteamWorkshopId: 2723801948
- Id: vanillaexpanded.vtexe
  Name: Vanilla Textures Expanded
  SteamWorkshopId: 2016436324
- Id: vanillaexpanded.vtexvariations
  Name: Vanilla Textures Expanded - Variations
  SteamWorkshopId: 2493234474
- Id: vanillaexpanded.basegeneration
  Name: Vanilla Base Generation Expanded
  SteamWorkshopId: 2830358905
- Id: vanillastorytellersexpanded.winstonwave
  Name: Vanilla Storytellers Expanded - Winston Waves
  SteamWorkshopId: 2734032569
- Id: aoba.warcasket
  Name: WarCasket Expanded
  SteamWorkshopId: 2733135485
- Id: aa.warcaskets.rw
  Name: 'Ancient Arsenal: Warcaskets'
  SteamWorkshopId: 2904745733
- Id: aoba.fortress.industrial
  Name: Fortifications - Industrial
  SteamWorkshopId: 2561619583
- Id: aoba.fortress.industrial.citadel
  Name: Fortification Industrial - Citadel
  SteamWorkshopId: 2887532326
- Id: aoba.fortress.industrial.nucleardawn
  Name: Fortification Industrial -Nuclear Dawn
  SteamWorkshopId: 2733185331
- Id: aoba.rtg
  Name: Radioisotope Thermoelectric Generator
  SteamWorkshopId: 2523966486
- Id: aoba.cargocontainer
  Name: Cargo container
  SteamWorkshopId: 2725808118
- Id: aoba.gekko
  Name: Metal Gear Rimworld-Gekko
  SteamWorkshopId: 2886259577
- Id: brassy.sfguns.vanilla
  Name: "Girl's Frontline: Sangvis Ferri Weapons"
  SteamWorkshopId: 1684134687
- Id: petetimessix.simplesidearms
  Name: Simple sidearms
  SteamWorkshopId: 927155256
- Id: syrus.simplesidearmsswitchweapon
  Name: Simple Sidearms - Switch Weapon
  SteamWorkshopId: 2652962609
- Id: kost.astartes
  Name: Astartes
  SteamWorkshopId: 2844173597
- Id: kost.custodes
  Name: Custodes
  SteamWorkshopId: 2900590143
- Id: statistno1.nolowerpsyfocuslimit
  Name: No lower Psyfocus limit
  SteamWorkshopId: 2570726278
- Id: zirc.nonaturalpsyfocusdecrease
  Name: No Natural Psyfocus Decrease
  SteamWorkshopId: 2448505614
- Id: rh.doom
  Name: '[RH2] DOOM'
  SteamWorkshopId: 2875842250
- Id: rimsenal.techist
  Name: Rimsenal Style Pack - Techist
  SteamWorkshopId: 2661828028
- Id: rimsenal.urb
  Name: Rimsenal Style Pack - Urbworld
  SteamWorkshopId: 2908039338
- Id: petre27.mechcaller
  Name: Mech Caller
  SteamWorkshopId: 2881974849
- Id: hol.brrt
  Name: Brrrt
  SteamWorkshopId: 2655326110
- Id: aoba.brrt.retexture
  Name: Brrrt-Retexturrrre
  SteamWorkshopId: 2798333568
- Id: elstrages.hydroponicsextended
  Name: Hydroponics Extended
  SteamWorkshopId: 2811289866
- Id: smartkar.enhancedvatlearning
  Name: Enhanced Vat Learning
  SteamWorkshopId: 2908453851
- Id: dark.cloning
  Name: Biotech Cloning
  SteamWorkshopId: 2881790485
- Id: dubwise.rimefeller
  Name: Rimefeller
  SteamWorkshopId: 1321849735
- Id: frozensnowfox.complexjobs
  Name: '[FSF] Complex Jobs'
  SteamWorkshopId: 2069684319
- Id: blackfranky.capableslaves
  Name: Capable Slaves
  SteamWorkshopId: 2870120550
- Id: bustedbunny.slaverebellionsimproved
  Name: Slave Rebellions Improved
  SteamWorkshopId: 2601801303
- Id: ultraemailman.moremechanitormechs
  Name: '[UEM] More Mechanitor Mechs'
  SteamWorkshopId: 2880075558
- Id: pal5k.logisticsmechanoid
  Name: Logistics_Mechanoid
  SteamWorkshopId: 2885430743
- Id: ratys.rtsolarflareshield
  Name: RT Solar Flare Shield
  SteamWorkshopId: 728315620
- Id: bart.app
  Name: Advanced Pollution Pump
  SteamWorkshopId: 2903717987
- Id: 3hstltd.signs
  Name: Bill Doors' Simple Signs
  SteamWorkshopId: 2905097730
- Id: bichang.moresculpture
  Name: More Sculpture
  SteamWorkshopId: 1612316880
- Id: tammybee.selectablesculpturegraphic
  Name: Selectable Sculpture Graphic
  SteamWorkshopId: 1537873717
- Id: owlchemist.ceilingutilities
  Name: 'Simple Utilities: Ceiling'
  SteamWorkshopId: 2571003732
- Id: owlchemist.windows
  Name: Windows
  SteamWorkshopId: 2571189146
- Id: telkir.tmods.morefloors
  Name: '[T] MoreFloors 1.4'
  SteamWorkshopId: 2878200208
- Id: owlchemist.simplefx.vapor
  Name: 'Simple FX: Vapor'
  SteamWorkshopId: 2886571275
- Id: owlchemist.toggleablereadouts
  Name: Toggleable Readouts
  SteamWorkshopId: 2661792499
- Id: owlchemist.simplefx.splashes
  Name: 'Simple FX: Splashes'
  SteamWorkshopId: 2889330414
- Id: owlchemist.scatteredflames
  Name: Scattered Flames
  SteamWorkshopId: 2652749788
- Id: owlchemist.perspectivebuildings
  Name: 'Perspective: Buildings'
  SteamWorkshopId: 2594383552
- Id: doctorstupid.sofa
  Name: Literally just a sofa
  SteamWorkshopId: 2894560149
- Id: limetreesnake.systems
  Name: '[LTS]Systems'
  SteamWorkshopId: 2812826451
- Id: limetreesnake.furnishing
  Name: '[LTS]Furnishing'
  SteamWorkshopId: 2567438519
- Id: zzz.invisibleconduit
  Name: Invisible Conduit
  SteamWorkshopId: 2013416365
- Id: stolij.morebatteries
  Name: More Batteries
  SteamWorkshopId: 747397788
- Id: dracoix.doormat.r12a
  Name: Door Mat
  SteamWorkshopId: 1505423207
- Id: nephlite.orbitaltradecolumn
  Name: Utility Columns
  SteamWorkshopId: 2013476665
- Id: dubwise.rimatomics
  Name: Dubs Rimatomics
  SteamWorkshopId: 1127530465
- Id: phonicmas.biotechexpansionwarhammer40k
  Name: Warhammer 40k - Genes and Psycasts
  SteamWorkshopId: 2880152795
- Id: aoba.geryknights
  Name: RimHammer40k - GreyKnights [PATCHED]
  SteamWorkshopId: 2901292852
- Id: aoba.geryknights.dreadnought
  Name: RimHammer40k -Dreadnought
  SteamWorkshopId: 2744972802
- Id: neronix17.embrasures
  Name: Seamless Embrasures
  SteamWorkshopId: 2290689449
- Id: ratys.rtfuse
  Name: RT Fuse
  SteamWorkshopId: 728314182
- Id: frozensnowfox.meditationfreedomnostory
  Name: '[FSF] Meditation Freedom (No Backstory Change)'
  SteamWorkshopId: 2578656876
- Id: mlie.mechanoidpower
  Name: Mechanoid Power (Continued)
  SteamWorkshopId: 2013172430
- Id: neceros.dws.simpleturrets
  Name: Simple Turrets
  SteamWorkshopId: 2559263455
- Id: horo.mechaniteforge.11
  Name: Mechanite Forge
  SteamWorkshopId: 2559315390
- Id: generalm13.m13geothermalgenerators
  Name: M-13's Geothermal Generators
  SteamWorkshopId: 1541519278
- Id: mlie.centralizedclimatecontrol
  Name: Centralized Climate Control (Continued)
  SteamWorkshopId: 2007268173
- Id: gt.sam.tilledsoil
  Name: Tilled Soil
  SteamWorkshopId: 725747149
- Id: avilmask.grazinglands
  Name: Grazing Lands
  SteamWorkshopId: 1770268130
- Id: frozensnowfox.growablegrass
  Name: '[FSF] Growable Grass'
  SteamWorkshopId: 817350064
- Id: razor2.3.anotherrimworldmod.autocutblight
  Name: Auto-Cut Blight
  SteamWorkshopId: 1885186534
- Id: albion.sparklingworlds.full
  Name: Sparkling Worlds - Full Mod
  SteamWorkshopId: 1123043922
- Id: mehni.pickupandhaul
  Name: Pick Up And Haul
  SteamWorkshopId: 1279012058
- Id: brrainz.achtung
  Name: Achtung!
  SteamWorkshopId: 730936602
- Id: dhultgren.keepbedownership
  Name: Keep Bed Ownership
  SteamWorkshopId: 2130184293
- Id: mlie.thisismine
  Name: This Is Mine (Continued)
  SteamWorkshopId: 2560584629
- Id: avilmask.commonsense
  Name: Common Sense
  SteamWorkshopId: 1561769193
- Id: fluffy.blueprints
  Name: Blueprints
  SteamWorkshopId: 708455313
- Id: weilbyte.snapout
  Name: Snap Out!
  SteamWorkshopId: 1319782555
- Id: fluffy.pharmacist
  Name: Pharmacist Temporary 1.4 Update
  SteamWorkshopId: 2880823401
- Id: uuugggg.smartmedicine
  Name: Smart Medicine
  SteamWorkshopId: 1309994319
- Id: yoann.commonsenseopportunisticcleaningpatch
  Name: Common Sense - opportunistic cleaning patch
  SteamWorkshopId: 2822058610
- Id: forza.fasterworkmechs
  Name: Faster Workspeed for Mechs
  SteamWorkshopId: 2879057072
- Id: merthsoft.designatorshapes
  Name: Designator Shapes
  SteamWorkshopId: 1235181370
- Id: dubwise.dubsmintmenus
  Name: Dubs Mint Menus
  SteamWorkshopId: 1446523594
- Id: dubwise.dubsmintminimap
  Name: Dubs Mint Minimap
  SteamWorkshopId: 1662119905
- Id: dubwise.dubspaintshop
  Name: Dub's Paint Shop
  SteamWorkshopId: 1579516669
- Id: uveren.hemogenextractor
  Name: Hemogen Extractor
  SteamWorkshopId: 2903919607
- Id: alex.friendlyfiretweaks
  Name: Friendly Fire Tweaks
  SteamWorkshopId: 1582686191
- Id: fluffy.followme
  Name: Follow Me
  SteamWorkshopId: 715759739
- Id: smashphil.loadinginprogress
  Name: Loading In Progress
  SteamWorkshopId: 1975622772
- Id: monkey5206.carrycapacityfixed
  Name: Carry Capacity Fixed (Continued)
  SteamWorkshopId: 2880150945
- Id: calltradeships.kv.rw
  Name: '[KV] Call Trade Ships [1.4]'
  SteamWorkshopId: 0
- Id: wexman.mines
  Name: Mines
  SteamWorkshopId: 1545681321
- Id: kikohi.bettergroundpenetratingscanner
  Name: Better ground-penetrating scanner
  SteamWorkshopId: 2809972387
- Id: kikohi.coloreddeepresources
  Name: Colored deep resources
  SteamWorkshopId: 2791102835
- Id: uuugggg.buildfrominventory
  Name: Build From Inventory
  SteamWorkshopId: 1691419062
- Id: unon.noburnmetal
  Name: No Burn Metal
  SteamWorkshopId: 1923990111
- Id: hatti.qualitybuilder
  Name: QualityBuilder
  SteamWorkshopId: 754637870
- Id: brrainz.rangefinder
  Name: Range Finder
  SteamWorkshopId: 1332119637
- Id: uuugggg.replacestuff
  Name: Replace Stuff
  SteamWorkshopId: 1372003680
- Id: garethp.replacestuffcompatibility
  Name: Replace Stuff Mod Compatibility
  SteamWorkshopId: 2642161586
- Id: joseasoler.tradingoptions
  Name: Trading Options
  SteamWorkshopId: 2876541977
- Id: tikubonn.dontblockdoor
  Name: Don't Block Door
  SteamWorkshopId: 1691076769
- Id: notfood.mendandrecycle
  Name: MendAndRecycle
  SteamWorkshopId: 735241897
- Id: fluxilis.germanquality
  Name: Quality Affects HP
  SteamWorkshopId: 2898409109
- Id: bdew.cremateautostrip
  Name: Cremate Auto Strip
  SteamWorkshopId: 1575458517
- Id: lbmaian.begonemessage
  Name: Begone, Message!
  SteamWorkshopId: 1951637504
- Id: angryhornet.ed.enhancedoptions
  Name: ED-EnhancedOptions [1.4]
  SteamWorkshopId: 2897488240
- Id: brrainz.cameraplus
  Name: Camera+
  SteamWorkshopId: 867467808
- Id: kapitanoczywisty.changemapedge
  Name: Change map edge limit
  SteamWorkshopId: 1546494565
- Id: superniquito.traiticons
  Name: Trait and Backstory Icons
  SteamWorkshopId: 2873494547
- Id: ih.clean.textures
  Name: Clean Textures
  SteamWorkshopId: 2865361569
- Id: indeed.stackxxl
  Name: Stack XXL
  SteamWorkshopId: 826366050
- Id: kota.inventorytab
  Name: InventoryTab
  SteamWorkshopId: 1509278793
- Id: supes.autoseller.core
  Name: Auto Seller
  SteamWorkshopId: 1440321094
- Id: sarg.smartspeed
  Name: Smart Speed
  SteamWorkshopId: 1504723424
- Id: cassie.hiddeneyes
  Name: Hidden Eyes
  SteamWorkshopId: 2590369351
- Id: owlchemist.researchpowl
  Name: ResearchPowl
  SteamWorkshopId: 2877856030
- Id: 8z.moretradernames
  Name: Better Orbital Trader Names
  SteamWorkshopId: 2882857841
- Id: madarauchiha.custommapsizes
  Name: Better Map Sizes
  SteamWorkshopId: 2099101052
- Id: zylle.mapdesigner
  Name: Map Designer
  SteamWorkshopId: 2111424996
- Id: fluxilis.fluxilisdebugactions
  Name: Fluxilis Debug Actions
  SteamWorkshopId: 2898787033
- Id: void.charactereditor
  Name: Character Editor
  SteamWorkshopId: 1874644848
- Id: mlie.showmoddesignators
  Name: ShowModDesignators (Continued)
  SteamWorkshopId: 2891633620
- Id: taranchuk.moderrorchecker
  Name: Mod Error Checker
  SteamWorkshopId: 2877266511
- Id: krkr.rocketman
  Name: RocketMan - Performance Mod
  SteamWorkshopId: 2479389928
- Id: taranchuk.performanceoptimizer
  Name: Performance Optimizer
  SteamWorkshopId: 2664723367
- Id: dubwise.dubsperformanceanalyzer.steam
  Name: Dubs Performance Analyzer
  SteamWorkshopId: 2038874626

 - Do you know what mod conflicts?: No reports on the error log. Is this intended behavior?

**Additional context**
I wanted to know if this is 
A: intended behavior
B: limitations due to how vanilla handles hauling resources to buildings
C: limitations due to Rimfactory.

Thank you for your time.

**Comment by Sn1p3rr3c0n** [comment]
sounds like you need an additional IO Output Port.

**Comment by Sn1p3rr3c0n** [comment]
It's a Vanilla behavior that pawns only start hauling to a building if they have enough materials on the map.

Maybe you can find a mod that allows deliveries to a building where there are not enough recourses available on the map.
but thats an area of the game that we don't aim to alter.

The Archival Storage Unit is designed to "hide" items form the game, as if they don't exist.
this greatly reduced the impact of those Stacks but you can't have your cake and eat it too.

**Comment by girisado** [comment]
That's part of what I thought could be the problem. Nonetheless, thank you for taking your time to respond :)
