### ISSUE TITLE
T0 furnace Fueled comp

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#76]
Fueled comp need to be added to thingclass for assemblers to be able to use fueled comp on T0 Blast Furnace

it uses
`<thingClass>ProjectRimFactory.SAL3.Things.Assemblers.Building_SimpleAssembler</thingClass>`

https://github.com/zymex22/Project-RimFactory-Revived/blob/master/Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_SimpleAssembler.cs

def file here:
https://github.com/zymex22/Project-RimFactory-Revived/blob/master/Defs/ThingDefs_Buildings/Buildings_Industry.xml#L479

might be related to #74

**Comment by lilwhitemouse** [comment]
I recommend a lower electrical power requirement + the fuel comp, although I suppose fuel could power some basic machinery. So either way?

**Comment by zymex22** [comment]
i have pulled and seem to work i close this for now
