### ISSUE TITLE
1.5 Job errors (Startet 10 Jobs)

### ISSUE THREAD

**Issue by Sn1p3rr3c0n** [zymex22/Project-RimFactory-Revived#779]
Appears to occur on:

- Unpowered DSU
- Linked Advanced IO Port

**Comment by Sn1p3rr3c0n** [comment]
Also as reported by `Etiological Myth`
Standard IO Ports in output mode when the Limit Function is used

**Comment by Sn1p3rr3c0n** [comment]
For all but the Advanced Port I would suspect `Patch_ForbidUtility_IsForbidden` is no longer working as intended

**Comment by Sn1p3rr3c0n** [comment]
[joblog.txt](https://github.com/zymex22/Project-RimFactory-Revived/files/15210618/joblog.txt)

**Comment by Sn1p3rr3c0n** [comment]
> the haul jobs error also crops up if the i/o port is set to hold something that the DSU it is attached to is not set to store https://gist.github.com/HugsLibRecordKeeper/f0606b619417e371061e95983de04eb7

~`kitrana`

**Comment by yowshi** [comment]
i might need to amend my last report. review of the save showed I had forgotten that I set the limiter on the port that was causing the issue.

**Comment by Sn1p3rr3c0n** [comment]
more testing suggests that `Patch_Building_Storage_Accepts` gets ignored

**Comment by Sn1p3rr3c0n** [comment]
1.4 Function for reference
[HowItWorkedIn1_4.txt](https://github.com/zymex22/Project-RimFactory-Revived/files/15286465/HowItWorkedIn1_4.txt)

**Comment by Sn1p3rr3c0n** [comment]
Unexpectedly 73d3edf30f5699609a9c12e694319290a2a48c29 also fixed Linked Advanced IO Ports
