### ISSUE TITLE
 (Bug report) (1.5) XML error

### ISSUE THREAD

**Issue by Jigain** [zymex22/Project-RimFactory-Revived#785]
# Describe the bug
Upon launch, RimFactory generates 15 XML errors as well as 1 patch operation fail.

**To Reproduce**
Reproducibility: !
1. Enable all official DLC + Harmony + Project RimFactory Revived + Drones + Materials
2. ???
3. Profit

**Expected behavior**
Boot into main menu of the game without debug log popup

**Actual Behavior**
Boot into main menu of the game with debug log popup

**Screenshots**
N/A

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.5.4085
 - PRF Version: Update: 4 May @ 9:36am
 - Link to gist bug report: ???
 - Type: ????
 - Severity: ?????
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: Yes
 - Your modlist (if needed): 
    <activeMods>
        <li>brrainz.harmony</li>
        <li>ludeon.rimworld</li>
        <li>ludeon.rimworld.royalty</li>
        <li>ludeon.rimworld.ideology</li>
        <li>ludeon.rimworld.biotech</li>
        <li>ludeon.rimworld.anomaly</li>
        <li>spdskatr.projectrimfactory</li>
        <li>spdskatr.projectrimfactory.drones</li>
        <li>prf.materials</li>
    </activeMods>
 - Do you know what mod conflicts?: No conflict

**Additional context**
Debug log: https://pastebin.com/YBs7UEwy

**Comment by Sn1p3rr3c0n** [comment]
sounds like this is caused by Materials.
Please report it to that project instead: https://github.com/zymex22/Project-RimFactory-Revived-Materials
