### ISSUE TITLE
I don't see item puller Mk.I displayed.

### ISSUE THREAD

**Issue by Dibzzz** [zymex22/Project-RimFactory-Revived#789]
![Снимок экрана 2024-05-19 210232](https://github.com/zymex22/Project-RimFactory-Revived/assets/170261880/7d3d5df7-2419-4293-8d17-7f74a70564fd)

![2](https://github.com/zymex22/Project-RimFactory-Revived/assets/170261880/62ebc1a0-d3d7-410d-b7f6-2cc210832d3d)

In the industrial tab, there is no puller Mk.I.

Hello, everything is running smoothly without any errors whatsoever.

Game version 1.5.4085 (Steam version).

Missing mod items in the game.

Average seriousness.

My mods:
- Non uno Pinata (don't drop items) rus
- Non uno Pinata (don't drop items)
- Food Poisoning Stack Fix (Continued)
- Project RimFactory Revived
- XML Extensions
- Reinforced Walls (Continued)
- CleaningAreaTemp
- Vanilla Research Panel - Queue
- Resource Replicator 1.0->1.5
- JDS Simple Storage
- LWM's Deep Storage
- RimHUD
- Dubs Mint Menus
- Vehicle Framework
- Vanilla Expanded Framework
- Vanilla Vehicles Expanded - Tier 3
- Vanilla Vehicles Expanded - Tier 3 Russian
- Vanilla Vehicles Expanded
- EdB Prepare Carefully
- Replace Stuff
- Harmony
- Humanoid Alien Races
- HugsLib
- Camera+
- Enable Oversized Weapons

The issue also occurs if only PRF is installed.

**Comment by Sn1p3rr3c0n** [comment]
Try right clicking the grow zone Puller

**Comment by Dibzzz** [comment]
Thank you, damn it, what a f*cker I am

**Comment by Sn1p3rr3c0n** [comment]
FYI you can also turn off the grouping in the settings
