### ISSUE TITLE
PRF Drone overhaul (cultivator, drone station, mini drone station)

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#80]
### This will affact
**Drone cultivator**
- [x] haul to stockpile/crate within cultivator zone
- [x] drones stuck in hydroponics ? (bug)
- [x] support special plant (temperature/second harvest..)

**Mechanite cultivator**
what should future for theese be?
- range slider maybe?

**Drone station from PRF - drones addon mod**
- [x] if range are set to infinite there should be a button to select vanilla zone
- [x] able to set drones skill level from XML
- [ ] possibility to change drone texture without create a new pawntype for each?

**Mini drone station (new building for core)**
This is a mini drone station with 1-2 drones in it, that fit core more.
it will mainly be used for mod support, like rimatomics work types and fishing.
but might serve a turret refueling drone
- [x] Off times (to balance)
- [x] Range set by def
- [x] Range power slider
- [x] Drones amount

**Drone crate / dropoff spot** **_(delayed for now)_**
A special version of prf storage crate that only drones/pullers can access
- only drones/pullers can access
- drones will prefer to use if within range
- can be a spot placed over things, eq. belts/IO and such
- maybe even only place drones can pickup/dropoff from? dunno

**Drones in general**´
- [ ] Can backstories and other crap be turned off to have less logic to them
- [ ] Performance updates (can be abit laggy on too many drones)
- [x] should we disallow clicking on a drone?
- [x] Should we make a new itab for drone stations to control them.
- [x] Should we allow it to disallow worktypes it have assigned so "disallow hauling for cultivators" (could be in itab)
- [x] button to lockdown ALL drones at once (like misc robots) this is usefull in raids.

**Comment by zymex22** [comment]
maybe just add option to set max range to:
```
    <modExtensions>
      <li Class="ProjectRimFactory.Drones.DefModExtension_DroneStation">
        <displayDormantDrones>true</displayDormantDrones>
        <workTypes>
          <li>Firefighter</li>
          <li>BasicWorker</li>
          <li>Hauling</li>
          <li>Cleaning</li>
        </workTypes>
      </li>
    </modExtensions>
```

or add support for:
```
    <modExtensions>
      <li Class="ProjectRimFactory.CultivatorTools.CultivatorDefModExtension">
        <squareAreaRadius>5</squareAreaRadius>
      </li>
      <li Class="ProjectRimFactory.Drones.DefModExtension_DroneStation">
        <maxNumDrones>2</maxNumDrones>        <!-- How many drones should be used? -->
        <displayDormantDrones>true</displayDormantDrones>        <!-- Drones will sit on top while not working -->
      </li>
```

**Comment by zymex22** [comment]
updated original post.

should properly? just add:
```
<li Class="ProjectRimFactory.CultivatorTools.CultivatorDefModExtension">
<squareAreaRadius>5</squareAreaRadius>
```

to `<thingClass>ProjectRimFactory.Drones.Building_DroneStationRefuelable</thingClass>`
and ONLY set range if active/present else unlimited range, to not break prf - drone mod

**Comment by zymex22** [comment]
properly this?
```
        private List<IntVec3> GetCoverageCells()
        {
            int squareAreaRadius = def.GetModExtension<CultivatorDefModExtension>().squareAreaRadius;
            List<IntVec3> list = new List<IntVec3>((squareAreaRadius * 2 + 1) * (squareAreaRadius * 2 + 1));
            for (int i = -squareAreaRadius; i <= squareAreaRadius; i++)
            {
                for (int j = -squareAreaRadius; j <= squareAreaRadius; j++)
                {
                    list.Add(new IntVec3(i, 0, j) + Position);
                }
            }
            return list;
        }
```
from:
https://github.com/zymex22/Project-RimFactory-Revived/blob/master/Source/ProjectRimFactory/CultivatorTools/Building_DroneCultivator.cs

That need to go inside `ProjectRimFactory.Drones.Building_DroneStationRefuelable` or something =)

**Comment by zymex22** [comment]
i created a new branch for this and deleting old one, so its new format and not conflicting:
https://github.com/zymex22/Project-RimFactory-Revived/tree/Issue-%2380

**Comment by Sn1p3rr3c0n** [comment]
Remaining open Points:

Fix Issue:
- [ ] Error when Placing
- [ ] Disallow Player from manually changing the allowed Zone of individual drones

Add Features:
- [ ]  Work times (only work from 6am - 7pm for example) (configurable from XML)
- [ ]  Maybe? able to set specific drone texture/color?

**Comment by zymex22** [comment]
Feature should also be added:
- able to set drones skill level
- if range are set to infinite there should be a button to select vanilla zone

**Comment by zymex22** [comment]
we should maybe do a post with all change logs for this update, might be some time before going live and forgot some of the smaller things?

**Comment by Sn1p3rr3c0n** [comment]
@zymex22 I tried but i could not find a way to change the texture for the PawnDrone without a new PawnType.
@lilwhitemouse Do you know if that is possible / know how to do that?
`Graphic` as used by Buildings seems not work for Pawns.

**Comment by zymex22** [comment]
yea im not sure if it even can be done and also it might not even be very important right now, next big upgrade would be set levels i guess? =)

**Comment by Sn1p3rr3c0n** [comment]
- [ ] Add Comp to set if a Station will be spawned with drones inside on placement

**Comment by Sn1p3rr3c0n** [comment]
@zymex22 I added the Component as a part of `ProjectRimFactory.Drones.DefModExtension_DroneStation`
You can use one for the following implementations.
```
<spawnWithFullDrones>true</spawnWithFullDrones>
```
```
<spawnWithDrones>4</spawnWithDrones>
```

**Comment by zymex22** [comment]
will this btw be backward compatible with old placed cultivators and drone stations or will they need to be replaced?

**Comment by Sn1p3rr3c0n** [comment]
@zymex22 This will need testing. I would recommend to repeat that Testing when the PR is ready.
- [ ] Test the Upgrade Process from Master to this Version and document the Results

**Comment by zymex22** [comment]
@lilwhitemouse normally ive seen other mods doing drones are changing texture with creating a new drone/pawn/def/xml file and just change texture in there....
guess thats a option.

but i would like if we could get like a comp/modextension line kinda like "second layer comp"
where i could overwrite drones standard texture into another one, like a fire drone could be a red one or something.

so logic would be
a drone stations xml file can have a texture comp -> that comp can overwrite texture for drone pawns -> if not set it will just be normal drone pawn texture.

**Comment by Sn1p3rr3c0n** [comment]
@zymex22 what would be the intended behavior for a non refuel-able drone station in the event of a drone dying / getting killed?

**Comment by zymex22** [comment]
@Sn1p3rr3c0n hmmmm not sure?`

i guess it should just respawn back at drone station, because it doesn't have refuel comp?

maybe we should add a cooldown 60 seconds or something to create a new one? ill ask in discord

**Comment by zymex22** [comment]
not sure why...
but your language file in latest branch build don't work on buttons
![image](https://user-images.githubusercontent.com/41029070/93740507-e6b8a100-fbea-11ea-96c3-c4188a1ecd30.png)

same goes for info box:
![image](https://user-images.githubusercontent.com/41029070/93740559-0a7be700-fbeb-11ea-8ec9-199a3ff00010.png)
i looked in language file and names look to correspond to your C# edit you made so not sure why it doesn't work here

**Comment by Sn1p3rr3c0n** [comment]
- [ ] drone cultivator should have the X over it when its under lockdown

**Comment by Sn1p3rr3c0n** [comment]
- [ ] Add a scaling Power consumption to refuelable Drone Stations. More Drones = More required Power. (may have a minimum Consumption)
example: 200W base & 50W per drone.
_This is a non blocking addition_

**Comment by zymex22** [comment]
i think ill scale back a bit with new stuff, and lets just add new comps and xml for existing buildings like cultivators.
and then later when we have tested live and implemented all features i can add new drone stations and such.

i think thats a more safe start instead of a total overhaul of all drone buildings def and adding new ones.

what do you think @Sn1p3rr3c0n
so just:
- update drone cultivator to new system
- update prf - drones mod to support new core functions

and then later add more drone stations and such =)
this will let us see how it work out live before adding more =)

**Comment by zymex22** [comment]
playing a small playthrough with this branch to see if theres anything funny showing up

theese are some pointers i found so far:
- [ ] when power is off (no power on grid) drones that are send out will continue to work until they go back to station.
they should properly go back to station when power is lost?
- [ ] when you have eq. 5 drones out and working and clicking debug button it just list -5 drones stored and they will continue to be out until they have no more work.
- [ ] i had a wierd bug drones send out just went in loop pickup and dropping next cell, and another one where drones would just stand still and do nothing. this was a pretty big modlist and think its some kind of mod incompat it was in SoS2 but ill see if i can reproduce and make a full report.
- [ ] maybe we should make a debug button "respawn drones" which will destroy all drones out from that station, if they gets stuck like mine did, i had no way of call them back except use "debug kill" and click on them manually.
they did go away when i destroy drone station though.

- can we merge master into here to get latest master updates with it, or is that a mess to do?

**Comment by Sn1p3rr3c0n** [comment]
> i had a wierd bug drones send out just went in loop pickup and dropping next cell, and another one where drones would just stand still and do nothing. this was a pretty big modlist and think its some kind of mod incompat it was in SoS2 but ill see if i can reproduce and make a full report.

Where there any Errors logged?

**Comment by Sn1p3rr3c0n** [comment]
>  when you have eq. 5 drones out and working and clicking debug button it just list -5 drones stored and they will continue to be out until they have no more work.

I think that would be expected.
this scenario can only occur in the debug mode where the as per your example 5 drones are active and then you want to set them to 0 via the debug button.
We could change it but as it cant occur during normal play i would not see it as important by any means

**Comment by zymex22** [comment]
didn't check if there were any log on it, it was a big modlist, so had a lot of other errors, but it didn't popup with any reds, ill write down more info if i can make it happen again, i tried to stress it to see if i could reproduce =)

- it felt like it was a hauling bug of some sort but only have job of opputiny and common sense in.
no haul to stack or pickup and haul or other mod know to mess hauling up.

**Comment by Sn1p3rr3c0n** [comment]
> when power is off (no power on grid) drones that are send out will continue to work until they go back to station.
they should properly go back to station when power is lost?

I think there are two plausible viewpoints on this:
- The station is "just" a charging port _(They should return after all work is done)_
- The station is coordinating the Drones _(They should return directly)_

Currently i would agree with the second Point.

**Comment by zymex22** [comment]
i feel second solution sound best too, it could kinda be a charging station...
but i kinda more feel its a "command station" for drones, so they should return if "connection" / power is lost.

else they work kinda freely if you power off if you just can keep them busy so they do not return

**Comment by zymex22** [comment]
Drones dont like til fill DS storage @lilwhitemouse ill ofc have to blame DS for this...

anyways i saw this in misc. robots mod page:
> - Misc. Robots is compatible to Deep Storage, but you have to reduce
> the required intelligence in the Deep Storage Mod Settings

and thought it might be related here too?

**Comment by zymex22** [comment]
Should we add a line displaying assigned job types?:
```xml
        <workTypes>
          <li>BasicWorker</li>
          <li>Hauling</li>
          <li>Cleaning</li>
        </workTypes>
```
shown in inspect box to see what jobs a drone station is assigned this makes it easier to trouble shoot if having jobs mods installed and why they don do certain jobs.

also makes it easier/faster to see what job its assigned instead of see description (if we write them there)
![image](https://user-images.githubusercontent.com/41029070/94129168-5634c780-fe5b-11ea-9619-5471dde61581.png)

**Comment by zymex22** [comment]
got a stuck drone again this time it was about to and install this vent but are just standing there.
no log reported at all.

it worked just by recall drones from that station and let it go back and try again.
this dont seem to be same problem i had yesterday though, this seemed very innocent, and easy fixed

![image](https://user-images.githubusercontent.com/41029070/94136868-dceea200-fe65-11ea-9440-b146ef5a9701.png)

**Comment by Sn1p3rr3c0n** [comment]
@zymex22 Regarding the Upgrade Test the only "error" _(its a warning)_ i'm getting is:
```
Trying to get valid region at (80, 0, 132) but RegionAndRoomUpdater is disabled. The result may be incorrect.
Verse.Log:Warning(String, Boolean)
Verse.RegionGrid:GetValidRegionAt(IntVec3)
Verse.RegionAndRoomQuery:RegionAt(IntVec3, Map, RegionType)
Verse.GridsUtility:GetRegion(IntVec3, Map, RegionType)
Verse.Area:MarkDirty(IntVec3)
Verse.Area:Set(IntVec3, Boolean)
Verse.Area:set_Item(IntVec3, Boolean)
ProjectRimFactory.Drones.Building_DroneStation:get_GetDroneAllowedArea()
ProjectRimFactory.Drones.Building_DroneStation:Update_droneAllowedArea_forDrones(Area)
ProjectRimFactory.Drones.Building_DroneStation:SpawnSetup(Map, Boolean)
ProjectRimFactory.Drones.Building_DroneCultivator:SpawnSetup(Map, Boolean)
Verse.GenSpawn:Verse.GenSpawn.Spawn_Patch0(Thing, IntVec3, Map, Rot4, WipeMode, Boolean)
Verse.GenSpawn:SpawnBuildingAsPossible(Building, Map, Boolean)
Verse.Map:Verse.Map.FinalizeLoading_Patch0(Map)
Verse.Game:LoadGame()
Verse.SavedGameLoaderNow:LoadGameFromSaveFileNow(String)
Verse.<>c:<Start>b__1_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()
```

that gets spammed i some variation (different cells) Seems to be linked to the drone stations range.
No impact could be observed so far. After a new save the issue is not observed.

I will therefor check that we have performed the test and would at least for now skip searching for a way to avoid that 1 time Warning spam.

**Comment by zymex22** [comment]
1 time spam is ok, we are still in beta, and if everything is working after a reload i dont see that as a problem =)

**Comment by zymex22** [comment]
got this error while playing.
i changed one of the drone station to "unrestricted zone" i think? it might already been on it before i changed to it again.

it came every time i clicked on that drone station or it was because drones were returning im unsure about that.

- second test.
oh got it...
it comes when changing zones and then when clicking on another tile (to exist) drone station it throw that error.

https://gist.github.com/5b9be60266026a24fea964f2a1df1450

![image](https://user-images.githubusercontent.com/41029070/94261336-ff4df180-ff31-11ea-8efa-1b5db96de8b8.png)

**Comment by Sn1p3rr3c0n** [comment]
- [ ] Check for Compatibility between mods that add / Split up WorkDefs 
for example  `[FSF] Complex Jobs`

**Comment by zymex22** [comment]
not needed for release but have an idea:

Make new tab:
- [ ]  show stat level for each skill it can do, in a new collum for allow button.

thats usefull when we use:
```xml
      <li Class="ProjectRimFactory.Common.ModExtension_Skills">
        <BaseSkill>19</BaseSkill>
        <skills>
          <li>
            <def>Intellectual</def>
            <levelInt>11</levelInt>
          </li>
        </skills>
```
      </li> -->

**Comment by Sn1p3rr3c0n** [comment]
- [ ] Check what is causing the `TryMakePreToilReservations() returned false for a non-queued job right after StartJob(). This should have been checked before. curJob=RefillWater (Job_2998) A=Thing_PassiveCooler10721 B=(108, 0, 141)` Error Spam 
https://gist.github.com/HugsLibRecordKeeper/25a3a6c8bdaf690269d45d38aef142f5

For the relevant skills part use an average

**Comment by Sn1p3rr3c0n** [comment]
- [ ] if the station has no power the skills are shown as 0 instead of the correct value

**Comment by Sn1p3rr3c0n** [comment]
**Additional info for the drone standing around bug:**
The actual `job` that they perform in that case is `standing`. 
This issue seems to occur if the distance to the Job position is too great.

to prevent this in the future the following points shall be completed:
- [ ] Fix / replace that code that causes this behavior
- [ ] If a drone gets a `standing` Job replace that one with `return to base` **Or** make it impossible for drones to get that job

**Comment by zymex22** [comment]
forgot about `<Sleeptimes>22,23,24,0,1,2</Sleeptimes> <!-- SLEEEEEEP -->`
is it visable when they are off i didnt see any label or something last test?

we could maybe add info to Drone tab like:
Will work
00 - 24
Will Sleep 22,23,24,0,1,2

or make a full line:
**1 2** 3 4 5 6 7 8 9 10 11 12 13 14 15 17 18 19 20 **21 22 23 24**
and those who are "off times" make them RED color

**Comment by Sn1p3rr3c0n** [comment]
- [ ] Add Sleep times Display to the ITab

**Comment by Sn1p3rr3c0n** [comment]
- [ ] Fix Drone tab Title (its slightly cutoff atm)

**Comment by zymex22** [comment]
under set target
should we list max and min drones on either end of scale so
0 at buttom and max value at high end?

**Comment by Sn1p3rr3c0n** [comment]
- [ ] Add Min Max label for fuel level

**Comment by Sn1p3rr3c0n** [comment]
- [ ] remove the `Plant cut` Job from the Cultivators (as its not needed for the function)

**Comment by Sn1p3rr3c0n** [comment]
- [ ] Fix Issue where Drones can spawn for the mech faction(hostile). (expecting it to be a side effect from the SOS2 compatibility)

**Comment by zymex22** [comment]
Closed we will open issue for rest
