### ISSUE TITLE
Support Vanilla Renaming by using that name for the GUI

### ISSUE THREAD

**Issue by Sn1p3rr3c0n** [zymex22/Project-RimFactory-Revived#811]
> If I want to configure "For what zone" on a puller, pallets and other storage objects only are displayed with their default name. Like "wooden pallet", even if I renamed them to somtehing else. Having multiple of them it is unclear which is which.
~ `SAUSACK`

Confirmed by me

**Comment by Sn1p3rr3c0n** [comment]
For Regular Storage buildings such as DS and Vanilla Buildings that is not quite That easy.

This is caused by the Fact that one **Can't RENAME any of them** normally.
While the game makes it seem like your rename them, that is not what actually happens. 

What happens instead is that a **Settings group** is created and then you name that Group.
being a Group, that name applies to ALL members of it. That can be one or many buildings.

maybe the best option would be to show the mane and then the Group in brackets
like: `DSU (MY NAME)`   `Wooden Shelf (Steel)`

**Comment by Sn1p3rr3c0n** [comment]
![image](https://github.com/user-attachments/assets/16656c69-3871-4c19-ae56-7186d529f0e3)
I Think that looks quite clear

**Comment by ylin111** [comment]
Hello Sn1p3rr3c0n! Thank you for directing me here. Could you please tell me how I can let the Group be displayed in the bracket in the "For what zone" list of the Puller? When I rename my I/O port (which creates a group with that name and put this I/O port in this group), the name in the "For what zone" list does not change, it is still "I/O port". Is it a setting of the game or I misunderstood your method.

**Comment by Sn1p3rr3c0n** [comment]
Its resolved on the Current (but not yet released) Version of Rimfactory.

**Comment by ylin111** [comment]
> Its resolved on the Current (but not yet released) Version of Rimfactory.

Sounds great! Look forward to the new version! Thank you for the updates!
