### ISSUE TITLE
Blast furnace(+others?) does not output if output direction is into wall

### ISSUE THREAD

**Issue by lilwhitemouse** [zymex22/Project-RimFactory-Revived#83]
If you adjust the output direction for the blast furnace so it points into a wall it will happily destroy the output instead of placing it anywhere. The player gets no indication that there is a bad output cell.

**Comment by lilwhitemouse** [comment]
Okay, it doesn't destroy it; it keeps it piled up until it has a clear output zone!

In that case, maybe when it cannot place something, it should trigger an indicator that there's a blocked output slot, and its overlay text should include a line of text "Waiting to place XX items."

**Comment by lilwhitemouse** [comment]
Note: Overlay text can probably be adjusted in SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs, method GetInspectString()

**Comment by lilwhitemouse** [comment]
DrawGUIOverlay()

**Comment by zymex22** [comment]
it already has a "Waiting to place XX items." in small info box down at the corner =) but maybe not clear enough =)
it will also stay blocked if one item is output and another type is trying to output. it will wait for output cell to clear up before placing 1 prf belt are a good way of move away from output cell into a stockpile early.

**Comment by lilwhitemouse** [comment]
I will play around with it a bit, especially if I am testing DS placement.

**Comment by zymex22** [comment]
We could put in a Output blocked label to the label system we made?

either in a new line and 2 text, or just if more its list as "items waiting to be placed" it will throw a "blocked output" label instead of current label.

**Comment by lilwhitemouse** [comment]
Yeah, that was on my internal list of things to do, but got distracted from.  It should be really easy to add.

**Comment by zymex22** [comment]
Should just add:
-  label with "output blocked" if pointing into a wall. or other impassable
else if not blocked just list "items waiting to be placed" as already is
