### ISSUE TITLE
Blast furance balance question

### ISSUE THREAD

**Issue by lilwhitemouse** [zymex22/Project-RimFactory-Revived#84]
The Blast Furnace uses less power than the vanilla smelter (100 vs 250), smelts at least as fast as the vanilla smelter, and does not require a worker. Is this the intended balance for PRF?

**Comment by zymex22** [comment]
its related to #76 
i had Fueled comp on it but since it dont support it, it would run even if it ran out of fuel, so i set it to power until 76 is done :P
same goes for t1 miner but thats a different thingclass and issue #74

**Comment by zymex22** [comment]
Still waiting for #76 but for now i have raised power use on all 3 furnace to match vanilla ones i close this as #76 will balance further

**Comment by lilwhitemouse** [comment]
Wait, T0 blast furnace will be powered AND fueled?

**Comment by Steague** [comment]
@lilwhitemouse per @zymex22 on Discord, The T0 blast furnace should be fueled only. The comp isnt supported yetso it was just made electric until then. There's an issue for that comp with code. We need to solve that rare tick that we talked about. All info in that issue.
