### ISSUE TITLE
"Toggle allow forbidden" is unclear

### ISSUE THREAD

**Issue by lilwhitemouse** [zymex22/Project-RimFactory-Revived#85]
The Blast Furnace has a toggle command "Toggle allow forbidden" that determines whether it will accept input that is forbidden. Better would be "Toggle using forbidden" or "Toggle taking forbidden" or "Use[or Take] forbidden items?" so it's clear at a glance what it means. The description text was v helpful.

**Comment by zymex22** [comment]
yea might wanna update that in lang files.
this was what i ref. when we talked about allow forbidden on vacuum hopper =)
