### ISSUE TITLE
Blast furnace gives no indication it magically sucks in any input next to it.

### ISSUE THREAD

**Issue by lilwhitemouse** [zymex22/Project-RimFactory-Revived#86]
Need to update description text

**Comment by zymex22** [comment]
`    <description>A early stage Furnace. made to burn unwanted things and smelt raw rescourses into usefull materials also capable of burning stones into usefull bricks.\n\nWhite cell is input range</description>`

what should it say instead? it would make sense to do a short description on blast furnace as its first machine for many ppl
