### ISSUE TITLE
Building_ProgrammableAssembler overlay does not distinguish between "no bills" and "no input"

### ISSUE THREAD

**Issue by lilwhitemouse** [zymex22/Project-RimFactory-Revived#88]
Both are "Idle"

**Comment by zymex22** [comment]
also both are saying searching for ingredients in info box thats kinda confusing when its because there isn't setup a bill

**Comment by lilwhitemouse** [comment]
Teaching zymex C#:
Step 0. Set up a git branch (issue88, zymex-first-lesson, whatever)
1. Find the C# class associated with the Thing in question (in this case, I listed it in title)
2. Find in the C# where it prints "Idle"
2a. Find in the XML where the translated string "Idle" is - in RimWorld, there are translation keys (that are strings) that link to the actual language translation.
2b. Find that key in the code.
3. (Hardest part) figure out how to know if the assembler has any open/active bills.
4. replace the "idle" display code with an "if/then" clause:
`if ([see step 3]) { // if there are active bills (comment the code in the event step 3 is complicated/hard to read
  // do the same sort of thing the code did for "idle"
  // but change it to the new key for "Waiting for input"
  //  (I had a better phrase but forgot it over breakfast)
} else { // no active bils
  // Do the same the but use the "Nothing to do" key.
  // Actually, better might be "Awaiting instructions"
}`
5 Compile!
6.Figure out what you did wrong.
7. Fix it.
8. Compile!
9. Test in game.
10. Update the language files to link those keys to the actual phrases // maybe should be step 4 or 5:p Probably 4.
11. check in the code, make a pull request, wait for someone else to double-check it!

**Comment by lilwhitemouse** [comment]
Step 3 breakdown (LWM):
1. Look up the "class" for this building:
```    public abstract class Building_ProgrammableAssembler : Building_DynamicBillGiver, IPowerSupplyMachineHolder```
The `:` there means that the `Building_ProgrammableAssembler` class is a child class of `Building_DynamicBillGiver` and implements the `IPowerSupplyMachineHolder` interface.  If you don't know what "child class" means, go read a very basic introduction to object oriented programing.  It will probably involve either `Person` or `Animal`.
2. Well, `IPowerSupply...` doesn't look like it involves bills so ignore that.
3. Go find `Building_DynamicBillGiver`!
4. And then that is:
```    public abstract class Building_DynamicBillGiver : Building, IBillGiver```
So it's a `Building` - that's boring.  But it implements the `IBillGiver` interface!  That's vanilla!  Let's see what that offers!
5. Looking at `IBillGiver` I see it has this: `		BillStack BillStack { get; }`.  Okay, so we can get a BillStack.  Whatever that is.
6. Looking at `BillStack`, I see two things:
```
		public List<Bill> Bills
                 // ...
		public bool AnyShouldDoNow
```
Let's look at the 2nd see if it works for us.
7. Look at Bill, see what ShouldDoNow is. Super unhelpful. Look at Bill_Production.cs instead?
8. Casually read through `ShouldDoNow` - yep, looks good!
9. Our test will look like:
```
if (this.BillStack.ShouldDoNow()) {
```

**Comment by zymex22** [comment]
@lilwhitemouse can you confirm everything looks good and we can merge into develop and close this issue =)

**Comment by zymex22** [comment]
- Need Update to not say search for ingredients IF power is off.
- Also need update info box with same trick, it only say searching for ingredients always, it should match machine label we just made

**Comment by lilwhitemouse** [comment]
I got this
