### ISSUE TITLE
Update for Item tab storage (Request)

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#89]
### Malkav Requests:
I was thinking it would be nice if PRF storage had some of the interface features that LWM's Deep Storage has.
The thumbnail is messed up, you have to open the photo to see it. On the left is the contents of a PRF crate. On the right, a DS shelf unit. See how it has the check mark for forbidding, and the drop arrow for ejecting items?
Of course, unless you & him can solve the pushing of multiple stacks in, you wouldn't want to alter the current way PRF storage works.

![294100_screenshots_20200620045819_1](https://user-images.githubusercontent.com/41029070/85906033-6b269e00-b80d-11ea-9fbc-98abe2ee9629.jpg)

**Comment by zymex22** [comment]
PRF "items" tab already has a right click and drop option to output on I/O or drop on ground in front of DSU/storage.
this could be made into a drop button like in DS tab.

dunno about that check mark allow thing what that is for, you might know better than me LWM =)

**Comment by zymex22** [comment]
![image](https://user-images.githubusercontent.com/41029070/86179161-11361900-bb2a-11ea-8158-d35b4c2fc5fe.png)

If rightclick and item in storage or even on a connected I//O port in item tab, it can do this:
-output let you output into output cell or directly on a I/O port.
-by clicking one of those names it will equip it on them if its a weapon or apparel

**Comment by zymex22** [comment]
- Hairy
- Lumpy
- Trigger

are pawn names if clicking on them a new popup menu popup where you can select force wear if a apparel or weapon is chosen
@lilwhitemouse

**Comment by lilwhitemouse** [comment]
This could definitely happen!

**Comment by Steague** [comment]
I would very much like to see this feature.

**Comment by zymex22** [comment]
Is this something you can do @Sn1p3rr3c0n ?

and or do we need any pointers from @lilwhitemouse 
above pictures are comparison from LWM Deep storage mod and PRF storage content menu.

**so what we talked about in chat was:**
- Add that drop button (function already is rightclick and output item)
- Forbid/allow button to forbid pawns to take it out
- A pawn button that select what pawn to wear that item (function are on rightclick right now)
- Weight (not sure if usefull or not but meh)

**Comment by zymex22** [comment]
if we move deadline for 2.5.0 till same time as Oskars mech mod 2 week atleast till beta and out around christmas...

this would be a much loved update i think, both malkav and thorny really wanted this one to be done =)
@lilwhitemouse @Sn1p3rr3c0n 

we can properly steal most of the code from LWM's DeepStorage where source is placed =)

**Comment by lilwhitemouse** [comment]
Other requests: alphabatized sorting

**Comment by lilwhitemouse** [comment]
Other requests: in groups (like filters)

**Comment by lilwhitemouse** [comment]
(See issue #178  for the last comment)
