### ISSUE TITLE
Remove pulseglower

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#96]
i dont use this anymore:

```xml
      <li Class="ProjectRimFactory.Common.CompProperties_GlowerPulse">    Comp for pulseglow when working
        <minGlowRadius>1</minGlowRadius>                                  smallest size
        <maxGlowRadius>3</maxGlowRadius>                                  largest size
        <minGlowColor>(100,0,0,10)</minGlowColor>                         color and opacity when smallest
        <maxGlowColor>(230,0,0,100)</maxGlowColor>                        color and opacity when largest
        <intervalTicks>30</intervalTicks>                                 interval
        easingType : EasingLinear, EasingSineInOut, EasingQuadInOut, EasingCubicInOut, EasingExpInOut, EasingElasticInOut, EasingBounceInOut, EasingQuadIn, EasingQuadOut, EasingCubicIn, EasingCubicOut https://easings.net/en
        <easingType>ProjectRimFactory.Common.EasingCubicIn</easingType>   Type pulse see above link for types
      </li>
```

maybe it should be removed entirely from C# again?
it caused massive fps drops ingame when used, so i stopped using it and now its just sitting in files and doing nothing =)

Seem to have reference in miners.cs and assemblers.cs where pulseglower were used.
apparently? not in t1-2 miner only in t3.
but it was also used in t1 miner.

**Comment by lilwhitemouse** [comment]
Let's leave this open in the hope we can optimize the comp for minimal impact.

**Comment by zymex22** [comment]
We could change it to a blinking glower instead of a fading one, nobo went abit overkill with pulse/fade effect, so blinking might be better?

either way i dont think its super needed in prf it was something i thought would be nice but meh...
smoke on miners are cooler than a pulse glow =)

**Comment by lilwhitemouse** [comment]
Well, it's not doing any harm at the moment, so there's that :)

**Comment by zymex22** [comment]
i close this for now lets see if we need it later else i request it again :P
